force-app/main/default/objects/Integration_Logs__c/Integration_Logs__c.object-meta.xml
<CustomObject>
    <description>Se almacenan registros de errores de integración</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Integration Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Logs__c/fields/Body_JSON__c.field-meta.xml
<CustomField>
    <fullName>Body_JSON__c</fullName>
    <description>Json del Request que genero el error</description>
    <label>Body JSON</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/fields/Clase__c.field-meta.xml
<CustomField>
    <fullName>Clase__c</fullName>
    <description>Nombre de la clase de error</description>
    <label>Clase</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/fields/Linea__c.field-meta.xml
<CustomField>
    <fullName>Linea__c</fullName>
    <description>Línea en la que se genero el error</description>
    <label>Linea</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/fields/Mensaje_SFDC__c.field-meta.xml
<CustomField>
    <fullName>Mensaje_SFDC__c</fullName>
    <description>Exception de salesforce</description>
    <label>Mensaje SFDC</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Tipo de error</description>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CREACION_CLIENTES_SFDC</fullName>
            </value>
            <value>
                <fullName>CREACION_CLIENTES_SAP</fullName>
            </value>
            <value>
                <fullName>TOKEN_IIS</fullName>
            </value>
            <value>
                <fullName>CREAR_PEDIDO_SF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/centro_suministrador__c.field-meta.xml
<CustomField>
    <fullName>centro_suministrador__c</fullName>
    <label>Centro Suministrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Grupo_de_art_culos__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_art_culos__c</fullName>
    <label>Grupo de artículos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ESPA</fullName>
                <label>Espacios</label>
            </value>
            <value>
                <fullName>GUARQM</fullName>
                <label>Guardquim</label>
            </value>
            <value>
                <fullName>IMPERC</fullName>
                <label>Impercryl</label>
            </value>
            <value>
                <fullName>NAYA</fullName>
                <label>Naya</label>
            </value>
            <value>
                <fullName>QUIMCR</fullName>
                <label>Quimicret</label>
            </value>
            <value>
                <fullName>SELLAQ</fullName>
                <label>Sellaquim</label>
            </value>
            <value>
                <fullName>SOPORT</fullName>
                <label>Soporte</label>
            </value>
            <value>
                <fullName>DOCFIN</fullName>
                <label>Documento Financiero</label>
            </value>
            <value>
                <fullName>ACCESO</fullName>
                <label>Accesorio</label>
            </value>
            <value>
                <fullName>IQ</fullName>
                <label>Imperquimia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/IMP_IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IMP_IdExterno__c</fullName>
    <description>Almacena el número de producto de SAP</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/sku__c.field-meta.xml
<CustomField>
    <fullName>sku__c</fullName>
    <label>SKU</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/tipo_impuesto__c.field-meta.xml
<CustomField>
    <fullName>tipo_impuesto__c</fullName>
    <label>Tipo de impuesto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sujeto a impuestos</fullName>
            </value>
            <value>
                <fullName>Libre de impuesto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_IntegracionMateriales.cls
/************************************************************************
Name: IMP_IntegracionMateriales
Copyright © 2022 Salesforce
========================================================================
Purpose:
Clase que realiza la consulta de productos en SAP y actualiza los registros
en salesforce
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
 2.0      mvilchis@ts4.mx    01/04/2022     
************************************************************************/
public without sharing class IMP_IntegracionMateriales {  

    /*******************************************************************
    Purpose: Consulta una lista de materiales en SAP de acuerdo a una
    fecha de inicio y fin.
    Parameters: String fechaInicio, String fechaFinal
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    @future(callout=true)
    public static void getMateriales(String fechaInicio, String fechaFinal) {
        List<Product2> lstUpsert = new List<Product2>();
        Set<String> lstProdCode = new Set<String>();
        String body;
        String apiUrl = IMP_ServiceConstants.MATERIALES_API_URL;
        String urlFinal = 'imperquiaSAP'+apiUrl;
        String authHeader = 'BASIC ' + EncodingUtil.base64Encode(Blob.valueOf(System.Label.User_Integration + ':' + System.Label.Password_Integration));
        Map<String, String> params = new Map<String, String>();
        //String token = IMP_CrearClienteSap_CC.retriveToken().token;
        Map<String,String> headers = new Map<String,String>{'Content-Type' => 'application/json', 'Authorization' => authHeader};
        try {
            body = IMP_CreateJson.createMateriales(fechaInicio,fechaFinal);
            HttpRequest req = IMP_CalloutUtils.generateRequest(
                IMP_CalloutConstants.METHOD_POST, 
                urlFinal,
                params, 
                headers, 
                120000, 
                body
            );
            HttpResponse response = IMP_CalloutUtils.doRequest(req, true);
            IMP_IntegracionMateriales responseProducto = (IMP_IntegracionMateriales)JSON.deserialize(response.getBody(), IMP_IntegracionMateriales.class);
            for(IMP_IntegracionMateriales.cls_IT_MATERIALES prod : responseProducto.IT_MATERIALES) {
                if(prod.LVORM == 'X') {
                    lstProdCode.add(prod.MATNR.replaceFirst('^0+', ''));
                }
                else if(prod.MAKTX != '') {
                    Product2 prodNew = new Product2(Name=prod.MAKTX,centro_suministrador__c=prod.WERKS,ProductCode=prod.MATNR.replaceFirst('^0+', ''),IMP_IdExterno__c=prod.MATNR.replaceFirst('^0+', ''),
                                                Grupo_de_art_culos__c=prod.MATKL,/*Grupo_de_Materiales_c=prod.KONDM,*/sku__c=Decimal.valueOf(prod.MATNR.replaceFirst('^0+', '')),
                                                tipo_impuesto__c=prod.TAXKM,QuantityUnitOfMeasure=prod.MEINS,IsActive=true);
                    lstUpsert.add(prodNew);
                }
            }
            for(Product2 prod : [SELECT Id,ProductCode,IMP_IdExterno__c,IsActive FROM Product2 WHERE ProductCode IN : lstProdCode]) {
                prod.IsActive=false;
                lstUpsert.add(prod);
            }

            list<Database.upsertResult> uResults = Database.upsert(lstUpsert,Product2.IMP_IdExterno__c,false);
            for (Database.upsertResult res : uResults) {
                if(res.isSuccess()){
                    System.debug('Producto creado : '+ res.getId());
                }
                for (Database.Error  err : res.getErrors()) {
                    System.debug('err: ' + err);
                }
                
            }
        }
        catch(Exception exc){
            Integration_Logs__c systemLog = new Integration_Logs__c(Linea__c=String.valueOf(exc.getLineNumber()),
                                            Clase__c=exc.getTypeName().substring(0, exc.getTypeName().length()>255?200:exc.getTypeName().length())+' '+exc.getCause()+' '+exc.getStackTraceString(),
                                            Mensaje_SFDC__c=exc.getMessage(),Body_JSON__c=body,Tipo__c='GET_MATERIALES_SFDC');
        
            insert systemLog;
        }
    }
    //Juan Pedraza
    public cls_IT_MATERIALES[] IT_MATERIALES;
	public class cls_IT_MATERIALES {
		public String MATNR;//MATERIAL
		public String WERKS;//CENTRO CONSUMIDOR
		public String MAKTX;//NOMBRE MATERIAL
		public String KONWA;
		public String MATKL;//GRUPO ARTICULOS
		public String KONDM;//GRUPO MATERIALES
		public String SKU;//SKU
		public String TAXKM;//TIPO IMPUESTO
		public String PLTYP;
		public String MEINS;//UNIDAD MEDIDA
		public String LVORM;//INDICADOR BORRADO
	}
}