force-app/main/default/objects/Integration_Logs__c/Integration_Logs__c.object-meta.xml
<CustomObject>
    <description>Se almacenan registros de errores de integración</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Integration Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/centro_suministrador__c.field-meta.xml
<CustomField>
    <fullName>centro_suministrador__c</fullName>
    <label>Centro Suministrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Grupo_de_art_culos__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_art_culos__c</fullName>
    <label>Grupo de artículos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ESPA</fullName>
                <label>Espacios</label>
            </value>
            <value>
                <fullName>GUARQM</fullName>
                <label>Guardquim</label>
            </value>
            <value>
                <fullName>IMPERC</fullName>
                <label>Impercryl</label>
            </value>
            <value>
                <fullName>NAYA</fullName>
                <label>Naya</label>
            </value>
            <value>
                <fullName>QUIMCR</fullName>
                <label>Quimicret</label>
            </value>
            <value>
                <fullName>SELLAQ</fullName>
                <label>Sellaquim</label>
            </value>
            <value>
                <fullName>SOPORT</fullName>
                <label>Soporte</label>
            </value>
            <value>
                <fullName>DOCFIN</fullName>
                <label>Documento Financiero</label>
            </value>
            <value>
                <fullName>ACCESO</fullName>
                <label>Accesorio</label>
            </value>
            <value>
                <fullName>IQ</fullName>
                <label>Imperquimia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/IMP_IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IMP_IdExterno__c</fullName>
    <description>Almacena el número de producto de SAP</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/sku__c.field-meta.xml
<CustomField>
    <fullName>sku__c</fullName>
    <label>SKU</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/tipo_impuesto__c.field-meta.xml
<CustomField>
    <fullName>tipo_impuesto__c</fullName>
    <label>Tipo de impuesto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sujeto a impuestos</fullName>
            </value>
            <value>
                <fullName>Libre de impuesto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_IntegracionMateriales_Test.cls
/************************************************************************
Name: IMP_IntegracionMateriales_Test
Copyright © 2022 Salesforce
========================================================================
Purpose:
Clase test de la clase IMP_IntegracionMateriales y del scheduler
IMP_Materiales_Schedule
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      mvilchis@ts4.mx    11/04/2022     INITIAL        DEV CSR:
************************************************************************/
@isTest
public without sharing class IMP_IntegracionMateriales_Test {
    
    /*******************************************************************
    Purpose: Se inserta información de 2 productos.
    Information about changes (versions) []:
    ********************************************************************/
    @testSetup
    private static void testSetup() {
        Product2 nuevo = new Product2();
        nuevo.Name='TEST PROD';
        nuevo.centro_suministrador__c='';
        nuevo.ProductCode='10000247';
        nuevo.IMP_IdExterno__c='10000247';
        nuevo.Grupo_de_art_culos__c='IMPERC';
        nuevo.sku__c=Decimal.valueOf('10000247');
        nuevo.tipo_impuesto__c='';
        nuevo.QuantityUnitOfMeasure='UN';
        nuevo.IsActive=true;  
    	insert nuevo;

        Product2 prodNew2 = new Product2();
        prodNew2.Name='TEST PROD';
        prodNew2.centro_suministrador__c='';
        prodNew2.ProductCode='10000640';
        prodNew2.IMP_IdExterno__c='10000640';
        prodNew2.Grupo_de_art_culos__c='IMPERC';
        prodNew2.sku__c=Decimal.valueOf('10000640');
        prodNew2.tipo_impuesto__c='';
        prodNew2.QuantityUnitOfMeasure='UN';
        prodNew2.IsActive=true;  
    	insert prodNew2;
    }
    /*******************************************************************
    Purpose: Se inserta información de un producto y se realiza la llamada
    al servicio para actualizar.
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static  void materialesWS() {
        DateTime fecha=System.now();
        String hora = '0 0 23 * * ?';
        String body='{"IT_MATERIALES": [{"MATNR": "000000000010000637","WERKS": "SATE","MAKTX": "ELASTON 4 ROJO, 19LT","KONWA": "","MATKL": "IMPERC","KONDM": "08","SKU": "000000000010000637","TAXKM": "","PLTYP": "","MEINS": "UN","LVORM": ""},{"MATNR": "000000000010000640","WERKS": "","MAKTX": "ELASTON 4 BLANCO DOBLE ACCION, 19LT","KONWA": "","MATKL": "IQ","KONDM": "03","SKU": "000000000010000640","TAXKM": "","PLTYP": "","MEINS": "UN","LVORM": "X"},{"MATNR": "000000000010000247","WERKS": "SATE","MAKTX": "GUARDQUIM EPOXI 630 AQUA TRANSPAREN, 4LT","KONWA": "","MATKL": "GUARQM","KONDM": "03","SKU": "000000000010000247","TAXKM": "","PLTYP": "","MEINS": "UN","LVORM": "X"}]}';
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(200, 'OK', body, null));
        Test.startTest();

            String jobId = System.schedule('IMP_Materiales_Schedule',
                hora,
                new IMP_Materiales_Schedule());      
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
            NextFireTime
            FROM CronTrigger WHERE id = :jobId];
            System.assertEquals(0, ct.TimesTriggered,'ok');
        Test.stopTest();
    }
    @isTest
    public static void materialesWS1() {
        Test.startTest();
        IMP_IntegracionMateriales.getMateriales('20220328','20220328');
        Test.stopTest(); 
        list<Integration_Logs__c> listIntegraciones=[SELECT Id FROM Integration_Logs__c];
        System.assertEquals(2, listIntegraciones.size(),'ok');
    }

    
    

}