force-app/main/default/objects/Pricebook2/fields/IMP_Update__c.field-meta.xml
<CustomField>
    <fullName>IMP_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bander</description>
    <label>Actualizado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Lista_de_precios_SAP__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_precios_SAP__c</fullName>
    <label>Lista de precios SAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lista_de_precios_SAP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lista_de_precios_SAP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <masterLabel>Lista de precios SAP</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_EjecutarJobs_cc.cls
/************************************************************************
Name: IMP_EjecutarJobs_cc
Copyright © 2022 Salesforce
========================================================================
Purpose:
Servicio web para la consulta de documentos de un pedido desde SAP 
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
 1.0      rotrejo@ts4.mx      19/04/2023    
************************************************************************/
public without sharing class IMP_EjecutarJobs_cc {

    @AuraEnabled
    public static void getPrices() {
        List<Pricebook2> listPrecio = [SELECT Id, Name , IMP_update__c , Sucursal__c, Lista_de_precios_SAP__c FROM Pricebook2 WHERE IsStandard=false FOR UPDATE];
        for(Pricebook2 precio : listPrecio){
            precio.IMP_update__c= false;
        }
        update listPrecio;
        Database.executeBatch(new IMP_UpdateParentPrices());
    }
    
    /*******************************************************************
    Purpose: Actualiza los materiales al dia de hoy.
    Parameters:
    Returns:
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/ 
    @AuraEnabled
    public static void getMateriales(Date fechaInicio,Date fechaFin){
        String fechaInicial=Datetime.newInstance(fechaInicio, Time.newInstance(12, 0, 0, 0)).format('YYYY/MM/dd');
        String fechaFinal=Datetime.newInstance(fechaFin, Time.newInstance(12, 0, 0, 0)).format('YYYY/MM/dd');
        IMP_IntegracionMateriales.getMateriales(fechaFinal.replace('/',''),fechaFinal.replace('/',''));
    }
    
    
    /*******************************************************************
    Purpose: Actualiza los materiales al dia de hoy.
    Parameters:
    Returns:
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/ 
    @AuraEnabled
    public static IMP_FlujoDocumentos.Wrapper  getFacturas(Date fechaInicio,Date fechaFin){
   
        Integer days = fechaInicio.daysBetween(fechaFin);
        IMP_FlujoDocumentos.Wrapper newWrapper;
        try{
            if(days>7){
                AuraHandledException e = new AuraHandledException('');
                e.setMessage('El período de consulta no debe ser mayor a 7 días.');
                throw e;
                
            }else{
                String fechaInicial=Datetime.newInstance(fechaInicio, Time.newInstance(12, 0, 0, 0)).format('dd/MM/YYYY');
                String fechaFinal=Datetime.newInstance(fechaFin, Time.newInstance(12, 0, 0, 0)).format('dd/MM/YYYY');
                newWrapper = IMP_FlujoDocumentos.getFacturasWrapper(null,fechaInicial.replace('/','.'),fechaFinal.replace('/','.'));
                if(newWrapper.listFacturas != null){
                    Database.executeBatch(new IMP_BatchDocumentos(newWrapper.listFacturas),10000);
                }  
            }
        }catch(Exception ex){
            System.debug(ex.getLineNumber());
            System.debug(ex.getMessage());
             throw new AuraHandledException(ex.getMessage()); 
        }
        
      
        return newWrapper;
    }
    
    
    /*******************************************************************
    Purpose: Actualiza los descuentos
    Parameters:
    Returns:
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/ 
    @AuraEnabled
    public static void getDescuentos(){
        try{
           // Database.executeBatch(new IMP_BatchDescuentos(),10000);
           IMP_DescuentosManager.upsertDiscounts();
        }catch(Exception ex){
            throw new AuraHandledException(ex.getMessage()); 
        }        
    }
    
    /*******************************************************************
    Purpose: Actualiza los materiales al dia de hoy.
    Parameters:
    Returns:
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/ 
    @AuraEnabled
    public static void getPedidos(Date fechaInicio,Date fechaFin){
        String fechaInicial=Datetime.newInstance(fechaInicio, Time.newInstance(12, 0, 0, 0)).format('dd/MM/YYYY').replace('/','-');
        String fechaFinal=Datetime.newInstance(fechaFin, Time.newInstance(12, 0, 0, 0)).format('dd/MM/YYYY').replace('/','-');
        Database.executeBatch(new IMP_BatchPedidos(IMP_ListPedido.getListPedido(fechaInicial,fechaFinal)),10000);

    }
    
}