force-app/main/default/objects/Pricebook2/fields/Lista_de_precios_SAP__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_precios_SAP__c</fullName>
    <label>Lista de precios SAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lista_de_precios_SAP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <description>Almacena la llave prod.Id+&apos;/&apos;+listaPrecios.Name</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/sku__c.field-meta.xml
<CustomField>
    <fullName>sku__c</fullName>
    <label>SKU</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lista_de_precios_SAP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <masterLabel>Lista de precios SAP</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_PriceManager_tst.cls
/************************************************************************
Name: IMP_PriceManager_tst
Copyright © 2022 Salesforce
========================================================================
Purpose:
Test del controlador IMP_PriceManager
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      rotrejo@ts4.mx    11/04/2022     INITIAL        DEV CSR:
************************************************************************/
@isTest
public class IMP_PriceManager_tst {
    
    /*******************************************************************
    Purpose: Inserta datos de prueba
    Information about changes (versions) []:
    ********************************************************************/
    @testSetup static void inicializarDatos()
    {
        List<Product2> listProds = new  List<Product2>();
        for(Integer i = 1 ; i<= 20 ; i++){
            listProds.add(new Product2(Name='GUARDQUIM POLI RA 28, 18LT z'+i, ProductCode='1000010'+i, Family='2200 - MATIX', 
                                       CurrencyIsoCode='USD', sku__c =10000686+i));
        }
        insert listProds;
        Pricebook2  listaPrecios= new Pricebook2(Name='MIXC-Mostrador',CurrencyIsoCode='MXN',  Description ='Mixcoac',
                                                 Sucursal__c='MIXC',Lista_de_precios_SAP__c='03');
        insert listaPrecios;
        Pricebook2 pricebook= new Pricebook2();
        pricebook.Id=Test.getStandardPricebookId();
        update pricebook;
        List<PricebookEntry> listPricebooks = new  List<PricebookEntry>();
        listPricebooks.add(new PricebookEntry(Product2Id=listProds[0].Id,Pricebook2Id=pricebook.Id,UnitPrice=0));
        listPricebooks.add(new PricebookEntry(Product2Id=listProds[1].Id,Pricebook2Id=pricebook.Id,UnitPrice=0));
        listPricebooks.add(new PricebookEntry(Product2Id=listProds[0].Id,Pricebook2Id=listaPrecios.Id,UnitPrice=1000,IdExterno__c=listProds[0].Id+'/'+listaPrecios.Name));
        insert listPricebooks;
    }
    
    /*******************************************************************
    Purpose: Covertura de la clase IMP_PriceManager al metodo getPrices
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void getPricesTest()
    {
        List<IMP_PriceManager.cls_MATPRECIO> listaProductos= new List<IMP_PriceManager.cls_MATPRECIO>();
        for(Product2 prod : [SELECT Id, ProductCode FROM Product2 Limit 20]){
            IMP_PriceManager.cls_MATPRECIO prodResponse = new IMP_PriceManager.cls_MATPRECIO();
            prodResponse.VKBUR='MIXC';
            prodResponse.PLTYP='03';
            prodResponse.MATNR=prod.ProductCode;
            prodResponse.NETWR=Decimal.valueof((Math.random() * 10000));
            prodResponse.KONWA='MXN';
            listaProductos.add(prodResponse);
        }
        IMP_PriceManager respuesta = new IMP_PriceManager();
        respuesta.MATPRECIO=listaProductos;
        String body=JSON.serialize(respuesta);        

        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        IMP_PriceManager.getPrices();
        System.assertEquals(1, [SELECT id FROM PricebookEntry WHERE Pricebook2.Name='MIXC-Mostrador'].Size(),'ok');
        Test.stopTest();
    }
    
    
        /*******************************************************************
    Purpose: Se inserta información de un producto y se realiza la llamada
    al servicio para actualizar.
    Information about changes (versions) []:
    ********************************************************************/
	@isTest
    public static void materialesWS() {

        Test.startTest();
        String body='{"IT_MATERIALES": [{"MATNR": "000000000010000637","WERKS": "SATE","MAKTX": "ELASTON 4 ROJO, 19LT","KONWA": "","MATKL": "IMPERC","KONDM": "08","SKU": "000000000010000637","TAXKM": "","PLTYP": "","MEINS": "UN","LVORM": ""},{"MATNR": "000000000010000640","WERKS": "","MAKTX": "ELASTON 4 BLANCO DOBLE ACCION, 19LT","KONWA": "","MATKL": "IQ","KONDM": "03","SKU": "000000000010000640","TAXKM": "","PLTYP": "","MEINS": "UN","LVORM": "X"},{"MATNR": "000000000010000247","WERKS": "SATE","MAKTX": "GUARDQUIM EPOXI 630 AQUA TRANSPAREN, 4LT","KONWA": "","MATKL": "GUARQM","KONDM": "03","SKU": "000000000010000247","TAXKM": "","PLTYP": "","MEINS": "UN","LVORM": "X"}]}';
        Date fechaInicial=Date.today();
        Date fechaFinal=Date.today();
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(200, 'OK', body, null));
        IMP_PriceManager.getMateriales(fechaInicial,fechaFinal);
        System.assertEquals(true, [SELECT id FROM Product2 ].Size()>0,'ok');
        Test.stopTest();
    }
    
    /*******************************************************************
    Purpose: Se inserta información de un producto y se realiza la llamada
    al servicio para actualizar.
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void priceJOBTest() {
        
        DateTime fecha=System.now();
        String hora = '0 0 0 '+fecha.day()+' '+ fecha.month()+' ? ';
        Test.startTest();
        List<IMP_PriceManager.cls_MATPRECIO> listaProductos= new List<IMP_PriceManager.cls_MATPRECIO>();
        for(Product2 prod : [SELECT Id, ProductCode FROM Product2 Limit 20]){
            IMP_PriceManager.cls_MATPRECIO prodResponse = new IMP_PriceManager.cls_MATPRECIO();
            prodResponse.VKBUR='MIXC';
            prodResponse.PLTYP='03';
            prodResponse.MATNR=prod.ProductCode;
            prodResponse.NETWR=Decimal.valueof((Math.random() * 10000));
            prodResponse.KONWA='MXN';
            listaProductos.add(prodResponse);
        }
        IMP_PriceManager respuesta = new IMP_PriceManager();
        respuesta.MATPRECIO=listaProductos;
        String body=JSON.serialize(respuesta);        
        
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(200, 'OK', body, null));
        String jobId = System.schedule('SCHEDULER PRECIOS',hora,new IMP_PriceJOB());  
        System.assertEquals(1, [SELECT id FROM PricebookEntry WHERE Pricebook2.Name='MIXC-Mostrador'].Size(),'ok');
        Test.stopTest();
    }
}