force-app/main/default/objects/Product2/fields/centro_suministrador__c.field-meta.xml
<CustomField>
    <fullName>centro_suministrador__c</fullName>
    <label>Centro Suministrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/sku__c.field-meta.xml
<CustomField>
    <fullName>sku__c</fullName>
    <label>SKU</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_InventarioManager_tst.cls
/************************************************************************
Name: IMP_InventarioManager_tst
Copyright © 2022 Salesforce
========================================================================
Purpose:
Test del controlador IMP_InventarioManager
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      rotrejo@ts4.mx    11/04/2022     INITIAL        DEV CSR:
************************************************************************/

@isTest
public class IMP_InventarioManager_tst {
    
    /*******************************************************************
    Purpose: Covertura de las clases getInventario/getProdInventario
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void getInventarioTest()
    {
        IMP_InventarioManager respuesta = new IMP_InventarioManager();
        List<IMP_InventarioManager.cls_ZINVENTARIOS> listProd= new List<IMP_InventarioManager.cls_ZINVENTARIOS>();
        IMP_InventarioManager.cls_ZINVENTARIOS prod= new IMP_InventarioManager.cls_ZINVENTARIOS();
        prod.CHARG='0000092273';
        prod.CLABS=100;
        prod.HSDAT='2021-08-12';
        prod.MATNR='10000311';
        listProd.add(prod);
        IMP_InventarioManager.cls_ZINVENTARIOS prod2= new IMP_InventarioManager.cls_ZINVENTARIOS();
        prod2.CHARG='0000092273';
        prod2.CLABS=100;
        prod2.HSDAT='2021-08-12';
        prod2.MATNR='10000311';
        listProd.add(prod2);
        respuesta.ZINVENTARIOS=listProd;
        String body=JSON.serialize(respuesta);        

        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        List<IMP_InventarioManager.cls_ZINVENTARIOS> listProdResponse = IMP_InventarioManager.getInventario(new List<String>{'10000311'},'IMPQ');
        Assert.isTrue(listProdResponse.size()==2);
        Assert.isTrue(listProdResponse[0].MATNR=='10000311');
        Test.stopTest();
        
    }
    
    
    /*******************************************************************
    Purpose: Covertura de las clases getInventario
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void getInventariov2Test()
    {
        insert new Product2(Name='GUARDQUIM POLI RA 28, 18LT z', ProductCode='10000311', Family='2200 - MATIX', 
                                       CurrencyIsoCode='USD', sku__c =10000686); 
        
        IMP_InventarioManager respuesta = new IMP_InventarioManager();
        List<IMP_InventarioManager.cls_ZINVENTARIOS> listProd= new List<IMP_InventarioManager.cls_ZINVENTARIOS>();
        IMP_InventarioManager.cls_ZINVENTARIOS prod= new IMP_InventarioManager.cls_ZINVENTARIOS();
        prod.CHARG='0000092273';
        prod.CLABS=100;
        prod.HSDAT='2021-08-12';
        prod.MATNR='10000311';
        listProd.add(prod);
        IMP_InventarioManager.cls_ZINVENTARIOS prod2= new IMP_InventarioManager.cls_ZINVENTARIOS();
        prod2.CHARG='0000092273';
        prod2.CLABS=100;
        prod2.HSDAT='2021-08-12';
        prod2.MATNR='10000311';
        listProd.add(prod2);
        respuesta.ZINVENTARIOS=listProd;
        String body=JSON.serialize(respuesta);        

        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        IMP_ConsultaInventarioController.Wrapper data = IMP_ConsultaInventarioController.getInicialData('centro_suministrador__c');
        list<IMP_ConsultaInventarioController.Wrapper> listInventario = new  list<IMP_ConsultaInventarioController.Wrapper> ();
        IMP_ConsultaInventarioController.Wrapper inventario =  IMP_ConsultaInventarioController.getInventario('10000311','Imperquimia');
        listInventario.add(inventario);
        System.assertEquals(false, listInventario.size()>1,'Ok');
        Test.stopTest();
        
    }
    
    /*******************************************************************
    Purpose: Covertura de las clases getCatalogo
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void getCatalogoTest()
    {
        Test.startTest();
        List<String> catalogos= IMP_ConsultaInventarioController.getCatalogo('centro_suministrador__c');
        System.assertEquals(true, catalogos.size()>0,'ok');
        Test.stopTest(); 
    }
    
    /*******************************************************************
    Purpose: Covertura de las clases getInventario
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void getInventarioError()
    {
        Test.startTest();
        list<IMP_ConsultaInventarioController.Wrapper> listInventario = new  list<IMP_ConsultaInventarioController.Wrapper> ();
        IMP_ConsultaInventarioController.Wrapper inventario = IMP_ConsultaInventarioController.getInventario(null,'Imperquimia');
        listInventario.add(inventario);
        System.assertEquals(false, listInventario.size()>1,'Ok');
        Test.stopTest();  
    }
}