force-app/main/default/objects/Product2/fields/Grupo_de_Materiales__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Materiales__c</fullName>
    <label>Grupo de Materiales</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_de_materiales</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Productos__c/Productos__c.object-meta.xml
<CustomObject>
    <label>Material Solicitado</label>
    <nameField>
        <label>Nombre de Material Solicitado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materiales Solicitados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Productos__c/fields/Lista_de_precios__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_precios__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista de precios</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Materiales Solicitados</relationshipLabel>
    <relationshipName>Materiales_Solicitados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Productos__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Materiales Solicitados</relationshipLabel>
    <relationshipName>Materiales_Solicitados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Productos__c/fields/Solicitud_de_Pintura_Rotulaci_n__c.field-meta.xml
<CustomField>
    <fullName>Solicitud_de_Pintura_Rotulaci_n__c</fullName>
    <label>Solicitud de Pintura Rotulación</label>
    <referenceTo>Solicitud_de_Pintura_Rotulaci_n__c</referenceTo>
    <relationshipLabel>Materiales Solicitados</relationshipLabel>
    <relationshipName>Materiales_Solicitados</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pintura_Rotulaci_n__c/Solicitud_de_Pintura_Rotulaci_n__c.object-meta.xml
<CustomObject>
    <description>Gestionar las solicitudes de pintura rotulación para la fachada de nuevos clientes</description>
    <label>Solicitud de Pintura Rotulación</label>
    <nameField>
        <label>Nombre de Solicitud de Pintura Rotulación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitudes de Pinturas Rotulaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solicitud_de_Pintura_Rotulaci_n__c/fields/Compra_Trimestral__c.field-meta.xml
<CustomField>
    <fullName>Compra_Trimestral__c</fullName>
    <label>Compra Trimestral</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pintura_Rotulaci_n__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>Pendiente de Autorización</fullName>
            </value>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Preparación de Material</fullName>
            </value>
            <value>
                <fullName>Entrega en Almacén Planta</fullName>
            </value>
            <value>
                <fullName>Pintura No Entregada</fullName>
            </value>
            <value>
                <fullName>Pintura Entregada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solicitud_de_Pintura_Rotulaci_n__c/fields/Tipo_de_Solicitud__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Solicitud__c</fullName>
    <label>Tipo de Solicitud</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo Distribuidor</fullName>
            </value>
            <value>
                <fullName>Nuevo Punto de Venta</fullName>
            </value>
            <value>
                <fullName>Renovación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Grupo_de_materiales.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Lineas Generales</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Lineas Mayoristas</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Lineas Populares</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Commodity</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Especiales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Ultra Comodity</label>
    </customValue>
    <masterLabel>Grupo de materiales</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Material_solicitado_Test.cls
@isTest
public without sharing class Material_solicitado_Test {

/******************************************************************* 
    Purpose: Inserts all information to run the class method.
    Information about changes (versions):
    ********************************************************************/    
    @testSetup static void setup(){
  
                        
        Product2 prod =new Product2();
        prod.Name = 'ELASTON ROJO 12L';
        prod.ProductCode='100028-I';
        prod.Family = 'Naya';
        prod.Description = '';
        prod.IsActive = true;
        prod.CurrencyIsoCode='MXN';
        prod.Grupo_de_Materiales__c ='03';            
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId(); 

        PricebookEntry pbeSt = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            IsActive = true,
            CurrencyIsoCode='MXN',
            UnitPrice = 1100,
            UseStandardPrice=false
        );
        
        insert pbeSt;
        
        Solicitud_de_pintura_rotulaci_n__c Solicitud_de_pintura_rotulaci_n = new Solicitud_de_pintura_rotulaci_n__c(
        Name = 'Solicitud distribuidor test4',
        Estatus__c ='Nuevo',
        Tipo_de_Solicitud__c ='Nuevo Distribuidor',
        Compra_Trimestral__c =160000
        );
        
        insert Solicitud_de_Pintura_Rotulaci_n;
            
        
        Productos__c material_solicitado = new productos__c (
        Name ='Producto Test 5',
        Lista_de_precios__c = pricebookId,
        Producto__c = prod.Id,
        Solicitud_de_pintura_Rotulaci_n__c  = solicitud_de_pintura_Rotulaci_n.Id
        );
        
        insert material_solicitado;
        
        
    }
/******************************************************************* 
Purpose: Test class method to consult the PricebookEntry in relation to the Product and Price list of the sample.
Parameters:PricebookEntry pricebook , Id cotizacion.
Returns: 
Throws :
Information about changes (versions)
********************************************************************/   
    @isTest public static void crearMaterialsolicitado(){
        Productos__c material_solicitado = [SELECT Id FROM Productos__c WHERE Name ='Producto Test 5'];
    }
    

}