force-app/main/default/objects/Account/fields/billing_address_state__c.field-meta.xml
<CustomField>
    <fullName>billing_address_state__c</fullName>
    <label>Estado de facturación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGS</fullName>
                <label>AGUASCALIENTES</label>
            </value>
            <value>
                <fullName>BC</fullName>
                <label>BAJA CALIFORNIA</label>
            </value>
            <value>
                <fullName>BCS</fullName>
                <label>BAJA CALIFORNIA S</label>
            </value>
            <value>
                <fullName>CHI</fullName>
                <label>CHIHUAHUA</label>
            </value>
            <value>
                <fullName>CHS</fullName>
                <label>CHIAPAS</label>
            </value>
            <value>
                <fullName>CMP</fullName>
                <label>CAMPECHE</label>
            </value>
            <value>
                <fullName>CMX</fullName>
                <label>CIUDAD DE MÉXICO</label>
            </value>
            <value>
                <fullName>COA</fullName>
                <label>COAHUILA</label>
            </value>
            <value>
                <fullName>COL</fullName>
                <label>COLIMA</label>
            </value>
            <value>
                <fullName>DGO</fullName>
                <label>DURANGO</label>
            </value>
            <value>
                <fullName>GRO</fullName>
                <label>GUERRERO</label>
            </value>
            <value>
                <fullName>GTO</fullName>
                <label>GUANAJUATO</label>
            </value>
            <value>
                <fullName>HGO</fullName>
                <label>HIDALGO</label>
            </value>
            <value>
                <fullName>JAL</fullName>
                <label>JALISCO</label>
            </value>
            <value>
                <fullName>MCH</fullName>
                <label>MICHOACÁN</label>
            </value>
            <value>
                <fullName>MEX</fullName>
                <label>ESTADO DE MÉXICO</label>
            </value>
            <value>
                <fullName>MOR</fullName>
                <label>MORELOS</label>
            </value>
            <value>
                <fullName>NAY</fullName>
                <label>NAYARIT</label>
            </value>
            <value>
                <fullName>NL</fullName>
                <label>NUEVO LEÓN</label>
            </value>
            <value>
                <fullName>OAX</fullName>
                <label>OAXACA</label>
            </value>
            <value>
                <fullName>PUE</fullName>
                <label>PUEBLA</label>
            </value>
            <value>
                <fullName>QR</fullName>
                <label>QUINTANA ROO</label>
            </value>
            <value>
                <fullName>QRO</fullName>
                <label>QUERÉTARO</label>
            </value>
            <value>
                <fullName>SIN</fullName>
                <label>SINALOA</label>
            </value>
            <value>
                <fullName>SLP</fullName>
                <label>SAN LUIS POTOSÍ</label>
            </value>
            <value>
                <fullName>SON</fullName>
                <label>SONORA</label>
            </value>
            <value>
                <fullName>TAB</fullName>
                <label>TABASCO</label>
            </value>
            <value>
                <fullName>TLX</fullName>
                <label>TLAXCALA</label>
            </value>
            <value>
                <fullName>TMS</fullName>
                <label>TAMAULIPAS</label>
            </value>
            <value>
                <fullName>VER</fullName>
                <label>VERACRUZ</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Colonia__c.field-meta.xml
<CustomField>
    <fullName>Colonia__c</fullName>
    <label>Colonia</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/condiciones_de_pago__c.field-meta.xml
<CustomField>
    <fullName>condiciones_de_pago__c</fullName>
    <defaultValue>&quot;NT00&quot;</defaultValue>
    <label>Condiciones de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NT00</fullName>
                <label>Pagado a la recepcion</label>
            </value>
            <value>
                <fullName>NT08</fullName>
                <label>Vencimiento 08 dias</label>
            </value>
            <value>
                <fullName>NT15</fullName>
                <label>Vencimiento 15 dias</label>
            </value>
            <value>
                <fullName>NT20</fullName>
                <label>Vencimiento 20 dias</label>
            </value>
            <value>
                <fullName>NT30</fullName>
                <label>Vencimiento 30 dias</label>
            </value>
            <value>
                <fullName>NT45</fullName>
                <label>Vencimiento 45 dias</label>
            </value>
            <value>
                <fullName>NT60</fullName>
                <label>Vencimiento 60 dias</label>
            </value>
            <value>
                <fullName>NT90</fullName>
                <label>Vencimiento 90 dias</label>
            </value>
            <value>
                <fullName>NT120</fullName>
                <label>Vencimiento 120 dias</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <label>Delegación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_de_Cuentas__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Cuentas__c</fullName>
    <label>Grupo de Cuentas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>121000</fullName>
                <default>true</default>
                <label>Clientes Nacionales</label>
            </value>
            <value>
                <fullName>121001</fullName>
                <label>Clientes Extranjeros</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/grupo_de_tesoreria__c.field-meta.xml
<CustomField>
    <fullName>grupo_de_tesoreria__c</fullName>
    <label>Grupo de tesorería</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y01</fullName>
                <default>true</default>
                <label>C-Nacional</label>
            </value>
            <value>
                <fullName>Y02</fullName>
                <label>C-Exporta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_Exterior__c.field-meta.xml
<CustomField>
    <fullName>Numero_Exterior__c</fullName>
    <description>Número exterior de la cuenta</description>
    <label>Número Exterior</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_Interior__c.field-meta.xml
<CustomField>
    <fullName>Numero_Interior__c</fullName>
    <description>Contiene el número interior de la cuenta</description>
    <label>Número Interior</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OrganizacionVentas__c.field-meta.xml
<CustomField>
    <fullName>OrganizacionVentas__c</fullName>
    <label>Organización de Ventas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GOGA</fullName>
                <label>Gogal</label>
            </value>
            <value>
                <fullName>GRAV</fullName>
                <label>Graviq</label>
            </value>
            <value>
                <fullName>IMPQ</fullName>
                <default>true</default>
                <label>Imperquimia SA de CV</label>
            </value>
            <value>
                <fullName>IQSE</fullName>
                <label>IQ Servicios</label>
            </value>
            <value>
                <fullName>LEMA</fullName>
                <label>Lemma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RegimenFiscal__c.field-meta.xml
<CustomField>
    <fullName>RegimenFiscal__c</fullName>
    <description>Tipo de regimen fiscal de la cuenta</description>
    <label>Regímen Fiscal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>601</fullName>
                <label>General de Ley Personales Morales</label>
            </value>
            <value>
                <fullName>603</fullName>
                <label>Personas Morales con fines no lucrativos</label>
            </value>
            <value>
                <fullName>605</fullName>
                <label>Sueldos y Salarios e ingresos Asimilados a Salarios</label>
            </value>
            <value>
                <fullName>606</fullName>
                <label>Arrendamiento</label>
            </value>
            <value>
                <fullName>607</fullName>
                <label>Régimen de Enajenación o Adquisición de Bienes</label>
            </value>
            <value>
                <fullName>608</fullName>
                <label>Demás Ingresos</label>
            </value>
            <value>
                <fullName>610</fullName>
                <label>Residentes en el Extranjero Sin Establecimiento Permanente en México</label>
            </value>
            <value>
                <fullName>611</fullName>
                <label>Ingresos por Dividendos (Socios y Accionistas)</label>
            </value>
            <value>
                <fullName>612</fullName>
                <label>Personas Físicas con Actividades Empresariales y Profesionales</label>
            </value>
            <value>
                <fullName>614</fullName>
                <label>Ingresos por intereses</label>
            </value>
            <value>
                <fullName>615</fullName>
                <label>Régimen de los ingresos por obtención de premios</label>
            </value>
            <value>
                <fullName>616</fullName>
                <label>Sin obligaciones fiscales</label>
            </value>
            <value>
                <fullName>620</fullName>
                <label>Sociedad Cooperativas de Producción que optan por diferir sus ingresos</label>
            </value>
            <value>
                <fullName>621</fullName>
                <label>Incorporación Fiscal</label>
            </value>
            <value>
                <fullName>622</fullName>
                <label>Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras</label>
            </value>
            <value>
                <fullName>623</fullName>
                <label>Opcional para Grupos de Sociedades</label>
            </value>
            <value>
                <fullName>624</fullName>
                <label>Coordinados</label>
            </value>
            <value>
                <fullName>625</fullName>
                <label>Régimen de las Actividades Empresariales con Ingresos a través de Plataformas Tecnológicas</label>
            </value>
            <value>
                <fullName>626</fullName>
                <label>Régimen Simplificado de Confianza</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RFC__c.field-meta.xml
<CustomField>
    <fullName>RFC__c</fullName>
    <description>RFC del cliente, para persona física 12 dígitos y para moral 13</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <default>true</default>
                <label>Asfalticos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ViaPago__c.field-meta.xml
<CustomField>
    <fullName>ViaPago__c</fullName>
    <label>Vía de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>via_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/via_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>C</fullName>
        <label>Cheque</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>Deposito</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>Efectivo</label>
    </customValue>
    <customValue>
        <fullName>F</fullName>
        <label>Tarjeta de crédito</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Cheque Prod IQ</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>Tarjeta de Débito</label>
    </customValue>
    <customValue>
        <fullName>I</fullName>
        <label>Nota de Credito</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Por Definir</label>
    </customValue>
    <customValue>
        <fullName>T</fullName>
        <label>Transferencia Bancaria</label>
    </customValue>
    <masterLabel>Via de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_CreateJson.cls
/************************************************************************
Name: IMP_CreateJson
Copyright © 2022 Salesforce
========================================================================
Purpose:
Genera Json para cuentas y materiales para realizar el post al servicio
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
2.0            mvilchis@ts4.mx    11/04/2022     
3.0            rortega@ts4.mx    24/03/2022   Se agregan campos personalizados al método createJsonAccount (Código postal y Calle)
************************************************************************/
public without sharing class IMP_CreateJson {

    /*******************************************************************
    Purpose: Genera el token
    Returns: String
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    @AuraEnabled
    public static String getToken() {
        Map<String, String> mapToken = new Map<String, String>{
            'Username' => System.Label.User_Integration,
            'Password' => System.Label.Password_Integration
        };
        String jsonToken = JSON.serialize(mapToken);
        return jsonToken;
    }
    /*******************************************************************
    Purpose: Genera el json de cuentas
    Parameters: List<Id> lstId
    Returns: String
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    @AuraEnabled
    public static String createJsonAccount(List<Id> lstId) {
        String jsonString;
        Map<String,Contact> mapContact = new Map<String,Contact>();
        Map<String, String> mapAccount = new Map<String, String>();
        List<Account> lstAcc = new List<Account>([SELECT Id,AccountNumber,id_de_sap__c,/*Pais de Facturación,*/Name,/*nombre2,Street,*/Numero_Interior__c,Numero_Exterior__c,Owner.Grupo_de_Vendedor__c, 
                                                  Colonia__c,BillingStreet,ShippingStreet,Delegacion__c,BillingPostalCode,ShippingPostalCode,billing_address_state__c,Phone,/*MobilePhone,*/CorreoElectronico__c, 
                                                  RegimenFiscal__c,RFC__c,Grupo_de_Cuentas__c,grupo_de_tesoreria__c,condiciones_de_pago__c,/*ViaPago__c,*/OrganizacionVentas__c,
                                                  clave_delcanal__c,Sector__c,zona_de_ventas__c,centro_suministrador__c,grupo__c,CurrencyIsoCode,Grupo_de_precios__c,
                                                  ListaPrecios__c,BillingCountry,ShippingCountry,Intercoms_1__c,Intercoms_2__c,GrupoImputacion__c,Tipo_de_persona__c,IMP_PaisFacturacion__c/*,impuesto*/
                                                  , IMP_Calle__c, IMP_CodigoPostal__c,ViaPago__c,Apellidos__c
                                                 FROM Account
                                                 WHERE Id IN : lstId]);
        for(Contact contAcc : [SELECT Id,AccountId,MobilePhone
                               FROM Contact
                               WHERE AccountId IN : lstAcc]) {
            mapContact.put(contAcc.AccountId,contAcc);
        }

        for(Account a : lstAcc) {
            
            //System.debug('nombreCuenta');
            //System.debug(nombreCuenta);
            String grupoVendedor=a.Owner.Grupo_de_Vendedor__c<10?'00'+a.Owner.Grupo_de_Vendedor__c:''+a.Owner.Grupo_de_Vendedor__c;
            
            mapAccount.put('I_KUNNR_SF',EncodingUtil.base64Encode(Blob.valueOf(a.Id+'')));
            mapAccount.put('I_LAND',EncodingUtil.base64Encode(Blob.valueOf(a.IMP_PaisFacturacion__c+'')));
            if (a.Tipo_de_persona__c==true) {
                String nombreCuenta = a.Name.toUpperCase();
                String apellidoCuenta = a.Apellidos__c.toUpperCase();
                mapAccount.put('I_NAME1',EncodingUtil.base64Encode(Blob.valueOf(nombreCuenta+'')));
                mapAccount.put('I_NAME2',EncodingUtil.base64Encode(Blob.valueOf(apellidoCuenta+'')));
            } else {
                List<String> nombreCuenta1 = splitString(a.Name.toUpperCase());
                mapAccount.put('I_NAME1',EncodingUtil.base64Encode(Blob.valueOf(nombreCuenta1.size()>=1 ? nombreCuenta1[0]:'')));
                mapAccount.put('I_NAME2',EncodingUtil.base64Encode(Blob.valueOf(nombreCuenta1.size()>=2 ? nombreCuenta1[1]:'')));
                mapAccount.put('I_NAME3',EncodingUtil.base64Encode(Blob.valueOf(nombreCuenta1.size()>=3 ? nombreCuenta1[2]:'')));
                mapAccount.put('I_NAME4',EncodingUtil.base64Encode(Blob.valueOf(nombreCuenta1.size()>=4 ? nombreCuenta1[3]:'')));
            }
            
            mapAccount.put('I_TEL1', EncodingUtil.base64Encode(Blob.valueOf(a.Phone)));
            mapAccount.put('I_CITY1', EncodingUtil.base64Encode(Blob.valueOf((String.isNotEmpty(a.Colonia__c) ? a.Colonia__c.trim().toUppercase() : a.Colonia__c+''))));
            mapAccount.put('I_CITY2', EncodingUtil.base64Encode(Blob.valueOf((String.isNotBlank(a.Delegacion__c) ? a.Delegacion__c.trim().toUppercase() : a.Delegacion__c+''))));
            mapAccount.put('I_PSTLZ', EncodingUtil.base64Encode(Blob.valueOf((String.isNotBlank(a.IMP_CodigoPostal__c) ? a.IMP_CodigoPostal__c.trim().toUppercase() : a.IMP_CodigoPostal__c+'')))); 
            mapAccount.put('I_REGIO',EncodingUtil.base64Encode(Blob.valueOf(a.billing_address_state__c+'')));
            mapAccount.put('I_STRAS', EncodingUtil.base64Encode(Blob.valueOf((String.isNotBlank(a.IMP_Calle__c) ? a.IMP_Calle__c.trim().toUppercase(): a.IMP_Calle__c+''))));
            mapAccount.put('I_STCD1',EncodingUtil.base64Encode(Blob.valueOf(a.RFC__c+'')));
            mapAccount.put('I_STKZN',EncodingUtil.base64Encode(Blob.valueOf(a.Tipo_de_persona__c==true?'X':'')));
            mapAccount.put('I_AKONT',EncodingUtil.base64Encode(Blob.valueOf(a.Grupo_de_Cuentas__c+'')));
            mapAccount.put('I_ZTERM',EncodingUtil.base64Encode(Blob.valueOf(a.condiciones_de_pago__c+'')));
            mapAccount.put('I_ZWELS',EncodingUtil.base64Encode(Blob.valueOf(a.ViaPago__c+'')));
            mapAccount.put('I_KTGRD', EncodingUtil.base64Encode(Blob.valueOf((!String.isBlank(a.GrupoImputacion__c) ? a.GrupoImputacion__c: ''))));
            mapAccount.put('I_FDGRV',EncodingUtil.base64Encode(Blob.valueOf(a.grupo_de_tesoreria__c+'')));
            mapAccount.put('I_VKORG',EncodingUtil.base64Encode(Blob.valueOf(a.OrganizacionVentas__c+'')));
            mapAccount.put('I_VTWEG',EncodingUtil.base64Encode(Blob.valueOf(a.clave_delcanal__c+'')));
            mapAccount.put('I_SPART',EncodingUtil.base64Encode(Blob.valueOf(a.Sector__c+'')));
            mapAccount.put('I_KDGRP',EncodingUtil.base64Encode(Blob.valueOf(a.grupo__c+'')));
            mapAccount.put('I_BZIRK',EncodingUtil.base64Encode(Blob.valueOf(a.zona_de_ventas__c+'')));
            mapAccount.put('I_KONDA',EncodingUtil.base64Encode(Blob.valueOf(a.Grupo_de_precios__c+'')));
            mapAccount.put('I_PLTYP',EncodingUtil.base64Encode(Blob.valueOf(a.ListaPrecios__c+'')));
            mapAccount.put('I_INCO1',EncodingUtil.base64Encode(Blob.valueOf(a.Intercoms_1__c+'')));
            mapAccount.put('I_INCO2',EncodingUtil.base64Encode(Blob.valueOf(a.Intercoms_2__c+'')));
            mapAccount.put('I_SMTP_ADDR',EncodingUtil.base64Encode(Blob.valueOf(a.CorreoElectronico__c+'')));
            mapAccount.put('I_TEL2',EncodingUtil.base64Encode(Blob.valueOf(mapContact.size()>0 ? String.valueOf(mapContact.get(a.Id).MobilePhone) : '')));
            mapAccount.put('I_VWERK',EncodingUtil.base64Encode(Blob.valueOf(a.centro_suministrador__c+'')));
            mapAccount.put('I_VKGRP',EncodingUtil.base64Encode(Blob.valueOf(grupoVendedor+'')));
            mapAccount.put('I_VKBUR',EncodingUtil.base64Encode(Blob.valueOf(a.centro_suministrador__c+'')));
            mapAccount.put('I_WAERS',EncodingUtil.base64Encode(Blob.valueOf(a.CurrencyIsoCode+'')));
            mapAccount.put('I_BEGRU',EncodingUtil.base64Encode(Blob.valueOf(a.RegimenFiscal__c+'')));
            mapAccount.put('I_HOUSE_NO',EncodingUtil.base64Encode(Blob.valueOf((String.isNotBlank(a.Numero_Exterior__c) ? a.Numero_Exterior__c.trim().toUppercase(): ''))));
            mapAccount.put('I_BUILDING',EncodingUtil.base64Encode(Blob.valueOf((String.isNotBlank(a.Numero_Interior__c) ? a.Numero_Interior__c.trim().toUppercase(): ''))));
            mapAccount.put('I_STKZU',EncodingUtil.base64Encode(Blob.valueOf((getImpuesto(a.clave_delcanal__c,a.centro_suministrador__c))+'')));
            //mapAccount.put('I_KTOKD',(a.Grupo_de_Cuentas__c=='121000' ? 'YB04':'YBEC'));

            System.debug('Mapa to serialize');

            System.debug(mapAccount);

        }
        jsonString = jsonString+JSON.serialize(mapAccount);
        jsonString = jsonString.replace('null', '');
        jsonString = jsonString.replace('":,', '":"",');

        // Convertir la cadena JSON a Base64
        Blob jsonBlob = Blob.valueOf(jsonString);
        String base64String = EncodingUtil.base64Encode(jsonBlob);
        return jsonString;

    }
    /*******************************************************************
    Purpose: Retorna el impuesto del cliente de acuerdo al canal de
    distribución y al centro suministrador.
    Parameters: String canal,String centroSuministrador
    Returns: String
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    public static String getImpuesto(String canal,String centroSuministrador) {
        String centroImpuesto=System.Label.IMP_Impuesto;
        map<String,String> mapCentroSuministrador = new map<String,String>();
        Schema.DescribeFieldResult fieldResult = Account.centro_suministrador__c.getDescribe();
        for( Schema.PicklistEntry f : fieldResult.getPicklistValues())
        {
            mapCentroSuministrador.put(f.getValue(),f.getLabel());
        } 
        return (canal=='07' || centroImpuesto.contains(mapCentroSuministrador.get(centroSuministrador)))?'2':'1'; 
    }
    /*******************************************************************
    Purpose: Genera el json de materiales
    Parameters: String fechaInicio, String fechaFinal
    Returns: String
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    @AuraEnabled
    public static String createMateriales(String fechaInicio, String fechaFinal) {
        String jsonString;
        List<WrapperInnerMat> lstWrapp= new List<WrapperInnerMat>();
        WrapperInnerMat wrappInner = new WrapperInnerMat();
        wrappInner.MATNR='';
        wrappInner.WERKS='';
        wrappInner.MAKTX='';
        wrappInner.KONWA='';
        wrappInner.MATKL='';
        wrappInner.KONDM='';
        wrappInner.SKU='';
        wrappInner.TAXKM='';
        wrappInner.PLTYP='';
        wrappInner.MEINS='';
        wrappInner.LVORM='';
        lstWrapp.add(wrappInner);

        WrapperMat wrappMat = new WrapperMat();
        wrappMat.I_ERSDA=fechaInicio;
        wrappMat.I_LAEDA=fechaFinal;
        wrappMat.IT_MATERIALES=lstWrapp;
        jsonString = jsonString+JSON.serialize(wrappMat);
        jsonString = jsonString.replace('null', '');
        return jsonString;
    }

    private static List<string> splitString(String accName){ 
        List<String> ArrayWords = new List<String>();
        ArrayWords = accName.split(' ');
        integer indexStringRow = 0;
        List<String> ArrayStringRow = new List<String>();
        
        for(integer a =0; a < ArrayWords.size(); a++){
            if(a == 0){
                ArrayStringRow.add(ArrayWords[a]);
            }
            else if( (ArrayStringRow[indexStringRow].length()  + ArrayWords[a].length()  + 1) <= 35)
            {
                ArrayStringRow[indexStringRow] = ArrayStringRow[indexStringRow] + ' ' + ArrayWords[a];
            }
            else {
                indexStringRow++;
                ArrayStringRow.add(ArrayWords[a]);
            }
        }
        return ArrayStringRow;
    }
    
    public class WrapperMat{
        @AuraEnabled public String I_ERSDA {get; set;}
        @auraEnabled public String I_LAEDA {get;set;}
        @auraEnabled public List<WrapperInnerMat> IT_MATERIALES {get;set;}
        
    }
    public class WrapperInnerMat{
        @AuraEnabled public String MATNR {get; set;}
        @auraEnabled public String WERKS {get;set;}
        @auraEnabled public String MAKTX {get;set;}
        @auraEnabled public String KONWA {get;set;}
        @auraEnabled public String MATKL {get;set;}
        @auraEnabled public String KONDM {get;set;}
        @auraEnabled public String SKU {get;set;}
        @auraEnabled public String TAXKM {get;set;}
        @auraEnabled public String PLTYP {get;set;}
        @auraEnabled public String MEINS {get;set;}
        @auraEnabled public String LVORM {get;set;}
    }
}