force-app/main/default/objects/Account/fields/billing_address_state__c.field-meta.xml
<CustomField>
    <fullName>billing_address_state__c</fullName>
    <label>Estado de facturación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGS</fullName>
                <label>AGUASCALIENTES</label>
            </value>
            <value>
                <fullName>BC</fullName>
                <label>BAJA CALIFORNIA</label>
            </value>
            <value>
                <fullName>BCS</fullName>
                <label>BAJA CALIFORNIA S</label>
            </value>
            <value>
                <fullName>CHI</fullName>
                <label>CHIHUAHUA</label>
            </value>
            <value>
                <fullName>CHS</fullName>
                <label>CHIAPAS</label>
            </value>
            <value>
                <fullName>CMP</fullName>
                <label>CAMPECHE</label>
            </value>
            <value>
                <fullName>CMX</fullName>
                <label>CIUDAD DE MÉXICO</label>
            </value>
            <value>
                <fullName>COA</fullName>
                <label>COAHUILA</label>
            </value>
            <value>
                <fullName>COL</fullName>
                <label>COLIMA</label>
            </value>
            <value>
                <fullName>DGO</fullName>
                <label>DURANGO</label>
            </value>
            <value>
                <fullName>GRO</fullName>
                <label>GUERRERO</label>
            </value>
            <value>
                <fullName>GTO</fullName>
                <label>GUANAJUATO</label>
            </value>
            <value>
                <fullName>HGO</fullName>
                <label>HIDALGO</label>
            </value>
            <value>
                <fullName>JAL</fullName>
                <label>JALISCO</label>
            </value>
            <value>
                <fullName>MCH</fullName>
                <label>MICHOACÁN</label>
            </value>
            <value>
                <fullName>MEX</fullName>
                <label>ESTADO DE MÉXICO</label>
            </value>
            <value>
                <fullName>MOR</fullName>
                <label>MORELOS</label>
            </value>
            <value>
                <fullName>NAY</fullName>
                <label>NAYARIT</label>
            </value>
            <value>
                <fullName>NL</fullName>
                <label>NUEVO LEÓN</label>
            </value>
            <value>
                <fullName>OAX</fullName>
                <label>OAXACA</label>
            </value>
            <value>
                <fullName>PUE</fullName>
                <label>PUEBLA</label>
            </value>
            <value>
                <fullName>QR</fullName>
                <label>QUINTANA ROO</label>
            </value>
            <value>
                <fullName>QRO</fullName>
                <label>QUERÉTARO</label>
            </value>
            <value>
                <fullName>SIN</fullName>
                <label>SINALOA</label>
            </value>
            <value>
                <fullName>SLP</fullName>
                <label>SAN LUIS POTOSÍ</label>
            </value>
            <value>
                <fullName>SON</fullName>
                <label>SONORA</label>
            </value>
            <value>
                <fullName>TAB</fullName>
                <label>TABASCO</label>
            </value>
            <value>
                <fullName>TLX</fullName>
                <label>TLAXCALA</label>
            </value>
            <value>
                <fullName>TMS</fullName>
                <label>TAMAULIPAS</label>
            </value>
            <value>
                <fullName>VER</fullName>
                <label>VERACRUZ</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Colonia__c.field-meta.xml
<CustomField>
    <fullName>Colonia__c</fullName>
    <label>Colonia</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/condiciones_de_pago__c.field-meta.xml
<CustomField>
    <fullName>condiciones_de_pago__c</fullName>
    <defaultValue>&quot;NT00&quot;</defaultValue>
    <label>Condiciones de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NT00</fullName>
                <label>Pagado a la recepcion</label>
            </value>
            <value>
                <fullName>NT08</fullName>
                <label>Vencimiento 08 dias</label>
            </value>
            <value>
                <fullName>NT15</fullName>
                <label>Vencimiento 15 dias</label>
            </value>
            <value>
                <fullName>NT20</fullName>
                <label>Vencimiento 20 dias</label>
            </value>
            <value>
                <fullName>NT30</fullName>
                <label>Vencimiento 30 dias</label>
            </value>
            <value>
                <fullName>NT45</fullName>
                <label>Vencimiento 45 dias</label>
            </value>
            <value>
                <fullName>NT60</fullName>
                <label>Vencimiento 60 dias</label>
            </value>
            <value>
                <fullName>NT90</fullName>
                <label>Vencimiento 90 dias</label>
            </value>
            <value>
                <fullName>NT120</fullName>
                <label>Vencimiento 120 dias</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <label>Delegación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_Calle__c.field-meta.xml
<CustomField>
    <fullName>IMP_Calle__c</fullName>
    <description>Calle del cliente</description>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_CodigoPostal__c.field-meta.xml
<CustomField>
    <fullName>IMP_CodigoPostal__c</fullName>
    <description>Código postal de la dirección del cliente</description>
    <label>Código postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_PaisFacturacion__c.field-meta.xml
<CustomField>
    <fullName>IMP_PaisFacturacion__c</fullName>
    <defaultValue>&quot;MX&quot;</defaultValue>
    <description>Este campo servirá para enviar el código de País en la integración de SAP -SF</description>
    <label>País de Facturación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MX</fullName>
                <label>MÉXICO</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>COLOMBIA</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>COSTA RICA</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>ESTADOS UNIDOS</label>
            </value>
            <value>
                <fullName>GT</fullName>
                <label>GUATEMALA</label>
            </value>
            <value>
                <fullName>SV</fullName>
                <label>EL SALVADOR</label>
            </value>
            <value>
                <fullName>DO</fullName>
                <label>REP. DOMINICANA</label>
            </value>
            <value>
                <fullName>NI</fullName>
                <label>NICARAGUA</label>
            </value>
            <value>
                <fullName>HN</fullName>
                <label>HONDURAS</label>
            </value>
            <value>
                <fullName>PR</fullName>
                <label>PUERTO RICO</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>ESPAÑA</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>BRASIL</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>CANADÁ</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Intercoms_1__c.field-meta.xml
<CustomField>
    <fullName>Intercoms_1__c</fullName>
    <defaultValue>&quot;FOB&quot;</defaultValue>
    <label>Intercoms 1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Intercoms_2__c.field-meta.xml
<CustomField>
    <fullName>Intercoms_2__c</fullName>
    <defaultValue>&quot;FRANCO A BORDO&quot;</defaultValue>
    <label>Intercoms 2</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_Exterior__c.field-meta.xml
<CustomField>
    <fullName>Numero_Exterior__c</fullName>
    <description>Número exterior de la cuenta</description>
    <label>Número Exterior</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_Interior__c.field-meta.xml
<CustomField>
    <fullName>Numero_Interior__c</fullName>
    <description>Contiene el número interior de la cuenta</description>
    <label>Número Interior</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/pedido__c.field-meta.xml
<CustomField>
    <fullName>pedido__c</fullName>
    <description>Número de pedido en SAP</description>
    <externalId>true</externalId>
    <label>ID Pedido SAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/TotalPartidas__c.field-meta.xml
<CustomField>
    <fullName>TotalPartidas__c</fullName>
    <label>Total</label>
    <summarizedField>OrderItem.UnitPrice</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/TotalPedido__c.field-meta.xml
<CustomField>
    <fullName>TotalPedido__c</fullName>
    <description>Almacena el total del pedido</description>
    <label>Total de Pedido</label>
    <summarizedField>OrderItem.PrecioTotal__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DescuentoManual__c.field-meta.xml
<CustomField>
    <fullName>DescuentoManual__c</fullName>
    <description>Campo usado para almacenar el descuento total.</description>
    <label>Descuento Manual</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>DescuentoSAP__c</fullName>
    <description>Campo usado para capturar el descuento de SAP</description>
    <label>Descuento SAP</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IMP_Posicion__c.field-meta.xml
<CustomField>
    <fullName>IMP_Posicion__c</fullName>
    <description>Almacena el valor de la posición que se envia a SAP</description>
    <label>Posición</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PrecioTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotal__c</fullName>
    <description>Precio total del producto de pedido y el descuento aplicado</description>
    <formula>((1- DescuentoSAP__c )*(UnitPrice * Quantity )  * (1-IMP_DescuentoPromo__c))   *(1- DescuentoManual__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Peso__c.field-meta.xml
<CustomField>
    <fullName>Peso__c</fullName>
    <label>Peso</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>DescuentoSAP__c</fullName>
    <label>Descuento SAP</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IMP_DescuentoPromo__c.field-meta.xml
<CustomField>
    <fullName>IMP_DescuentoPromo__c</fullName>
    <description>Descuento de promoción de acuerdo a criterios de descuentos promocionales de SAP</description>
    <label>Descuento promoción</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Peso_bruto__c.field-meta.xml
<CustomField>
    <fullName>Peso_bruto__c</fullName>
    <formula>Quantity * Product2.Peso__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Peso bruto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_PedidoPDF_CC.cls
/************************************************************************
Name: IMP_PedidoPDF_CC
Copyright © 2023 Salesforce
========================================================================
Purpose:
Class to get information related to the order and show it in the PDF.
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      rortega@ts4.mx    28/03/2023     INITIAL        DEV CSR:
************************************************************************/
public class IMP_PedidoPDF_CC {

    public String getOrder() {
        return null;
    }


    public String pedido { get; set; }
    /******************************************************************* 
    Purpose: Declaration of variables to get the information.
    ********************************************************************/
    @auraEnabled public String orderId {get;set;}
    @auraEnabled public Order datosOrder {get;set;}
    @auraEnabled public Account cuenta {get; set;}
    @auraEnabled public Date fechaDocumento {get; set;}
    @auraEnabled public String direccionCompleta {get; set;}
    @auraEnabled public Decimal resultadoPesos {get; set;}
    @auraEnabled public Decimal IVA {get; set;}
    @auraEnabled public Decimal subtotal {get; set;}
    @auraEnabled public Decimal impuestos {get; set;}
    @auraEnabled public Decimal totalFinal {get; set;}
    @auraEnabled public AggregateResult pesosProductos {get; set;}
    @auraEnabled public List<OrderItemCalc> productsOrder {get; set;}
    /******************************************************************* 
    Purpose: Get the information.
    ********************************************************************/
    public IMP_PedidoPDF_CC() {   
        orderId= ApexPages.currentPage().getParameters().get('id');
        try{
            
            datosOrder = [SELECT Id, AccountId, OrderNumber,pedido__c
                            , createdDate, Precio_Total__c
                            , TotalAmount, TotalPartidas__c
                            , TotalPedido__c, Pricebook2.Sucursal__c
                            , condiciones_de_pago__c, CurrencyIsoCode
                        FROM Order WHERE Id =: orderId];

                        
           subtotal = datosOrder.TotalPedido__c.setScale(2);
           
          

            if(datosOrder.Pricebook2.Sucursal__c == 'TJ01'){
                IVA = 8.00;
            }else{
                IVA =16.00;
                
            }

            impuestos =  (datosOrder.TotalPedido__c * IVA / 100);
            totalFinal = (datosOrder.TotalPedido__c + impuestos).setScale(2);

            fechaDocumento = Date.valueOf(datosOrder.CreatedDate.addDays(2));

            cuenta = [SELECT Id, Name, AccountNumber, Phone, Fax
                      , CorreoElectronico__c , SHIPPINGCITY, id_de_sap__c
                      , Intercoms_1__c, Intercoms_2__c , IMP_Calle__c
                      , Numero_Interior__c, Numero_Exterior__c, Colonia__c
                      , Delegacion__c , IMP_CodigoPostal__c, ShippingStreet, ShippingPostalCode
                      , billing_address_state__c, IMP_PaisFacturacion__c, ShippingCountry
                      FROM Account
                      Where Id =: datosOrder.AccountId];

            direccionCompleta = '';
            if(String.isNotBlank(cuenta.IMP_Calle__c)){
                direccionCompleta += 'CALLE ' + cuenta.IMP_Calle__c;
            }
            else {
                direccionCompleta += (String.isNotBlank(cuenta.ShippingStreet ) ? (' ' + cuenta.ShippingStreet) : '');
            }
            
            direccionCompleta += (String.isNotBlank(cuenta.Numero_Exterior__c ) ? (' Núm. ext. ' + cuenta.Numero_Exterior__c) : '');
            direccionCompleta += (String.isNotBlank(cuenta.Numero_Interior__c ) ? (' Núm. int. ' + cuenta.Numero_Interior__c) : '');
            direccionCompleta += (String.isNotBlank(cuenta.Colonia__c ) ? (' COL. ' + cuenta.Colonia__c) : '');
            direccionCompleta += (String.isNotBlank(cuenta.Delegacion__c ) ? (' DEL. ' + cuenta.Delegacion__c) : '');
            
            if(String.isNotBlank(cuenta.IMP_CodigoPostal__c)){
                direccionCompleta += ' CP. ' + cuenta.IMP_CodigoPostal__c;
            }
            else {
                direccionCompleta += (String.isNotBlank(cuenta.ShippingPostalCode ) ? (' CP. ' + cuenta.ShippingPostalCode) : '');
            }
            
            if(String.isNotBlank(getPLVLabel(Account.billing_address_state__c, cuenta.billing_address_state__c))){
                direccionCompleta += ' ' + getPLVLabel(Account.billing_address_state__c, cuenta.billing_address_state__c); //picklist
            }
            else {
                direccionCompleta += (String.isNotBlank(cuenta.ShippingCity ) ? (' ' + cuenta.ShippingCity) : '');
            }

            if(String.isNotBlank(cuenta.ShippingCountry)){
                direccionCompleta += ' ' + cuenta.ShippingCountry;
            }
            else {
                direccionCompleta += (String.isNotBlank(getPLVLabel(Account.IMP_PaisFacturacion__c, cuenta.IMP_PaisFacturacion__c)) ? (' ' + cuenta.IMP_PaisFacturacion__c) : '' );  //picklist
            }

            direccionCompleta = direccionCompleta.toUpperCase();
            
            List<OrderItemCalc> ListProductsOrder = new List<OrderItemCalc>();

            for(OrderItem pOrder : [SELECT Id, IMP_Posicion__c, Product2.Name, Product2.ProductCode
            ,  Quantity, Product2.Description, ListPrice
            , UnitPrice,TotalPrice, DescuentoSAP__c, DescuentoManual__c, IMP_DescuentoPromo__c, QuoteLineItem.Peso_bruto__c
            , Product2.Peso__c
            , PrecioTotal__c
            , ServiceDate, EndDate
           
            FROM OrderItem  WHERE OrderId =: orderId]){
                OrderItemCalc orderItemElement = new OrderItemCalc();

                //orderItemElement.Posicion = pOrder.IMP_Posicion__c;
                orderItemElement.Name = pOrder.Product2.Name;
                orderItemElement.ProductoCode = pOrder.Product2.ProductCode;
                orderItemElement.Quantity = pOrder.Quantity;
                orderItemElement.Description = pOrder.Product2.Description;
                orderItemElement.ListPricee = pOrder.ListPrice;
                orderItemElement.PrecioUnit = pOrder.UnitPrice;

                orderItemElement.TotalPrecio = pOrder.UnitPrice * pOrder.Quantity;
                orderItemElement.DescuentoSAP = pOrder.DescuentoSAP__c != null ? pOrder.DescuentoSAP__c: 0.00; 
                orderItemElement.DescuentoManual = pOrder.DescuentoManual__c != null ? pOrder.DescuentoManual__c: 0.00;
                orderItemElement.DescuentoPromo = pOrder.IMP_DescuentoPromo__c != null ? pOrder.IMP_DescuentoPromo__c: 0.00;
               orderItemElement.Peso = pOrder.Product2.Peso__c ;
               orderItemElement.Peso = pOrder.QuoteLineItem.Peso_bruto__c; 
                orderItemElement.PrecioTotal= pOrder.PrecioTotal__c;
                orderItemElement.ServiceDate = pOrder.ServiceDate;
                orderItemElement.EndDate = pOrder.EndDate;
                
                orderItemElement.promoDescManual = 0;   
                orderItemElement.promoDescAuto = 0;
                orderItemElement.valorNetoItem = 0;
                
                if(pOrder.DescuentoManual__c != NULL && pOrder.DescuentoManual__c != 0){
                    orderItemElement.promoDescManual = ((pOrder.UnitPrice / 100 ) * pOrder.DescuentoManual__c)* pOrder.Quantity;
                }
                else 
                {
                    orderItemElement.promoDescManual = 0.00;
                }
                

                if(pOrder.DescuentoSAP__c != NULL && pOrder.DescuentoSAP__c != 0){
                    orderItemElement.promoDescAuto = ((pOrder.UnitPrice * pOrder.DescuentoSAP__c) / 100)* pOrder.Quantity;    
                }
                else 
                {
                    orderItemElement.promoDescAuto = 0.00;
                }

                if(pOrder.IMP_DescuentoPromo__c != NULL && pOrder.IMP_DescuentoPromo__c != 0){
                    orderItemElement.promoDesc = ((pOrder.UnitPrice * pOrder.IMP_DescuentoPromo__c) / 100)* pOrder.Quantity;    
                }
                else 
                {
                    orderItemElement.promoDesc = 0.00;
                }

                Decimal TotalDesct =  pOrder.UnitPrice;

                orderItemElement.valorNetoItem = TotalDesct;

                if(pOrder.DescuentoSAP__c != NULL && pOrder.DescuentoSAP__c != 0){
                    TotalDesct = TotalDesct -((TotalDesct / 100) * (pOrder.DescuentoSAP__c));
                    orderItemElement.valorNetoItem = TotalDesct;
                    
                    System.debug('Entra ambos descuentos ' + pOrder.Product2.ProductCode + ' valorNetoItem: ' + orderItemElement.valorNetoItem);
                } 
                
                if( pOrder.DescuentoManual__c != NULL && pOrder.DescuentoManual__c != 0){
                    TotalDesct = TotalDesct -((TotalDesct / 100) * (pOrder.DescuentoManual__c));
                    orderItemElement.valorNetoItem = TotalDesct;
                }

                if( pOrder.IMP_DescuentoPromo__c != NULL && pOrder.IMP_DescuentoPromo__c != 0){
                    TotalDesct = TotalDesct -((TotalDesct / 100) * (pOrder.IMP_DescuentoPromo__c));
                    orderItemElement.valorNetoItem = TotalDesct;
                }
                //TotalDesct

                ListProductsOrder.add(orderItemElement);

            }

            productsOrder = ListProductsOrder;

            pesosProductos = [SELECT SUM(Peso_bruto__c)totalPesos FROM OrderItem WHERE OrderId =: orderId];
            resultadoPesos = (decimal)pesosProductos.get('totalPesos');
            
        }catch(Exception exc){
            system.debug('Exception PDF '+exc.getMessage()+ exc.getCause()+exc.getLineNumber());
        }
    }

    public class OrderItemCalc
    {
        public Decimal Posicion {get; set;}
        public string Name {get; set;}
        public string ProductoCode {get; set;}
        public Decimal Quantity {get; set;}
        public string Description {get; set;}
        public Decimal ListPricee {get; set;}
        public Decimal PrecioUnit {get; set;}
        public Decimal TotalPrecio {get; set;}
        public Decimal DescuentoSAP {get; set;}
        public Decimal DescuentoManual {get; set;}
        public Decimal DescuentoPromo {get; set;}
        public Decimal Peso {get; set;}
        public Decimal PrecioTotal {get; set;}
        public date ServiceDate {get; set;}
        public date EndDate {get; set;}
        public Decimal promoDescManual {get; set;}
        public Decimal promoDescAuto {get; set;}//Descuento SAP
        public Decimal promoDesc {get; set;}//Descuento Promocion 
        public Decimal valorNetoItem {get; set;}
    }

    
    public String getPLVLabel(SObjectField fld, String val) {

        Schema.DescribeFieldResult dfr = fld.getDescribe();
        List<Schema.PicklistEntry> plvs = dfr.getPicklistValues();
        
        for (PicklistEntry ple: plvs) {
            if (ple.getValue() == val) {return ple.getLabel();}
        }
        return null;
    }
    
}