force-app/main/default/objects/Account/fields/billing_address_state__c.field-meta.xml
<CustomField>
    <fullName>billing_address_state__c</fullName>
    <label>Estado de facturación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGS</fullName>
                <label>AGUASCALIENTES</label>
            </value>
            <value>
                <fullName>BC</fullName>
                <label>BAJA CALIFORNIA</label>
            </value>
            <value>
                <fullName>BCS</fullName>
                <label>BAJA CALIFORNIA S</label>
            </value>
            <value>
                <fullName>CHI</fullName>
                <label>CHIHUAHUA</label>
            </value>
            <value>
                <fullName>CHS</fullName>
                <label>CHIAPAS</label>
            </value>
            <value>
                <fullName>CMP</fullName>
                <label>CAMPECHE</label>
            </value>
            <value>
                <fullName>CMX</fullName>
                <label>CIUDAD DE MÉXICO</label>
            </value>
            <value>
                <fullName>COA</fullName>
                <label>COAHUILA</label>
            </value>
            <value>
                <fullName>COL</fullName>
                <label>COLIMA</label>
            </value>
            <value>
                <fullName>DGO</fullName>
                <label>DURANGO</label>
            </value>
            <value>
                <fullName>GRO</fullName>
                <label>GUERRERO</label>
            </value>
            <value>
                <fullName>GTO</fullName>
                <label>GUANAJUATO</label>
            </value>
            <value>
                <fullName>HGO</fullName>
                <label>HIDALGO</label>
            </value>
            <value>
                <fullName>JAL</fullName>
                <label>JALISCO</label>
            </value>
            <value>
                <fullName>MCH</fullName>
                <label>MICHOACÁN</label>
            </value>
            <value>
                <fullName>MEX</fullName>
                <label>ESTADO DE MÉXICO</label>
            </value>
            <value>
                <fullName>MOR</fullName>
                <label>MORELOS</label>
            </value>
            <value>
                <fullName>NAY</fullName>
                <label>NAYARIT</label>
            </value>
            <value>
                <fullName>NL</fullName>
                <label>NUEVO LEÓN</label>
            </value>
            <value>
                <fullName>OAX</fullName>
                <label>OAXACA</label>
            </value>
            <value>
                <fullName>PUE</fullName>
                <label>PUEBLA</label>
            </value>
            <value>
                <fullName>QR</fullName>
                <label>QUINTANA ROO</label>
            </value>
            <value>
                <fullName>QRO</fullName>
                <label>QUERÉTARO</label>
            </value>
            <value>
                <fullName>SIN</fullName>
                <label>SINALOA</label>
            </value>
            <value>
                <fullName>SLP</fullName>
                <label>SAN LUIS POTOSÍ</label>
            </value>
            <value>
                <fullName>SON</fullName>
                <label>SONORA</label>
            </value>
            <value>
                <fullName>TAB</fullName>
                <label>TABASCO</label>
            </value>
            <value>
                <fullName>TLX</fullName>
                <label>TLAXCALA</label>
            </value>
            <value>
                <fullName>TMS</fullName>
                <label>TAMAULIPAS</label>
            </value>
            <value>
                <fullName>VER</fullName>
                <label>VERACRUZ</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Colonia__c.field-meta.xml
<CustomField>
    <fullName>Colonia__c</fullName>
    <label>Colonia</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/condiciones_de_pago__c.field-meta.xml
<CustomField>
    <fullName>condiciones_de_pago__c</fullName>
    <defaultValue>&quot;NT00&quot;</defaultValue>
    <label>Condiciones de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NT00</fullName>
                <label>Pagado a la recepcion</label>
            </value>
            <value>
                <fullName>NT08</fullName>
                <label>Vencimiento 08 dias</label>
            </value>
            <value>
                <fullName>NT15</fullName>
                <label>Vencimiento 15 dias</label>
            </value>
            <value>
                <fullName>NT20</fullName>
                <label>Vencimiento 20 dias</label>
            </value>
            <value>
                <fullName>NT30</fullName>
                <label>Vencimiento 30 dias</label>
            </value>
            <value>
                <fullName>NT45</fullName>
                <label>Vencimiento 45 dias</label>
            </value>
            <value>
                <fullName>NT60</fullName>
                <label>Vencimiento 60 dias</label>
            </value>
            <value>
                <fullName>NT90</fullName>
                <label>Vencimiento 90 dias</label>
            </value>
            <value>
                <fullName>NT120</fullName>
                <label>Vencimiento 120 dias</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <label>Delegación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_Calle__c.field-meta.xml
<CustomField>
    <fullName>IMP_Calle__c</fullName>
    <description>Calle del cliente</description>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_CodigoPostal__c.field-meta.xml
<CustomField>
    <fullName>IMP_CodigoPostal__c</fullName>
    <description>Código postal de la dirección del cliente</description>
    <label>Código postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_PaisFacturacion__c.field-meta.xml
<CustomField>
    <fullName>IMP_PaisFacturacion__c</fullName>
    <defaultValue>&quot;MX&quot;</defaultValue>
    <description>Este campo servirá para enviar el código de País en la integración de SAP -SF</description>
    <label>País de Facturación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MX</fullName>
                <label>MÉXICO</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>COLOMBIA</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>COSTA RICA</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>ESTADOS UNIDOS</label>
            </value>
            <value>
                <fullName>GT</fullName>
                <label>GUATEMALA</label>
            </value>
            <value>
                <fullName>SV</fullName>
                <label>EL SALVADOR</label>
            </value>
            <value>
                <fullName>DO</fullName>
                <label>REP. DOMINICANA</label>
            </value>
            <value>
                <fullName>NI</fullName>
                <label>NICARAGUA</label>
            </value>
            <value>
                <fullName>HN</fullName>
                <label>HONDURAS</label>
            </value>
            <value>
                <fullName>PR</fullName>
                <label>PUERTO RICO</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>ESPAÑA</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>BRASIL</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>CANADÁ</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Intercoms_1__c.field-meta.xml
<CustomField>
    <fullName>Intercoms_1__c</fullName>
    <defaultValue>&quot;FOB&quot;</defaultValue>
    <label>Intercoms 1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Intercoms_2__c.field-meta.xml
<CustomField>
    <fullName>Intercoms_2__c</fullName>
    <defaultValue>&quot;FRANCO A BORDO&quot;</defaultValue>
    <label>Intercoms 2</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_Exterior__c.field-meta.xml
<CustomField>
    <fullName>Numero_Exterior__c</fullName>
    <description>Número exterior de la cuenta</description>
    <label>Número Exterior</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_Interior__c.field-meta.xml
<CustomField>
    <fullName>Numero_Interior__c</fullName>
    <description>Contiene el número interior de la cuenta</description>
    <label>Número Interior</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Peso__c.field-meta.xml
<CustomField>
    <fullName>Peso__c</fullName>
    <label>Peso</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/condiciones_de_pago__c.field-meta.xml
<CustomField>
    <fullName>condiciones_de_pago__c</fullName>
    <label>Condiciones de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CondicionesPago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Fecha_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_entrega__c</fullName>
    <label>Fecha de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PrecioTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotal__c</fullName>
    <label>Precio Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TotalPartidas__c.field-meta.xml
<CustomField>
    <fullName>TotalPartidas__c</fullName>
    <label>Total</label>
    <summarizedField>QuoteLineItem.PrecioTotalConDescuentos__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Descuento_adicional__c.field-meta.xml
<CustomField>
    <fullName>Descuento_adicional__c</fullName>
    <description>Este descuento se ingresa de forma manual</description>
    <label>Descuento adicional</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>DescuentoSAP__c</fullName>
    <label>Descuento SAP</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IMP_DescuentoPromo__c.field-meta.xml
<CustomField>
    <fullName>IMP_DescuentoPromo__c</fullName>
    <description>Descuento de promoción de acuerdo a criterios de descuentos promocionales de SAP</description>
    <label>Descuento promoción</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Peso_bruto__c.field-meta.xml
<CustomField>
    <fullName>Peso_bruto__c</fullName>
    <formula>Quantity * Product2.Peso__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Peso bruto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrecioTotalConDescuentos__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotalConDescuentos__c</fullName>
    <label>Precio Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CondicionesPago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NT00</fullName>
        <default>true</default>
        <label>Pagado a la recepcion</label>
    </customValue>
    <customValue>
        <fullName>NT08</fullName>
        <label>Vencimiento 08 dias</label>
    </customValue>
    <customValue>
        <fullName>NT15</fullName>
        <label>Vencimiento 15 dias</label>
    </customValue>
    <customValue>
        <fullName>NT20</fullName>
        <label>Vencimiento 20 dias</label>
    </customValue>
    <customValue>
        <fullName>NT30</fullName>
        <label>Vencimiento 30 dias</label>
    </customValue>
    <customValue>
        <fullName>NT45</fullName>
        <label>Vencimiento 45 dias</label>
    </customValue>
    <customValue>
        <fullName>NT60</fullName>
        <label>Vencimiento 60 dias</label>
    </customValue>
    <customValue>
        <fullName>NT90</fullName>
        <label>Vencimiento 90 dias</label>
    </customValue>
    <customValue>
        <fullName>NT120</fullName>
        <label>Vencimiento 120 dias</label>
    </customValue>
    <masterLabel>Condiciones de Pago</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_CotizacionPDF_CC.cls
/************************************************************************
Name: IMP_CotizacionPDF_CC
Copyright © 2022 Salesforce
========================================================================
Purpose:
Class to get information related to the quote and show it in the PDF.
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      mmauro@ts4.mx    17/01/2021     INITIAL        DEV CSR:
************************************************************************/
public with sharing class IMP_CotizacionPDF_CC {

    public String partidadepresupuesto { get; set; }
    /******************************************************************* 
    Purpose: Declaration of variables to get the information.
    ********************************************************************/
    @auraEnabled public String cotizacionId {get;set;}
    @auraEnabled public Quote datosCotizacion {get;set;}
    @auraEnabled public Account cuenta {get; set;}
    @auraEnabled public Date fechaFinValidez {get; set;}
    @auraEnabled public Date fechaEntrega {get; set;}
    @auraEnabled public String direccionCompleta {get; set;}
    @auraEnabled public Decimal resultadoPesos {get; set;}
    @auraEnabled public Decimal IVA {get; set;}
    @auraEnabled public Decimal subtotal {get; set;}
    @auraEnabled public Decimal impuestos {get; set;}
    @auraEnabled public Decimal totalFinal {get; set;}
    @auraEnabled public AggregateResult pesosProductos {get; set;}
    @auraEnabled public List<QuoteLineItem> productsQuote {get; set;}
    /******************************************************************* 
    Purpose: Get the information.
    ********************************************************************/
    public IMP_CotizacionPDF_CC() {   
        cotizacionId= ApexPages.currentPage().getParameters().get('id');
        try{
            datosCotizacion = [SELECT Id, AccountId, QuoteNumber, createdDate, Subtotal,Tax, condiciones_de_pago__c,
                               CurrencyIsoCode,TotalPrice,TotalPartidas__c,PrecioTotal__c,Pricebook2.Sucursal__c, ExpirationDate, Fecha_de_entrega__c
                               FROM Quote 
                               WHERE Id =: cotizacionId];
            subtotal = datosCotizacion.TotalPartidas__c.setScale(2);
            impuestos = datosCotizacion.Tax.setScale(2);
            totalFinal = datosCotizacion.PrecioTotal__c.setScale(2);
            if(datosCotizacion.Pricebook2.Sucursal__c == 'TJ01'){
                IVA = 8.00;
            }else{
                IVA =16.00;
                
            }

            fechaFinValidez = Date.valueOf(datosCotizacion.CreatedDate.addMonths(1));
            fechaEntrega = Date.valueOf(datosCotizacion.CreatedDate.addDays(2));
            cuenta = [SELECT Id, Name, AccountNumber, Phone, Fax, CorreoElectronico__c, SHIPPINGCITY, id_de_sap__c,
                      SHIPPINGCOUNTRY, SHIPPINGPOSTALCODE, billing_address_state__c, SHIPPINGSTREET,Intercoms_1__c, Intercoms_2__c 
                      , IMP_Calle__c, IMP_CodigoPostal__c, Numero_Exterior__c, Numero_Interior__c, COLONIA__C, Delegacion__c, IMP_PaisFacturacion__c
                      FROM Account
                      Where Id =: datosCotizacion.AccountId];
            
            direccionCompleta = '';
            if(String.isNotBlank(cuenta.IMP_Calle__c)){
                direccionCompleta = 'CALLE ' + cuenta.IMP_Calle__c;
            }
            else {
                direccionCompleta = (String.isNotBlank(cuenta.ShippingStreet ) ? (' ' + cuenta.ShippingStreet) : '');
            }
            
            direccionCompleta += (String.isNotBlank(cuenta.Numero_Exterior__c ) ? (' Núm. ext. ' + cuenta.Numero_Exterior__c) : '');
            direccionCompleta += (String.isNotBlank(cuenta.Numero_Interior__c ) ? (' Núm. int. ' + cuenta.Numero_Interior__c) : '');
            direccionCompleta += (String.isNotBlank(cuenta.Colonia__c ) ? (' COL. ' + cuenta.Colonia__c) : '');
            direccionCompleta += (String.isNotBlank(cuenta.Delegacion__c ) ? (' DEL. ' + cuenta.Delegacion__c) : '');

            if(String.isNotBlank(cuenta.IMP_CodigoPostal__c)){
                direccionCompleta += ' CP. ' + cuenta.IMP_CodigoPostal__c;
            }
            else {
                direccionCompleta += (String.isNotBlank(cuenta.ShippingPostalCode ) ? (' CP. ' + cuenta.ShippingPostalCode) : '');
            }

            if(String.isNotBlank(getPLVLabel(Account.billing_address_state__c, cuenta.billing_address_state__c))){
                direccionCompleta += ' ' + getPLVLabel(Account.billing_address_state__c, cuenta.billing_address_state__c); //picklist
            }
            else {
                direccionCompleta += (String.isNotBlank(cuenta.ShippingCity ) ? (' ' + cuenta.ShippingCity) : '');
            }

            if(String.isNotBlank(cuenta.ShippingCountry)){
                direccionCompleta += ' ' + cuenta.ShippingCountry;
            }
            else {
                direccionCompleta += (String.isNotBlank(getPLVLabel(Account.IMP_PaisFacturacion__c, cuenta.IMP_PaisFacturacion__c)) ? (' ' + cuenta.IMP_PaisFacturacion__c) : '' );  //picklist
            }

            direccionCompleta = direccionCompleta.toUpperCase();
            
            
            productsQuote = [SELECT Id, Product2.Name, Product2.ProductCode,  Quantity, Product2.Description, ListPrice, UnitPrice, TotalPrice, Peso_bruto__c,
                             IMP_DescuentoPromo__c, Descuento_adicional__c, DescuentoSAP__c, Product2.Peso__c,PrecioTotalConDescuentos__c
                             FROM QuoteLineItem 
                             WHERE QuoteId =: cotizacionId];


            pesosProductos = [SELECT SUM(Peso_bruto__c)totalPesos FROM QuoteLineItem WHERE QuoteId =: cotizacionId];
            resultadoPesos = (decimal)pesosProductos.get('totalPesos');
            
        }catch(Exception exc){
            system.debug('Exception PDF '+exc.getMessage()+ exc.getCause()+exc.getLineNumber());
        }
    }

    public String getPLVLabel(SObjectField fld, String val) {

        Schema.DescribeFieldResult dfr = fld.getDescribe();
        List<Schema.PicklistEntry> plvs = dfr.getPicklistValues();
        
        for (PicklistEntry ple: plvs) {
            if (ple.getValue() == val) {return ple.getLabel();}
        }
        return null;
    }
}