force-app/main/default/objects/Account/fields/centro_suministrador__c.field-meta.xml
<CustomField>
    <fullName>centro_suministrador__c</fullName>
    <label>Centro Suministrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC01</fullName>
                <label>Acapulco</label>
            </value>
            <value>
                <fullName>CA01</fullName>
                <label>Cancún</label>
            </value>
            <value>
                <fullName>CH01</fullName>
                <label>Chihuahua</label>
            </value>
            <value>
                <fullName>CU01</fullName>
                <label>Culiacán</label>
            </value>
            <value>
                <fullName>CV01</fullName>
                <label>Cuernavaca</label>
            </value>
            <value>
                <fullName>ERMI</fullName>
                <label>Ermita</label>
            </value>
            <value>
                <fullName>GD01</fullName>
                <label>Guadalajara</label>
            </value>
            <value>
                <fullName>HE01</fullName>
                <label>Hermosillo</label>
            </value>
            <value>
                <fullName>IMPQ</fullName>
                <label>Imperquimia</label>
            </value>
            <value>
                <fullName>IMPV</fullName>
                <label>Imperquimia Ventas</label>
            </value>
            <value>
                <fullName>LE01</fullName>
                <label>León</label>
            </value>
            <value>
                <fullName>ME01</fullName>
                <label>Mérida</label>
            </value>
            <value>
                <fullName>ME02</fullName>
                <label>Mérida II</label>
            </value>
            <value>
                <fullName>MIXC</fullName>
                <label>Mixcoac</label>
            </value>
            <value>
                <fullName>MT01</fullName>
                <label>Monterrey</label>
            </value>
            <value>
                <fullName>PSUR</fullName>
                <label>Perisur</label>
            </value>
            <value>
                <fullName>QE01</fullName>
                <label>Querétaro</label>
            </value>
            <value>
                <fullName>RAZA</fullName>
                <label>La Raza</label>
            </value>
            <value>
                <fullName>RIVI</fullName>
                <label>Riviera</label>
            </value>
            <value>
                <fullName>SATE</fullName>
                <label>Satélite</label>
            </value>
            <value>
                <fullName>TJ01</fullName>
                <label>Tijuana</label>
            </value>
            <value>
                <fullName>VE01</fullName>
                <label>Veracruz</label>
            </value>
            <value>
                <fullName>VI01</fullName>
                <label>Villahermosa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Condicion_de_expedicion__c.field-meta.xml
<CustomField>
    <fullName>Condicion_de_expedicion__c</fullName>
    <label>Condicion de expedicion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <default>true</default>
                <label>Estándar</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Recogida</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Inmediatamente</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Servicios de Transpo</label>
            </value>
            <value>
                <fullName>RE</fullName>
                <label>Devoluciones</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Esquema_cliente__c.field-meta.xml
<CustomField>
    <fullName>Esquema_cliente__c</fullName>
    <label>Esquema cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Estandar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/grupo__c.field-meta.xml
<CustomField>
    <fullName>grupo__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Distribuidor A</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Distribuidor B</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Distribuidor C</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidor D</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Contratistas A</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Contratistas B</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Contratistas C</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Multimarcas A</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Multimarcas B</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Multimarcas C</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Desarrollo de Negoci</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Aplicador A</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Contratistas Plus</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_de_Cuentas__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Cuentas__c</fullName>
    <label>Grupo de Cuentas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>121000</fullName>
                <default>true</default>
                <label>Clientes Nacionales</label>
            </value>
            <value>
                <fullName>121001</fullName>
                <label>Clientes Extranjeros</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_de_precios__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_precios__c</fullName>
    <label>Grupo de precios</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Gran consumidor</label>
            </value>
            <value>
                <fullName>02</fullName>
                <default>true</default>
                <label>Comprador ocasional</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/grupo_de_tesoreria__c.field-meta.xml
<CustomField>
    <fullName>grupo_de_tesoreria__c</fullName>
    <label>Grupo de tesorería</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y01</fullName>
                <default>true</default>
                <label>C-Nacional</label>
            </value>
            <value>
                <fullName>Y02</fullName>
                <label>C-Exporta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ListaPrecios__c.field-meta.xml
<CustomField>
    <fullName>ListaPrecios__c</fullName>
    <label>Lista de precios SAP</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>03</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/prioridad_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>prioridad_de_entrega__c</fullName>
    <label>Prioridad de entrega</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>alta</label>
            </value>
            <value>
                <fullName>02</fullName>
                <default>true</default>
                <label>normal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Proceso_Aprobado__c.field-meta.xml
<CustomField>
    <fullName>Proceso_Aprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proceso Aprobado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/RFC__c.field-meta.xml
<CustomField>
    <fullName>RFC__c</fullName>
    <description>RFC del cliente, para persona física 12 dígitos y para moral 13</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <default>true</default>
                <label>Asfalticos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/sector__c.field-meta.xml
<CustomField>
    <fullName>sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gobierno</fullName>
            </value>
            <value>
                <fullName>Privado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Oportunidad.recordType-meta.xml
<RecordType>
    <fullName>Oportunidad</fullName>
    <active>true</active>
    <businessProcess>Oportunidad</businessProcess>
    <description>Estandar</description>
    <label>Oportunidad</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Oportunidad_BIMSA.recordType-meta.xml
<RecordType>
    <fullName>Oportunidad_BIMSA</fullName>
    <active>true</active>
    <businessProcess>BIMSA</businessProcess>
    <label>Oportunidad BIMSA</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Pedido.recordType-meta.xml
<RecordType>
    <fullName>Pedido</fullName>
    <active>true</active>
    <businessProcess>Oportunidad</businessProcess>
    <label>Pedido</label>
</RecordType>

force-app/main/default/objects/Pricebook2/fields/Lista_de_precios_SAP__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_precios_SAP__c</fullName>
    <label>Lista de precios SAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lista_de_precios_SAP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lista_de_precios_SAP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <masterLabel>Lista de precios SAP</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_ViewPDF_Test.cls
/************************************************************************
Name: IMP_ViewPDF_Test
Copyright © 2023 Salesforce
========================================================================
Purpose:
Test class from the class IMP_ViewPDF_Test.
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      rortega@ts4.mx    12/10/2023     INITIAL        DEV CSR:
************************************************************************/
@isTest
public class IMP_ViewPDF_Test {
    
	/******************************************************************* 
    Purpose: Inserts all information to run the class method.
    Information about changes (versions):
    ********************************************************************/
    @testSetup static void inicializaDatos() {
        try{
            User administrador = [Select Id, UserRoleId,managerId From User Where Profile.Name='Administrador del sistema' AND isActive=true Limit 1];
            System.runAs(administrador){
            	Profile perfilUser=[SELECT Name, Id FROM Profile WHERE Name='Administrador del sistema'];
                
                User usuario = new User();
                usuario.Username ='usuarioprueba1@gmail.com';
                usuario.LastName ='Usuario1';
                usuario.FirstName ='Prueba1';
                usuario.CompanyName ='Imperquimia1';
                usuario.Email='usuariotest1@test.com';
                usuario.Phone = '45.56.12.34.10';
                usuario.IsActive =true;
                usuario.CommunityNickname='IMPQ1';
                usuario.TimeZoneSidKey='America/Mexico_City';
                usuario.LocaleSidKey='es_MX';
                usuario.EmailEncodingKey='UTF-8';
                usuario.Alias='impq1';
                usuario.ProfileId=perfilUser.Id;
                usuario.LanguageLocaleKey='es';
                usuario.ManagerId=administrador.Id;
                insert usuario;
                
                User usuario2 = new User();
                usuario2.Username ='usuarioprueba2@gmail.com';
                usuario2.LastName ='Usuario2';
                usuario2.FirstName ='Prueba2';
                usuario2.CompanyName ='Imperquimia';
                usuario2.Email='usuariotest2@test.com';
                usuario2.Phone = '45.56.12.34.12';
                usuario2.IsActive =true;
                usuario2.CommunityNickname='IMPQ2';
                usuario2.TimeZoneSidKey='America/Mexico_City';
                usuario2.LocaleSidKey='es_MX';
                usuario2.EmailEncodingKey='UTF-8';
                usuario2.Alias='impqus2';
                usuario2.ProfileId=perfilUser.Id;
                usuario2.LanguageLocaleKey='es';
                usuario2.ManagerId=administrador.Id;
                insert usuario2;
                
                Id pricebookId = Test.getStandardPricebookId();
                
                Pricebook2 listaPrecios = new Pricebook2(Name='AC01 - Mostrador', CurrencyIsoCode='MXN', 
                                                         IsActive=false, Description='Acapulco',Sucursal__c='AC01', 
                                                         Lista_de_precios_SAP__c='03');
                insert listaPrecios;
            
                Account cuentaTest = new Account(Name='Cuenta Prueba', BillingStreet='33 Calle Bahía de las Palmas', 
                                                 BillingCity='Ciudad de México', BillingPostalCode='11300', BillingCountry='México', Phone='5523456783', 
                                                 CurrencyIsoCode='MXN',
                                                 clave_delcanal__c='04', centro_suministrador__c='AC01', grupo__c='08', 
                                                 Condicion_de_expedicion__c='01', prioridad_de_entrega__c='02', 
                                                 RFC__c='0011MYA12345', Esquema_cliente__c='1', Grupo_de_Cuentas__c='121000', 
                                                 Grupo_de_precios__c='02', grupo_de_tesoreria__c='Y01', Sector__c='10',
                                                 CorreoElectronico__c='cuentaprueba@gmail.com', 
                                                 ListaPrecios__c='04', Proceso_Aprobado__c=false
                                                );
                Insert cuentaTest;
                
                RecordType oportunidadDistribucionRT=[SELECT Name, DeveloperName, sobjecttype, Id FROM RecordType where sobjectType='Opportunity' and DeveloperName='Oportunidad_BIMSA'];
                
                Opportunity oportunidadTest = new Opportunity(AccountId=cuentaTest.Id, RecordTypeId=oportunidadDistribucionRT.Id, 
                                                          Name='Oportunidad Test', StageName='Obra Negociada', Probability=100, 
                                                          CloseDate=date.today(), ForecastCategoryName='Closed', 
                                                          CurrencyIsoCode='MXN', Budget_Confirmed__c=false, Discovery_Completed__c=false, 
                                                          ROI_Analysis_Completed__c=false, OwnerId=usuario2.Id);
            	Insert oportunidadTest;
            
                Order pedido = new Order(Name='ORD-TEST', CurrencyIsoCode = 'MXN', 
                                         OpportunityId= oportunidadTest.Id, Pricebook2Id = listaPrecios.Id,Precio_Total__c = 500, 
                                         Status='Draft', AccountId = cuentaTest.Id, condiciones_de_pago__c = 'NT00'
                                         , EffectiveDate=Date.newInstance(2023, 04, 15)
                                         , ViaPago__c = 'C'
                                        );
                Insert pedido;
                
                Quote cotizacion = new Quote();
                cotizacion.Name = 'Test';
                cotizacion.OpportunityId = oportunidadTest.Id; 
                cotizacion.Pricebook2Id = listaPrecios.Id;
                cotizacion.CurrencyIsoCode='MXN';
                cotizacion.Tax=0.00;
                cotizacion.Status='Borrador'; 
                cotizacion.BillingName='Direccion Test'; 
                cotizacion.ShippingName='Direccion Test';
                Insert cotizacion;
            }
        }
        catch(Exception ex){
            System.debug(ex.getMessage());
            System.debug(ex.getCause());
            System.debug(ex.getLineNumber());
        }
    }
    
    /************************************************************************** 
    Purpose: Test the method to get the type of sboject
    Information about changes (versions)
    **************************************************************************/
    @isTest 
    public static void getObjectTypeNameOrder() {
        Order orderTest=[SELECT Id FROM Order WHERE Name='ORD-TEST' LIMIT 1];
		String idOrder =  orderTest.Id;       
        Test.startTest();
        String typeObjecto = IMP_ViewPDF_CC.getObjectTypeName(idOrder);
        System.assert(typeObjecto != null, '');
        Test.stopTest();
    }
    
    /************************************************************************** 
    Purpose: Test the method getPDF for create a record and saved it such as Order.
    Information about changes (versions)
    **************************************************************************/
    @isTest 
    public static void getPDFTestOrder() {
        Order orderTest=[SELECT Id FROM Order WHERE Name='ORD-TEST' LIMIT 1];
		String idOrder =  orderTest.Id;       
        Test.startTest();
        String idPdf = IMP_ViewPDF_CC.getPDF(idOrder, 'Order');
        System.assert(idPdf != null, '');
        Test.stopTest();
    }
    
    /************************************************************************** 
    Purpose: Test the method getPDF for create a record and saved it such as Quote.
    Information about changes (versions)
    **************************************************************************/
    @isTest 
    public static void getPDFTestQuote() {
        Quote quoteTest=[SELECT Id FROM Quote WHERE Name='Test' LIMIT 1];
		String idQuote =  quoteTest.Id;       
        Test.startTest();
        String idPdf = IMP_ViewPDF_CC.getPDF(idQuote, 'Quote');
        System.assert(idPdf != null, '');
        Test.stopTest();
    }
}