force-app/main/default/objects/Account/fields/centro_suministrador__c.field-meta.xml
<CustomField>
    <fullName>centro_suministrador__c</fullName>
    <label>Centro Suministrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC01</fullName>
                <label>Acapulco</label>
            </value>
            <value>
                <fullName>CA01</fullName>
                <label>Cancún</label>
            </value>
            <value>
                <fullName>CH01</fullName>
                <label>Chihuahua</label>
            </value>
            <value>
                <fullName>CU01</fullName>
                <label>Culiacán</label>
            </value>
            <value>
                <fullName>CV01</fullName>
                <label>Cuernavaca</label>
            </value>
            <value>
                <fullName>ERMI</fullName>
                <label>Ermita</label>
            </value>
            <value>
                <fullName>GD01</fullName>
                <label>Guadalajara</label>
            </value>
            <value>
                <fullName>HE01</fullName>
                <label>Hermosillo</label>
            </value>
            <value>
                <fullName>IMPQ</fullName>
                <label>Imperquimia</label>
            </value>
            <value>
                <fullName>IMPV</fullName>
                <label>Imperquimia Ventas</label>
            </value>
            <value>
                <fullName>LE01</fullName>
                <label>León</label>
            </value>
            <value>
                <fullName>ME01</fullName>
                <label>Mérida</label>
            </value>
            <value>
                <fullName>ME02</fullName>
                <label>Mérida II</label>
            </value>
            <value>
                <fullName>MIXC</fullName>
                <label>Mixcoac</label>
            </value>
            <value>
                <fullName>MT01</fullName>
                <label>Monterrey</label>
            </value>
            <value>
                <fullName>PSUR</fullName>
                <label>Perisur</label>
            </value>
            <value>
                <fullName>QE01</fullName>
                <label>Querétaro</label>
            </value>
            <value>
                <fullName>RAZA</fullName>
                <label>La Raza</label>
            </value>
            <value>
                <fullName>RIVI</fullName>
                <label>Riviera</label>
            </value>
            <value>
                <fullName>SATE</fullName>
                <label>Satélite</label>
            </value>
            <value>
                <fullName>TJ01</fullName>
                <label>Tijuana</label>
            </value>
            <value>
                <fullName>VE01</fullName>
                <label>Veracruz</label>
            </value>
            <value>
                <fullName>VI01</fullName>
                <label>Villahermosa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/condiciones_de_pago__c.field-meta.xml
<CustomField>
    <fullName>condiciones_de_pago__c</fullName>
    <defaultValue>&quot;NT00&quot;</defaultValue>
    <label>Condiciones de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NT00</fullName>
                <label>Pagado a la recepcion</label>
            </value>
            <value>
                <fullName>NT08</fullName>
                <label>Vencimiento 08 dias</label>
            </value>
            <value>
                <fullName>NT15</fullName>
                <label>Vencimiento 15 dias</label>
            </value>
            <value>
                <fullName>NT20</fullName>
                <label>Vencimiento 20 dias</label>
            </value>
            <value>
                <fullName>NT30</fullName>
                <label>Vencimiento 30 dias</label>
            </value>
            <value>
                <fullName>NT45</fullName>
                <label>Vencimiento 45 dias</label>
            </value>
            <value>
                <fullName>NT60</fullName>
                <label>Vencimiento 60 dias</label>
            </value>
            <value>
                <fullName>NT90</fullName>
                <label>Vencimiento 90 dias</label>
            </value>
            <value>
                <fullName>NT120</fullName>
                <label>Vencimiento 120 dias</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ViaPago__c.field-meta.xml
<CustomField>
    <fullName>ViaPago__c</fullName>
    <label>Vía de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>via_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_CanalDistribucion__c.field-meta.xml
<CustomField>
    <fullName>IMP_CanalDistribucion__c</fullName>
    <label>Canal de distribución</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_CanalVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_CanalVentas__c</fullName>
    <label>Organización de ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_CentroBeneficio__c.field-meta.xml
<CustomField>
    <fullName>IMP_CentroBeneficio__c</fullName>
    <label>Centro de beneficio</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_ClaseDocumento__c.field-meta.xml
<CustomField>
    <fullName>IMP_ClaseDocumento__c</fullName>
    <label>Clase de documento</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_CreadoPor__c.field-meta.xml
<CustomField>
    <fullName>IMP_CreadoPor__c</fullName>
    <label>Creado por</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SF</fullName>
                <default>true</default>
                <label>SF</label>
            </value>
            <value>
                <fullName>TIO</fullName>
            </value>
            <value>
                <fullName>PLENUS</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_DescripcionCeBe__c.field-meta.xml
<CustomField>
    <fullName>IMP_DescripcionCeBe__c</fullName>
    <label>Descripción Ce Be</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_DescripcionGrupoVendedor__c.field-meta.xml
<CustomField>
    <fullName>IMP_DescripcionGrupoVendedor__c</fullName>
    <label>Descripción Grupo Vendedor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_GrupoVendedor__c.field-meta.xml
<CustomField>
    <fullName>IMP_GrupoVendedor__c</fullName>
    <label>Grupo vendedor</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_NumeroCliente__c.field-meta.xml
<CustomField>
    <fullName>IMP_NumeroCliente__c</fullName>
    <label>Número de cliente</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_OficinaVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_OficinaVentas__c</fullName>
    <label>Oficina de ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_SectorVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_SectorVentas__c</fullName>
    <label>Sector de Ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/pedido__c.field-meta.xml
<CustomField>
    <fullName>pedido__c</fullName>
    <description>Número de pedido en SAP</description>
    <externalId>true</externalId>
    <label>ID Pedido SAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ViaPago__c.field-meta.xml
<CustomField>
    <fullName>ViaPago__c</fullName>
    <label>Vía de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>via_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/via_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>C</fullName>
        <label>Cheque</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>Deposito</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>Efectivo</label>
    </customValue>
    <customValue>
        <fullName>F</fullName>
        <label>Tarjeta de crédito</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Cheque Prod IQ</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>Tarjeta de Débito</label>
    </customValue>
    <customValue>
        <fullName>I</fullName>
        <label>Nota de Credito</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Por Definir</label>
    </customValue>
    <customValue>
        <fullName>T</fullName>
        <label>Transferencia Bancaria</label>
    </customValue>
    <masterLabel>Via de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_ListPedido.cls
/************************************************************************
Name: IMP_ListPedido
Copyright © 2022 Salesforce
========================================================================
Purpose:
Servicio web para la consulta de pedidos desde SAP 
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
 1.0      rotrejo@ts4.mx      12/05/2023    
************************************************************************/
public class IMP_ListPedido {
  public String PI_FFIN;
  public String PI_FINI;
  public List<IMP_EnvioPedidoSAP> IT_PEDIDOS;

  /*******************************************************************
    Purpose: Actualiza los pedidos al dia de hoy.
    Parameters:
    Returns:
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
  public static List<Order> getListPedido(
    String fechaInicial,
    String fechaFinal
  ) {
    IMP_ListPedido newConsulta = new IMP_ListPedido();
    List<IMP_EnvioPedidoSAP> listPedidos = new List<IMP_EnvioPedidoSAP>();
    IMP_EnvioPedidoSAP pedido = new IMP_EnvioPedidoSAP();
    listPedidos.add(pedido);
    System.debug(String.valueOf(fechaInicial));
    System.debug(String.valueOf(fechaFinal));
    newConsulta.PI_FFIN = fechaFinal; //'31-05-2023';
    newConsulta.PI_FINI = fechaInicial; //'01-05-2023';
    newConsulta.IT_PEDIDOS = listPedidos;
    String body = JSON.serialize(newConsulta);
    System.debug(body);
    HttpResponse response = IMP_CalloutUtils.getResponse(
      body,
      IMP_ServiceConstants.PEDIDOS_API_URL
    );
    System.debug(response.getBody());
    Map<String, Object> jsonData = (Map<String, Object>) JSON.deserializeUntyped(
      response.getBody()
    );
    convertirAListaSiNecesario(jsonData, 'IT_PEDIDOS');
    String modifiedJson = JSON.serialize(jsonData);
    String newJsonString = convertObjectToArray(modifiedJson, 'IT_PEDIDOS');
    Map<String, Object> responseFlujoDocumentos = (Map<String, Object>) JSON.deserializeUntyped(
      newJsonString
    );
    System.debug('el JSON ' + newJsonString);
    IMP_ListPedido discountResponse = (IMP_ListPedido) JSON.deserialize(
      newJsonString,
      IMP_ListPedido.class
    );
    List<Order> newListOrders = new List<Order>();
    set<String> setAccIds = new Set<String>();
    Set<Decimal> grupoVendedor = new Set<Decimal>();
    for (IMP_EnvioPedidoSAP nuevoPedido : discountResponse.IT_PEDIDOS) {
      setAccIds.add(nuevoPedido.I_KUNNR);
      if (nuevoPedido.I_VKGRP != '') {
        grupoVendedor.add(Decimal.valueOf(nuevoPedido.I_VKGRP));
      }
    }
    Map<String, Account> mapCuentas = IMP_FlujoDocumentos.getCuentas(setAccIds);
    Map<String, User> mapUsers = IMP_FlujoDocumentos.getUsers(grupoVendedor);
    Map<String, String> mapCentroSuministrador = new Map<String, String>();
    Schema.DescribeFieldResult fieldResult = Account.centro_suministrador__c.getDescribe();
    for (Schema.PicklistEntry f : fieldResult.getPicklistValues()) {
      mapCentroSuministrador.put(f.getValue(), f.getLabel());
    }
    for (IMP_EnvioPedidoSAP nuevoPedido : discountResponse.IT_PEDIDOS) {
      String sucursal =
        'Sucursal ' + mapCentroSuministrador.get(nuevoPedido.EXT1);
      String sucursalSinAcento = sucursal.replaceAll('á', 'a')
        .replaceAll('é', 'e')
        .replaceAll('í', 'i')
        .replace('ó', 'o')
        .replaceAll('ú', 'u');
      newListOrders.add(
        new Order(
          pedido__c = nuevoPedido.E_VBELN,
          ViaPago__c = nuevoPedido.ZLSCH,
          AccountId = mapCuentas.containsKey(
              nuevoPedido.I_KUNNR +
                nuevoPedido.I_VKORG +
                nuevoPedido.I_VTWEG +
                nuevoPedido.SPART
            )
            ? mapCuentas.get(
                  nuevoPedido.I_KUNNR +
                    nuevoPedido.I_VKORG +
                    nuevoPedido.I_VTWEG +
                    nuevoPedido.SPART
                )
                .Id
            : System.label.IMP_Cuenta,
          EffectiveDate = nuevoPedido.BSTDK.length() == 8 &&
            nuevoPedido.BSTDK != '00000000'
            ? Date.valueOf(
                nuevoPedido.BSTDK.substring(0, 4) +
                  '-' +
                  nuevoPedido.BSTDK.substring(4, 6) +
                  '-' +
                  nuevoPedido.BSTDK.substring(6, 8)
              )
            : nuevoPedido.BSTDK == '00000000'
                ? Date.today()
                : Date.valueOf(nuevoPedido.BSTDK),
          IMP_ClaseDocumento__c = nuevoPedido.AUART,
          IMP_OficinaVentas__c = nuevoPedido.I_VKBUR,
          IMP_CanalVentas__c = nuevoPedido.I_VKORG,
          IMP_SectorVentas__c = nuevoPedido.SPART,
          IMP_NumeroCliente__c = nuevoPedido.I_KUNNR,
          IMP_GrupoVendedor__c = nuevoPedido.I_VKGRP,
          IMP_DescripcionGrupoVendedor__c = nuevoPedido.BEZEI,
          IMP_DescripcionCeBe__c = nuevoPedido.LTEXT,
          IMP_CentroBeneficio__c = nuevoPedido.PRCTR,
          Precio_Total__c = nuevoPedido.NETWR != null &&
            nuevoPedido.NETWR != ''
            ? Decimal.valueOf(nuevoPedido.NETWR.replace(' ', ''))
            : 0,
          IMP_CreadoPor__c = nuevoPedido.ERNAM,
          Status = nuevoPedido.GBSTK != '' ? nuevoPedido.GBSTK : 'Draft',
          condiciones_de_pago__c = nuevoPedido.ZTERM,
          IMP_CanalDistribucion__c = nuevoPedido.I_VTWEG,
          OwnerId = (nuevoPedido.I_VKGRP == '001')
            ? mapUsers.containsKey(sucursal)
                ? mapUsers.get(sucursal).id
                : mapUsers.containsKey(sucursalSinAcento)
                    ? mapUsers.get(sucursalSinAcento).id
                    : UserInfo.getUserId()
            : mapUsers.containsKey(nuevoPedido.I_VKGRP)
                ? mapUsers.get(nuevoPedido.I_VKGRP).id
                : UserInfo.getUserId()
        )
      );
    }
    return newListOrders;
  }

  public static String convertObjectToArray(
    String jsonString,
    String objectKey
  ) {
    // Convertir el JSON original a un mapa de objetos sin tipo
    Map<String, Object> jsonData = (Map<String, Object>) JSON.deserializeUntyped(
      jsonString
    );
    if (jsonData.containsKey(objectKey)) {
      Object tA305Object = jsonData.get(objectKey);
      if (tA305Object instanceof Map<String, Object>) {
        Map<String, Object> tA305Map = (Map<String, Object>) tA305Object;
        if (
          tA305Map.containsKey('item') &&
          tA305Map.get('item') instanceof List<Object>
        ) {
          List<Object> itemList = (List<Object>) tA305Map.get('item');
          jsonData.put(objectKey, itemList);
          jsonData.remove('item');
        }
      }
    }

    String updatedJsonDataString = JSON.serialize(jsonData);

    // Paso 4: Convertir el mapa en formato JSON
    return JSON.serialize(jsonData);
  }

  public static void convertirAListaSiNecesario(
    Map<String, Object> jsonData,
    String clave
  ) {
    Object objeto = jsonData.get(clave);
    if (String.valueOf(objeto).contains('{item={')) {
      Map<String, Object> mapa = (Map<String, Object>) objeto;
      List<Object> lista = new List<Object>();
      lista.add(mapa.get('item'));
      mapa.put('item', lista);
    }
  }
}