force-app/main/default/objects/Account/fields/centro_suministrador__c.field-meta.xml
<CustomField>
    <fullName>centro_suministrador__c</fullName>
    <label>Centro Suministrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC01</fullName>
                <label>Acapulco</label>
            </value>
            <value>
                <fullName>CA01</fullName>
                <label>Cancún</label>
            </value>
            <value>
                <fullName>CH01</fullName>
                <label>Chihuahua</label>
            </value>
            <value>
                <fullName>CU01</fullName>
                <label>Culiacán</label>
            </value>
            <value>
                <fullName>CV01</fullName>
                <label>Cuernavaca</label>
            </value>
            <value>
                <fullName>ERMI</fullName>
                <label>Ermita</label>
            </value>
            <value>
                <fullName>GD01</fullName>
                <label>Guadalajara</label>
            </value>
            <value>
                <fullName>HE01</fullName>
                <label>Hermosillo</label>
            </value>
            <value>
                <fullName>IMPQ</fullName>
                <label>Imperquimia</label>
            </value>
            <value>
                <fullName>IMPV</fullName>
                <label>Imperquimia Ventas</label>
            </value>
            <value>
                <fullName>LE01</fullName>
                <label>León</label>
            </value>
            <value>
                <fullName>ME01</fullName>
                <label>Mérida</label>
            </value>
            <value>
                <fullName>ME02</fullName>
                <label>Mérida II</label>
            </value>
            <value>
                <fullName>MIXC</fullName>
                <label>Mixcoac</label>
            </value>
            <value>
                <fullName>MT01</fullName>
                <label>Monterrey</label>
            </value>
            <value>
                <fullName>PSUR</fullName>
                <label>Perisur</label>
            </value>
            <value>
                <fullName>QE01</fullName>
                <label>Querétaro</label>
            </value>
            <value>
                <fullName>RAZA</fullName>
                <label>La Raza</label>
            </value>
            <value>
                <fullName>RIVI</fullName>
                <label>Riviera</label>
            </value>
            <value>
                <fullName>SATE</fullName>
                <label>Satélite</label>
            </value>
            <value>
                <fullName>TJ01</fullName>
                <label>Tijuana</label>
            </value>
            <value>
                <fullName>VE01</fullName>
                <label>Veracruz</label>
            </value>
            <value>
                <fullName>VI01</fullName>
                <label>Villahermosa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/grupo__c.field-meta.xml
<CustomField>
    <fullName>grupo__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Distribuidor A</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Distribuidor B</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Distribuidor C</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidor D</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Contratistas A</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Contratistas B</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Contratistas C</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Multimarcas A</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Multimarcas B</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Multimarcas C</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Desarrollo de Negoci</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Aplicador A</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Contratistas Plus</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ListaPrecios__c.field-meta.xml
<CustomField>
    <fullName>ListaPrecios__c</fullName>
    <label>Lista de precios SAP</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>03</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OrganizacionVentas__c.field-meta.xml
<CustomField>
    <fullName>OrganizacionVentas__c</fullName>
    <label>Organización de Ventas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GOGA</fullName>
                <label>Gogal</label>
            </value>
            <value>
                <fullName>GRAV</fullName>
                <label>Graviq</label>
            </value>
            <value>
                <fullName>IMPQ</fullName>
                <default>true</default>
                <label>Imperquimia SA de CV</label>
            </value>
            <value>
                <fullName>IQSE</fullName>
                <label>IQ Servicios</label>
            </value>
            <value>
                <fullName>LEMA</fullName>
                <label>Lemma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RFC__c.field-meta.xml
<CustomField>
    <fullName>RFC__c</fullName>
    <description>RFC del cliente, para persona física 12 dígitos y para moral 13</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/PoliticaDescuento__c.object-meta.xml
<CustomObject>
    <label>Política de descuento</label>
    <nameField>
        <label>Nombre de Política de descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Politicas de descuento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PoliticaDescuento__c/fields/Activa__c.field-meta.xml
<CustomField>
    <fullName>Activa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/fields/Canaldistribucion__c.field-meta.xml
<CustomField>
    <fullName>Canaldistribucion__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanalDistribucion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/fields/Descuento__c.field-meta.xml
<CustomField>
    <fullName>Descuento__c</fullName>
    <inlineHelpText>Este valor calcula el descuento para la política</inlineHelpText>
    <label>Descuento</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/fields/Grupo_de_cliente_del__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_cliente_del__c</fullName>
    <label>Grupo de cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_de_Cliente</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Lista_de_precios_SAP__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_precios_SAP__c</fullName>
    <label>Lista de precios SAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lista_de_precios_SAP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/centro_suministrador__c.field-meta.xml
<CustomField>
    <fullName>centro_suministrador__c</fullName>
    <label>Centro Suministrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Grupo_de_art_culos__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_art_culos__c</fullName>
    <label>Grupo de artículos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ESPA</fullName>
                <label>Espacios</label>
            </value>
            <value>
                <fullName>GUARQM</fullName>
                <label>Guardquim</label>
            </value>
            <value>
                <fullName>IMPERC</fullName>
                <label>Impercryl</label>
            </value>
            <value>
                <fullName>NAYA</fullName>
                <label>Naya</label>
            </value>
            <value>
                <fullName>QUIMCR</fullName>
                <label>Quimicret</label>
            </value>
            <value>
                <fullName>SELLAQ</fullName>
                <label>Sellaquim</label>
            </value>
            <value>
                <fullName>SOPORT</fullName>
                <label>Soporte</label>
            </value>
            <value>
                <fullName>DOCFIN</fullName>
                <label>Documento Financiero</label>
            </value>
            <value>
                <fullName>ACCESO</fullName>
                <label>Accesorio</label>
            </value>
            <value>
                <fullName>IQ</fullName>
                <label>Imperquimia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Grupo_de_Materiales__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Materiales__c</fullName>
    <label>Grupo de Materiales</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_de_materiales</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PoliticaDescuento__c.field-meta.xml
<CustomField>
    <fullName>PoliticaDescuento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Política de descuento</label>
    <referenceTo>PoliticaDescuento__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/CanalDistribucion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>E-Commerce</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Obras y Proyectos</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Des. Negocios</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Industriales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Exportación</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Call Center</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Ventas Directas</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Mayorista</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Otras Ventas</label>
    </customValue>
    <masterLabel>Canal de distribución</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_de_Cliente.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Distribuidor A</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Distribuidor B</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Distribuidor C</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidor D</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Contratistas A</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Contratistas B</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Contratistas C</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Multimarcas A</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Multimarcas B</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Multimarcas C</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>Obras y Proyectos</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Industriales</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Exportación</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Desarrollo de Negoci</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Call Center</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>Aplicador A</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>Contratistas Plus</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>Retail</label>
    </customValue>
    <masterLabel>Grupo de Cliente</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_de_materiales.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Lineas Generales</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Lineas Mayoristas</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Lineas Populares</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Commodity</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Especiales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Ultra Comodity</label>
    </customValue>
    <masterLabel>Grupo de materiales</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lista_de_precios_SAP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <masterLabel>Lista de precios SAP</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_CotizadorProductos_Test.cls
/************************************************************************
Name: IMP_CotizadorProductos_Test
Copyright © 2022 Salesforce
========================================================================
Purpose:
Test class from the class IMP_CotizadorProductosController.
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      mmauro@ts4.mx    20/01/2021     INITIAL        DEV CSR:
************************************************************************/
@isTest
public without sharing class IMP_CotizadorProductos_Test {
/******************************************************************* 
    Purpose: Inserts all information to run the class method.
    Information about changes (versions):
    ********************************************************************/ 
    @testSetup static void setup(){
        User administrador = [Select Id, UserRoleId,managerId From User Where Profile.Name='Administrador del sistema' AND isActive=true Limit 1];
        System.runAs(administrador){
            
            Profile perfilUser=[SELECT Name, Id FROM Profile WHERE Name='Administrador del sistema'];
            
            User usuario = new User();
            usuario.Username ='usuarioprueba1@gmail.com';
            usuario.LastName ='Usuario1';
            usuario.FirstName ='Prueba1';
            usuario.CompanyName ='Imperquimia1';
            usuario.Email='usuariotest1@test.com';
            usuario.Phone = '45.56.12.34.10';
            usuario.IsActive =true;
            usuario.CommunityNickname='IMPQ1';
            usuario.TimeZoneSidKey='America/Mexico_City';
            usuario.LocaleSidKey='es_MX';
            usuario.EmailEncodingKey='UTF-8';
            usuario.Alias='impq1';
            usuario.ProfileId=perfilUser.Id;
            usuario.LanguageLocaleKey='es';
            usuario.ManagerId=administrador.Id;
            insert usuario;
            
            
            User usuario2 = new User();
            usuario2.Username ='usuarioprueba2@gmail.com';
            usuario2.LastName ='Usuario2';
            usuario2.FirstName ='Prueba2';
            usuario2.CompanyName ='Imperquimia';
            usuario2.Email='usuariotest2@test.com';
            usuario2.Phone = '45.56.12.34.12';
            usuario2.IsActive =true;
            usuario2.CommunityNickname='IMPQ2';
            usuario2.TimeZoneSidKey='America/Mexico_City';
            usuario2.LocaleSidKey='es_MX';
            usuario2.EmailEncodingKey='UTF-8';
            usuario2.Alias='impqus2';
            usuario2.ProfileId=perfilUser.Id;
            usuario2.LanguageLocaleKey='es';
            usuario2.ManagerId=administrador.Id;
            insert usuario2;
            
            Account cuenta = new Account();
            cuenta.OrganizacionVentas__c = 'IMPQ';
            cuenta.name = 'Cuenta Prueba';
            cuenta.id_de_sap__c = '0001032287';
            cuenta.RFC__c = '0011MYA12345';
            cuenta.CurrencyIsoCode = 'MXN';
            cuenta.centro_suministrador__c = 'AC01';
            cuenta.clave_delcanal__c = '02';
            cuenta.ListaPrecios__c='03';
            cuenta.grupo__c = '17';
            cuenta.Phone='+52 7225398962';
            insert cuenta;
            
            RecordType recordTypeOportunidad=[SELECT Name, DeveloperName,sobjecttype, Id FROM RecordType where sobjectType='Opportunity' and DeveloperName='Oportunidad'];
            
            Opportunity oportunidad = new Opportunity();
            oportunidad.AccountId = cuenta.Id;
            oportunidad.Name = 'Oportunidad Test';
            oportunidad.StageName = 'Plan';
            oportunidad.CurrencyIsoCode = 'MXN';
            oportunidad.CloseDate = Date.today().addDays(30);
            oportunidad.RecordTypeId=recordTypeOportunidad.Id;
            oportunidad.Amount=3850.6;
            oportunidad.Probability=100; 
            oportunidad.OwnerId=usuario2.Id;
            insert oportunidad;
            
            Product2 prod =new Product2();
            prod.Name = 'IMPERMEABILIZANTE';
            prod.ProductCode='IMP-12345';
            prod.Family = 'Naya';
            prod.Description = '';
            prod.IsActive = true;
            prod.CurrencyIsoCode='MXN';
            prod.Grupo_de_Materiales__c ='03';    
            prod.Grupo_de_art_culos__c = 'IQ';        
            Insert prod;
            
            Product2 prod2 =new Product2();
            prod2.Name = 'IMPERMEABILIZANTE 2 ';
            prod2.ProductCode='IMP-123456';
            prod2.Family = 'Naya';
            prod2.Description = '';
            prod2.IsActive = true;
            prod2.CurrencyIsoCode='MXN';
            prod2.Grupo_de_Materiales__c ='04'; 
            prod2.Grupo_de_art_culos__c = 'IQ';               
            Insert prod2;
            
            Product2 prod3 =new Product2();
            prod3.Name = 'IMPERMEABILIZANTE3';
            prod3.ProductCode='IMP-123457';
            prod3.Family = 'Naya';
            prod3.Description = '';
            prod3.IsActive = false;
            prod3.CurrencyIsoCode='MXN';
            prod3.Grupo_de_Materiales__c ='';  
            prod3.Grupo_de_art_culos__c = 'IQ';              
            Insert prod3;
            
            Id pricebookId = Test.getStandardPricebookId(); 
            
            Pricebook2 listaPrecios = new Pricebook2();
            listaPrecios.Name='AC01 - Distribuidor';
            listaPrecios.Sucursal__c='AC01';
            listaPrecios.CurrencyIsoCode='MXN';
            listaPrecios.IsActive=true;
            listaPrecios.Lista_de_precios_SAP__c='04';
        
            insert listaPrecios;
            
            PricebookEntry pbeSt = new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = prod.Id,
                IsActive = true,
                CurrencyIsoCode='MXN',
                UnitPrice = 150,
                UseStandardPrice=false
            );
            
            insert pbeSt;    
            
            PricebookEntry pbeSt2 = new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = prod2.Id,
                IsActive = true,
                CurrencyIsoCode='MXN',
                UnitPrice = 150,
                UseStandardPrice=false
            );
            
            insert pbeSt2; 
            
            PricebookEntry pbe = new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = prod3.Id,
                IsActive = true,
                CurrencyIsoCode='MXN',
                UnitPrice = 500,
                UseStandardPrice=false
            );            
            insert pbe;
            
            
            Quote cotizacion = new Quote();
            cotizacion.Name = 'Test';
            cotizacion.OpportunityId = oportunidad.Id; 
            cotizacion.Pricebook2Id = pricebookId;
            cotizacion.CurrencyIsoCode='MXN';
            cotizacion.Tax=0.00;
            cotizacion.Status='Borrador'; 
            cotizacion.BillingName='Direccion Test'; 
            cotizacion.ShippingName='Direccion Test';
            Insert cotizacion;
            
            PoliticaDescuento__c  politicaDescuento = new PoliticaDescuento__c ();
            politicaDescuento.Name = 'Distribuidor A/ Populares';
            politicaDescuento.Activa__c  = true;
            politicaDescuento.CurrencyIsoCode = 'MXN';
            politicaDescuento.Descuento__c  = 70.2;
            politicaDescuento.Grupo_de_cliente_del__c = '17';
            politicaDescuento.Canaldistribucion__c = '02';        
            politicaDescuento.GrupoProducto__c = '03';
            Insert politicaDescuento;
            
            List<QuoteLineItem> listaQli=new List<QuoteLineItem>();
            
            QuoteLineItem productEdit = new QuoteLineItem();
            productEdit.Quantity  = 2;
            productEdit.QuoteId = cotizacion.Id;  
            productEdit.Product2Id = prod.Id;
            productEdit.Descuento_adicional__c = 20.0;
            productEdit.DescuentoSAP__c = 46.0;
            productEdit.IMP_DescuentoPromo__c = 25.0;
            productEdit.UnitPrice=150;
            productEdit.PricebookEntryId=pbeSt.Id; 
            productEdit.PoliticaDescuento__c=politicaDescuento.Id;
            productEdit.Descuento_adicional__c = 10.0;
            listaQli.add(productEdit);
            
            QuoteLineItem productEdit1 = new QuoteLineItem();
            productEdit1.Quantity  = 2;
            productEdit1.QuoteId = cotizacion.Id;
            productEdit1.Product2Id = prod.Id;
            productEdit1.Descuento_adicional__c = 20.0;
            productEdit1.DescuentoSAP__c = 46.0;
            productEdit1.IMP_DescuentoPromo__c = 50;
            productEdit1.UnitPrice=500;
            productEdit1.Discount=66.0;     
            productEdit1.PoliticaDescuento__c=politicaDescuento.Id;
            productEdit1.Descuento_adicional__c = 13.0;
            productEdit1.PricebookEntryId=pbeSt.Id; 
            
            listaQli.add(productEdit1);
            
            QuoteLineItem productEdit2 = new QuoteLineItem();
            productEdit2.Quantity  = 2;
            productEdit2.QuoteId = cotizacion.Id;
            productEdit2.Product2Id = prod3.Id;
            productEdit2.Descuento_adicional__c = 20.0;
            productEdit2.DescuentoSAP__c = 46.0;
            productEdit2.UnitPrice=500;
            productEdit2.Discount=66.0;     
            productEdit2.PoliticaDescuento__c=politicaDescuento.Id;
            productEdit2.PricebookEntryId=pbe.Id; 
            
            productEdit2.Descuento_adicional__c = 14.0; 
            
            listaQli.add(productEdit2);
            Insert listaQli;

            Descuento__c descuento = new Descuento__c();
            descuento.IMP_SecuenciaAcceso__c = 'A993';
            descuento.IMP_OrganizacionVentas__c = 'IMPQ';
            descuento.IMP_ClaseCondicion__c = 'KA00';
            descuento.IMP_CanalVentas__c = '02';
            descuento.IMP_GrupoArticulos__c = 'IQ';
            descuento.IMP_GrupoClientes__c = '17';
            descuento.IMP_FechaInicial__c =  Date.newInstance(2023, 3, 29); 
            descuento.IMP_FechaFinal__c = Date.newInstance(2100, 12, 31);
            descuento.IMP_ImportePorcentaje__c = 20;
            descuento.IMP_UnidadCondicion__c = '%';
            
            Insert descuento;

        }
         
    }
    /******************************************************************* 
    Purpose: Test class method that obtains the information of the quotation.
    Parameters:
    Returns: 
    Throws :
    Information about changes (versions)
    ********************************************************************/
    @isTest
    public static void getCotizacion(){ 
        Quote cotizacion = [SELECT Id, Name,pricebook2Id FROM Quote WHERE Name = 'Test'];
        Test.startTest();
        IMP_CotizadorProductosController.getInitialData(cotizacion.Id);
        System.assert(cotizacion != null,'Products cannot be null');                
        Test.stopTest();
    }
    
    /******************************************************************* 
    Purpose: Test class method that obtains the products that match the search code or description
    Parameters:String nombre,Id listaPrecios, Integer pageSize, Integer pageNumber, String  recordId.
    Returns: 
    Throws :
    Information about changes (versions)
    ********************************************************************/     
    @isTest
    public static void getProductos(){
        Quote cotizacion = [SELECT Id, Name, PriceBook2Id,CurrencyIsoCode FROM Quote WHERE Name = 'Test']; 
        IMP_InventarioManager respuesta = new IMP_InventarioManager();
        List<IMP_InventarioManager.cls_ZINVENTARIOS> listProd= new List<IMP_InventarioManager.cls_ZINVENTARIOS>();
        IMP_InventarioManager.cls_ZINVENTARIOS prod= new IMP_InventarioManager.cls_ZINVENTARIOS();
        prod.CHARG='0000092273';
        prod.CLABS=100;
        prod.HSDAT='2021-08-12';
        prod.MATNR='IMP-12345';
        listProd.add(prod);
        IMP_InventarioManager.cls_ZINVENTARIOS prod2= new IMP_InventarioManager.cls_ZINVENTARIOS();
        prod2.CHARG='0000092273';
        prod2.CLABS=100;
        prod2.HSDAT='2021-08-12';
        prod2.MATNR='IMP-123457';
        listProd.add(prod2);
        respuesta.ZINVENTARIOS=listProd;
        String body=JSON.serialize(respuesta);  
        Test.startTest();               
        IMP_CotizadorProductosController.getProductos('1234', cotizacion.PriceBook2Id, 1, 1,cotizacion.Id);
        Test.stopTest();
        System.assert( cotizacion != null,'Quote cannot be null');                
                
    }
/******************************************************************* 
Purpose: Test class method that creates item records of a quote.
Parameters:PricebookEntry pricebook , Id cotizacion.
Returns: 
Throws :
Information about changes (versions)
********************************************************************/    
    @isTest
    public static void crearQuoteLineItem(){ 
        Quote cotizacion = [SELECT Id, Name,Pricebook2Id, (SELECT Id, QuoteId FROM QuoteLineItems) FROM Quote WHERE Name = 'Test'];             
        Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = 'IMPERMEABILIZANTE'];
        PricebookEntry pricebook = [SELECT Id , Product2Id,Product2.ProductCode,Product2.Grupo_de_Materiales__c, Product2.Grupo_de_art_culos__c, UnitPrice FROM PricebookEntry WHERE Pricebook2Id=:cotizacion.Pricebook2Id AND Product2Id =: product.Id];
        IMP_InventarioManager respuesta = new IMP_InventarioManager();
        List<IMP_InventarioManager.cls_ZINVENTARIOS> listProd= new List<IMP_InventarioManager.cls_ZINVENTARIOS>();
        IMP_InventarioManager.cls_ZINVENTARIOS prod= new IMP_InventarioManager.cls_ZINVENTARIOS();
        prod.CHARG='0000092273';
        prod.CLABS=100;
        prod.HSDAT='2021-08-12';
        prod.MATNR='IMP-12345';
        listProd.add(prod);
        IMP_InventarioManager.cls_ZINVENTARIOS prod2= new IMP_InventarioManager.cls_ZINVENTARIOS();
        prod2.CHARG='0000092273';
        prod2.CLABS=100;
        prod2.HSDAT='2021-08-12';
        prod2.MATNR='IMP-123457';
        listProd.add(prod2);
        IMP_InventarioManager.cls_ZINVENTARIOS prod3= new IMP_InventarioManager.cls_ZINVENTARIOS();
        prod3.CHARG='0000092273';
        prod3.CLABS=100;
        prod3.HSDAT='2021-08-12';
        prod3.MATNR='IMP-123457';
        listProd.add(prod3);
        respuesta.ZINVENTARIOS=listProd;
        String body=JSON.serialize(respuesta);        
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        IMP_CotizadorProductosController.crearQuoteLineItem(pricebook, cotizacion.Id);
        System.assert(pricebook != null,'Products cannot be null');                
        Test.stopTest();
        
    }
    
    @isTest
    public static void crearQuoteLineItem2(){ 
        Quote cotizacion = [SELECT Id, Name,Pricebook2Id, (SELECT Id, QuoteId FROM QuoteLineItems) FROM Quote WHERE Name = 'Test'];             
        Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = 'IMPERMEABILIZANTE3'];
        PricebookEntry pricebook = [SELECT Id , Product2Id,Product2.ProductCode,Product2.Grupo_de_Materiales__c, Product2.Grupo_de_art_culos__c, UnitPrice FROM PricebookEntry WHERE Pricebook2Id=:cotizacion.Pricebook2Id AND Product2Id =: product.Id];
        IMP_InventarioManager respuesta = new IMP_InventarioManager();
        List<IMP_InventarioManager.cls_ZINVENTARIOS> listProd= new List<IMP_InventarioManager.cls_ZINVENTARIOS>();
        IMP_InventarioManager.cls_ZINVENTARIOS prod= new IMP_InventarioManager.cls_ZINVENTARIOS();
        prod.CHARG='0000092273';
        prod.CLABS=100;
        prod.HSDAT='2021-08-12';
        prod.MATNR='IMP-12345';
        listProd.add(prod);
        IMP_InventarioManager.cls_ZINVENTARIOS prod2= new IMP_InventarioManager.cls_ZINVENTARIOS();
        prod2.CHARG='0000092273';
        prod2.CLABS=100;
        prod2.HSDAT='2021-08-12';
        prod2.MATNR='IMP-123457';
        listProd.add(prod2);
        respuesta.ZINVENTARIOS=listProd;
        String body=JSON.serialize(respuesta);      
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        IMP_CotizadorProductosController.crearQuoteLineItem(pricebook, cotizacion.Id);
        System.assert(pricebook != null,'Products cannot be null');                
        Test.stopTest();
        
    }
    /******************************************************************* 
    Purpose: Test class method that delete item records for a quote.
    Parameters:QuoteLineItem productEdit.
    Returns: 
    Throws :
    Information about changes (versions)
    ********************************************************************/      
    @isTest
    public static void deleteQuoteLineItem(){
        Quote cotizacion = [SELECT Id, Name,Pricebook2Id FROM Quote WHERE Name = 'Test'];
        QuoteLineItem productEdit=[SELECT Id, QuoteId FROM QuoteLineItem WHERE Quote.Name=:'Test' Limit 1];
        
        Test.startTest();
        System.assert(cotizacion != null,'Products cannot be null');                
        IMP_CotizadorProductosController.deleteQuoteLineItem(productEdit);
        Test.stopTest();
        
    }
    /******************************************************************* 
    Purpose: Test class method that updates item records for a quote.
    Parameters:QuoteLineItem productEdit ,  String tipoACampo.
    Returns: 
    Throws :
    Information about changes (versions)
    ********************************************************************/    
    @isTest
    public static void updateQuoteLineItem(){
        Quote cotizacion = [SELECT Id, Name,Pricebook2Id FROM Quote WHERE Name = 'Test'];
        QuoteLineItem productEdit=[SELECT Id,QuoteId,Quantity,Descuento_adicional__c,PrecioTotalConDescuentos__c,TotalPrice, IMP_OmitirDescuentoSAP__c, IMP_DescuentoPromo__c FROM QuoteLineItem WHERE Quote.Name=:'Test' Limit 1];
        productEdit.PrecioTotalConDescuentos__c = productEdit.TotalPrice;
        update productEdit;
        String tipoACampoC = 'Cantidad';
        
        IMP_CotizadorProductosController.updateQuoteLineItem(productEdit, tipoACampoC);
        Test.startTest();
        System.assert(IMP_CotizadorProductosController.updateQuoteLineItem(productEdit, tipoACampoC) != null,'Products cannot be null');                
        Test.stopTest();
        
    }

    /******************************************************************* 
    Purpose: Test class method that update the QuoteLineItem with the added discount.
    Parameters:QuoteLineItem productEdit ,  Double valueDesc.
    Returns: 
    Throws :
    Information about changes (versions)
    ********************************************************************/      
    @isTest
    public static void procesoDescuento(){
        Quote cotizacion = [SELECT Id, Name,Pricebook2Id FROM Quote WHERE Name = 'Test'];
        QuoteLineItem productEdit=[SELECT Id, QuoteId FROM QuoteLineItem WHERE Quote.Name=:'Test' Limit 1];    
        Double valueDesc = 30.0;
        
        IMP_CotizadorProductosController.procesoDescuento(productEdit, valueDesc);
        Test.startTest();
        System.assert(IMP_CotizadorProductosController.procesoDescuento(productEdit, valueDesc) != null,'Products cannot be null');                
        Test.stopTest();
        
    }
    
}