force-app/main/default/objects/Account/fields/centro_suministrador__c.field-meta.xml
<CustomField>
    <fullName>centro_suministrador__c</fullName>
    <label>Centro Suministrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC01</fullName>
                <label>Acapulco</label>
            </value>
            <value>
                <fullName>CA01</fullName>
                <label>Cancún</label>
            </value>
            <value>
                <fullName>CH01</fullName>
                <label>Chihuahua</label>
            </value>
            <value>
                <fullName>CU01</fullName>
                <label>Culiacán</label>
            </value>
            <value>
                <fullName>CV01</fullName>
                <label>Cuernavaca</label>
            </value>
            <value>
                <fullName>ERMI</fullName>
                <label>Ermita</label>
            </value>
            <value>
                <fullName>GD01</fullName>
                <label>Guadalajara</label>
            </value>
            <value>
                <fullName>HE01</fullName>
                <label>Hermosillo</label>
            </value>
            <value>
                <fullName>IMPQ</fullName>
                <label>Imperquimia</label>
            </value>
            <value>
                <fullName>IMPV</fullName>
                <label>Imperquimia Ventas</label>
            </value>
            <value>
                <fullName>LE01</fullName>
                <label>León</label>
            </value>
            <value>
                <fullName>ME01</fullName>
                <label>Mérida</label>
            </value>
            <value>
                <fullName>ME02</fullName>
                <label>Mérida II</label>
            </value>
            <value>
                <fullName>MIXC</fullName>
                <label>Mixcoac</label>
            </value>
            <value>
                <fullName>MT01</fullName>
                <label>Monterrey</label>
            </value>
            <value>
                <fullName>PSUR</fullName>
                <label>Perisur</label>
            </value>
            <value>
                <fullName>QE01</fullName>
                <label>Querétaro</label>
            </value>
            <value>
                <fullName>RAZA</fullName>
                <label>La Raza</label>
            </value>
            <value>
                <fullName>RIVI</fullName>
                <label>Riviera</label>
            </value>
            <value>
                <fullName>SATE</fullName>
                <label>Satélite</label>
            </value>
            <value>
                <fullName>TJ01</fullName>
                <label>Tijuana</label>
            </value>
            <value>
                <fullName>VE01</fullName>
                <label>Veracruz</label>
            </value>
            <value>
                <fullName>VI01</fullName>
                <label>Villahermosa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/condiciones_de_pago__c.field-meta.xml
<CustomField>
    <fullName>condiciones_de_pago__c</fullName>
    <defaultValue>&quot;NT00&quot;</defaultValue>
    <label>Condiciones de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NT00</fullName>
                <label>Pagado a la recepcion</label>
            </value>
            <value>
                <fullName>NT08</fullName>
                <label>Vencimiento 08 dias</label>
            </value>
            <value>
                <fullName>NT15</fullName>
                <label>Vencimiento 15 dias</label>
            </value>
            <value>
                <fullName>NT20</fullName>
                <label>Vencimiento 20 dias</label>
            </value>
            <value>
                <fullName>NT30</fullName>
                <label>Vencimiento 30 dias</label>
            </value>
            <value>
                <fullName>NT45</fullName>
                <label>Vencimiento 45 dias</label>
            </value>
            <value>
                <fullName>NT60</fullName>
                <label>Vencimiento 60 dias</label>
            </value>
            <value>
                <fullName>NT90</fullName>
                <label>Vencimiento 90 dias</label>
            </value>
            <value>
                <fullName>NT120</fullName>
                <label>Vencimiento 120 dias</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Credito_Acumulado__c.field-meta.xml
<CustomField>
    <fullName>Credito_Acumulado__c</fullName>
    <label>Crédito Acumulado</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credito_Disponible__c.field-meta.xml
<CustomField>
    <fullName>Credito_Disponible__c</fullName>
    <description>Almacena el crédito del cliente para visualizarlo a nivel cuenta</description>
    <formula>LineaCredito__c - Credito_Acumulado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credito Disponible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/grupo__c.field-meta.xml
<CustomField>
    <fullName>grupo__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Distribuidor A</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Distribuidor B</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Distribuidor C</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidor D</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Contratistas A</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Contratistas B</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Contratistas C</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Multimarcas A</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Multimarcas B</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Multimarcas C</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Desarrollo de Negoci</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Aplicador A</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Contratistas Plus</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RFC__c.field-meta.xml
<CustomField>
    <fullName>RFC__c</fullName>
    <description>RFC del cliente, para persona física 12 dígitos y para moral 13</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ViaPago__c.field-meta.xml
<CustomField>
    <fullName>ViaPago__c</fullName>
    <label>Vía de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>via_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/TotalPedido__c.field-meta.xml
<CustomField>
    <fullName>TotalPedido__c</fullName>
    <description>Almacena el total del pedido</description>
    <label>Total de Pedido</label>
    <summarizedField>OrderItem.PrecioTotal__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/ViaPago__c.field-meta.xml
<CustomField>
    <fullName>ViaPago__c</fullName>
    <label>Vía de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>via_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>DescuentoSAP__c</fullName>
    <description>Campo usado para capturar el descuento de SAP</description>
    <label>Descuento SAP</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Lista_de_precios_SAP__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_precios_SAP__c</fullName>
    <label>Lista de precios SAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lista_de_precios_SAP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/centro_suministrador__c.field-meta.xml
<CustomField>
    <fullName>centro_suministrador__c</fullName>
    <label>Centro Suministrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/sku__c.field-meta.xml
<CustomField>
    <fullName>sku__c</fullName>
    <label>SKU</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lista_de_precios_SAP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <masterLabel>Lista de precios SAP</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/via_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>C</fullName>
        <label>Cheque</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>Deposito</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>Efectivo</label>
    </customValue>
    <customValue>
        <fullName>F</fullName>
        <label>Tarjeta de crédito</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Cheque Prod IQ</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>Tarjeta de Débito</label>
    </customValue>
    <customValue>
        <fullName>I</fullName>
        <label>Nota de Credito</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Por Definir</label>
    </customValue>
    <customValue>
        <fullName>T</fullName>
        <label>Transferencia Bancaria</label>
    </customValue>
    <masterLabel>Via de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_EnvioPedidoSAP_tst.cls
/************************************************************************
Name: IMP_EnvioPedidoSAP_tst
Copyright © 2022 Salesforce
========================================================================
Purpose:
Test del controlador IMP_EnvioPedidoSAP
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      rotrejo@ts4.mx    11/04/2022     INITIAL        DEV CSR:
************************************************************************/
@isTest
public without sharing class IMP_EnvioPedidoSAP_tst {
    
    /*******************************************************************
    Purpose: Inserta datos de prueba
    Information about changes (versions) []:
    ********************************************************************/
    @testSetup static void inicializarDatos()
    {
        List<PricebookEntry> entradasPrecios = new  List<PricebookEntry>();
        List<PricebookEntry> entradasPreciosEstandar = new  List<PricebookEntry>();
        List<Product2> listProds = new  List<Product2>();
        for(Integer i = 1 ; i<= 20 ; i++){
            listProds.add(new Product2(Name='GUARDQUIM POLI RA 28, 18LT z'+i, ProductCode='1000010'+i, Family='2200 - MATIX', 
                                       CurrencyIsoCode='USD', sku__c =10000686+i));
        }
        insert listProds;
        
        Pricebook2  listaPrecios= new Pricebook2(Name='MIXC-Mostrador',CurrencyIsoCode='MXN',  Description ='Mixcoac',
                                                 Sucursal__c='MIXC',Lista_de_precios_SAP__c='03');
        insert listaPrecios;
        
        Pricebook2 pricebook= new Pricebook2();
        pricebook.Id=Test.getStandardPricebookId();
        update pricebook;
        
        for(Product2 prod : [SELECT Id FROM Product2]){
            entradasPreciosEstandar.add(new PricebookEntry(Product2Id=prod.Id,Pricebook2Id=pricebook.Id,UnitPrice=0));
        }
        insert entradasPreciosEstandar;
        for(Product2 prod : [SELECT Id FROM Product2]){
            entradasPrecios.add(new PricebookEntry(Pricebook2Id=listaPrecios.Id,Product2Id=prod.Id,
                                                   CurrencyIsoCode='MXN',IsActive=true,
                                                   UnitPrice = Integer.valueof((Math.random() * 1000))));
        }
        insert entradasPrecios;
        
        
        Account cuenta = new Account();
        cuenta.name = 'Cuenta Prueba';
        cuenta.RFC__c = '123456789101';
        cuenta.CurrencyIsoCode = 'MXN';
        cuenta.Phone='+52 7225398962';
        cuenta.centro_suministrador__c = 'AC01';
        cuenta.clave_delcanal__c = '04';
        cuenta.grupo__c = '01';
        insert cuenta;
        
        Order pedido = new Order(Pricebook2Id=listaPrecios.Id,AccountId=cuenta.Id,condiciones_de_pago__c='NT00',EffectiveDate= Date.today(), Status='Draft');
        insert pedido;
        List<Orderitem> orderItem = new  List<Orderitem>();
        for(PricebookEntry entradaPrecio : [SELECT Id,Product2Id FROM PricebookEntry WHERE Pricebook2Id=:listaPrecios.Id]){
            orderItem.add(new OrderItem (OrderId=pedido.Id,Quantity=100,UnitPrice=1200.7,DescuentoSAP__c=30,IMP_DescuentoPromo__c= 50, PricebookEntryId=entradaPrecio.Id));
        }
        insert orderItem;
    }
    
    /*******************************************************************
    Purpose: Covertura de la clase IMP_PedidoSAPController al metodo enviarPedioSAP
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void enviarPedioSAPTest()
    {
        Order pedido=[SELECT Id,Ordernumber,Pricebook2Id,Account.clave_delcanal__c, EffectiveDate,TotalAmount,Account.Credito_Disponible__c,Account.Credito_Acumulado__c ,TotalPedido__c, Account.Name,Account.id_de_sap__c,ViaPago__c,Pricebook2.Sucursal__c,
                      Pricebook2.Lista_de_precios_SAP__c FROM Order];
        IMP_EnvioPedidoSAP respuesta = new  IMP_EnvioPedidoSAP();
        respuesta.E_VBELN='100001';
        String body=JSON.serialize(respuesta);        
        
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        IMP_EnvioPedidoSAP.Wrapper respuestaEnvio =  IMP_PedidoSAPController.enviarPedioSAP(pedido);
        System.assertEquals('SUCCESS', respuestaEnvio.status,'ok');
        Test.stopTest();
    }
    
    /*******************************************************************
    Purpose: Covertura de la clase IMP_PedidoSAPController al metodo enviarPedioSAP
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void enviarPedioSAPError()
    {
        Order pedido=[SELECT Id,Ordernumber,Pricebook2Id,Account.clave_delcanal__c ,EffectiveDate,TotalAmount,Account.Credito_Disponible__c,Account.Credito_Acumulado__c ,TotalPedido__c, Account.Name,Account.id_de_sap__c,ViaPago__c,Pricebook2.Sucursal__c,
                      Pricebook2.Lista_de_precios_SAP__c FROM Order];
        IMP_EnvioPedidoSAP respuesta = new  IMP_EnvioPedidoSAP();
        respuesta.E_VBELN='';
        respuesta.E_TEXT='Error en el pedido';
        String body=JSON.serialize(respuesta);        
        
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        IMP_EnvioPedidoSAP.Wrapper respuestaEnvio = IMP_PedidoSAPController.enviarPedioSAP(pedido);
        System.assertEquals('Error en el pedido', respuestaEnvio.mensaje,'ok');
        Test.stopTest();
    }
    
    /*******************************************************************
    Purpose: Covertura de la clase IMP_PedidoSAPController al metodo getPedido
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void getOrderTest()
    {
        Order pedido=[SELECT Id,Ordernumber,Pricebook2Id, EffectiveDate,TotalAmount,Account.Credito_Disponible__c,Account.Credito_Acumulado__c ,TotalPedido__c, Account.Name,Account.id_de_sap__c,ViaPago__c,Pricebook2.Sucursal__c,
                      Pricebook2.Lista_de_precios_SAP__c FROM Order];
        IMP_EnvioPedidoSAP respuesta = new  IMP_EnvioPedidoSAP();
        respuesta.E_VBELN='';
        respuesta.E_TEXT='Error en el pedido';
        String body=JSON.serialize(respuesta);        
        
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        System.assertEquals('CUENTA PRUEBA', pedido.Account.Name,'ok');
        Test.stopTest();
    }
    
    /*******************************************************************
    Purpose: Covertura de la clase IMP_PedidoSAPController al metodo deleteOrderItem
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void deleteOrderItemTest()
    {
        Order pedido=[SELECT Id,Ordernumber,Pricebook2Id, EffectiveDate,TotalAmount,Account.Credito_Disponible__c,Account.Credito_Acumulado__c ,TotalPedido__c, Account.Name,Account.id_de_sap__c,ViaPago__c,Pricebook2.Sucursal__c,
                      Pricebook2.Lista_de_precios_SAP__c FROM Order];
        OrderItem prodPedido=[SELECT Id FROM OrderItem WHERE Orderid=:pedido.Id Limit 1];
        IMP_EnvioPedidoSAP respuesta = new  IMP_EnvioPedidoSAP();
        respuesta.E_VBELN='';
        respuesta.E_TEXT='Error en el pedido';
        String body=JSON.serialize(respuesta);        
        
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        IMP_PedidoSAPController.deleteOrderItem(prodPedido.Id);
        System.assertEquals(19, [SELECT id FROM OrderItem].Size(),'ok');
        Test.stopTest();
    }
    
    /*******************************************************************
    Purpose: Covertura de la clase IMP_PedidoSAPController al metodo getDatosPedido
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void getDatosPedidoTest()
    {
        List<IMP_InventarioManager.cls_ZINVENTARIOS> listProd= new List<IMP_InventarioManager.cls_ZINVENTARIOS>();
        IMP_InventarioManager respuesta = new IMP_InventarioManager();
        Order pedido=[SELECT Id,Ordernumber,Pricebook2Id, EffectiveDate,TotalAmount,Account.Credito_Disponible__c,Account.Credito_Acumulado__c ,TotalPedido__c, Account.Name,Account.id_de_sap__c,ViaPago__c,Pricebook2.Sucursal__c,
                      Pricebook2.Lista_de_precios_SAP__c FROM Order];
        
        IMP_PedidoSAPController.Wrapper newWrapperError = IMP_PedidoSAPController.getDatosPedido(pedido.Id);
        for(Product2 prod : [SELECT Id, productCode FROM Product2]){
            IMP_InventarioManager.cls_ZINVENTARIOS material= new IMP_InventarioManager.cls_ZINVENTARIOS();
            material.CHARG='0000092273';
            material.CLABS=Integer.valueof((Math.random() * 1000));
            material.HSDAT='2021-08-12';
            material.MATNR=prod.ProductCode; 
            listProd.add(material);
        }
      
        respuesta.ZINVENTARIOS=listProd;
        String body=JSON.serialize(respuesta);    
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        IMP_PedidoSAPController.Wrapper newWrapper = IMP_PedidoSAPController.getDatosPedido(pedido.Id);
        System.assertEquals(true, newWrapper.codigo == 'SUCCESS','ok');
        Test.stopTest();
    }
}