force-app/main/default/objects/Account/fields/centro_suministrador__c.field-meta.xml
<CustomField>
    <fullName>centro_suministrador__c</fullName>
    <label>Centro Suministrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC01</fullName>
                <label>Acapulco</label>
            </value>
            <value>
                <fullName>CA01</fullName>
                <label>Cancún</label>
            </value>
            <value>
                <fullName>CH01</fullName>
                <label>Chihuahua</label>
            </value>
            <value>
                <fullName>CU01</fullName>
                <label>Culiacán</label>
            </value>
            <value>
                <fullName>CV01</fullName>
                <label>Cuernavaca</label>
            </value>
            <value>
                <fullName>ERMI</fullName>
                <label>Ermita</label>
            </value>
            <value>
                <fullName>GD01</fullName>
                <label>Guadalajara</label>
            </value>
            <value>
                <fullName>HE01</fullName>
                <label>Hermosillo</label>
            </value>
            <value>
                <fullName>IMPQ</fullName>
                <label>Imperquimia</label>
            </value>
            <value>
                <fullName>IMPV</fullName>
                <label>Imperquimia Ventas</label>
            </value>
            <value>
                <fullName>LE01</fullName>
                <label>León</label>
            </value>
            <value>
                <fullName>ME01</fullName>
                <label>Mérida</label>
            </value>
            <value>
                <fullName>ME02</fullName>
                <label>Mérida II</label>
            </value>
            <value>
                <fullName>MIXC</fullName>
                <label>Mixcoac</label>
            </value>
            <value>
                <fullName>MT01</fullName>
                <label>Monterrey</label>
            </value>
            <value>
                <fullName>PSUR</fullName>
                <label>Perisur</label>
            </value>
            <value>
                <fullName>QE01</fullName>
                <label>Querétaro</label>
            </value>
            <value>
                <fullName>RAZA</fullName>
                <label>La Raza</label>
            </value>
            <value>
                <fullName>RIVI</fullName>
                <label>Riviera</label>
            </value>
            <value>
                <fullName>SATE</fullName>
                <label>Satélite</label>
            </value>
            <value>
                <fullName>TJ01</fullName>
                <label>Tijuana</label>
            </value>
            <value>
                <fullName>VE01</fullName>
                <label>Veracruz</label>
            </value>
            <value>
                <fullName>VI01</fullName>
                <label>Villahermosa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>Sujeta a aprobación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/grupo__c.field-meta.xml
<CustomField>
    <fullName>grupo__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Distribuidor A</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Distribuidor B</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Distribuidor C</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidor D</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Contratistas A</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Contratistas B</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Contratistas C</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Multimarcas A</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Multimarcas B</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Multimarcas C</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Desarrollo de Negoci</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Aplicador A</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Contratistas Plus</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RFC__c.field-meta.xml
<CustomField>
    <fullName>RFC__c</fullName>
    <description>RFC del cliente, para persona física 12 dígitos y para moral 13</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Muestras__c/Muestras__c.object-meta.xml
<CustomObject>
    <label>Muestra</label>
    <nameField>
        <label>Nombre de Muestra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Muestras</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Muestras__c/fields/Lista_de_precios_del__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_precios_del__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista de precios</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Muestras</relationshipLabel>
    <relationshipName>Muestras_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Muestras__c/fields/Producto_del__c.field-meta.xml
<CustomField>
    <fullName>Producto_del__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Muestras</relationshipLabel>
    <relationshipName>Muestras_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Muestras__c/fields/Solicitud_de_muestra_del__c.field-meta.xml
<CustomField>
    <fullName>Solicitud_de_muestra_del__c</fullName>
    <label>Solicitud de muestra</label>
    <referenceTo>SolicitudMuestra__c</referenceTo>
    <relationshipLabel>Muestras</relationshipLabel>
    <relationshipName>Muestras_del</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <displayFormat>OP-{000000}</displayFormat>
    <label># Oportunidad</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Oportunidad.recordType-meta.xml
<RecordType>
    <fullName>Oportunidad</fullName>
    <active>true</active>
    <businessProcess>Oportunidad</businessProcess>
    <description>Estandar</description>
    <label>Oportunidad</label>
</RecordType>

force-app/main/default/objects/Product2/fields/centro_suministrador__c.field-meta.xml
<CustomField>
    <fullName>centro_suministrador__c</fullName>
    <label>Centro Suministrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Grupo_de_Materiales__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Materiales__c</fullName>
    <label>Grupo de Materiales</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_de_materiales</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SolicitudMuestra__c/SolicitudMuestra__c.object-meta.xml
<CustomObject>
    <label>Solicitud de muestra</label>
    <nameField>
        <label>Nombre de Solicitud</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitudes de muestras</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SolicitudMuestra__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Preparación de Muestra</fullName>
            </value>
            <value>
                <fullName>Muestra en Almacén</fullName>
            </value>
            <value>
                <fullName>Entregado al Ejecutivo</fullName>
            </value>
            <value>
                <fullName>Muestra entregada</fullName>
                <color>#009900</color>
                <label>Muestra entregada</label>
            </value>
            <value>
                <fullName>Muestra no entregada</fullName>
                <color>#FF0000</color>
                <label>Muestra no entregada</label>
            </value>
            <value>
                <fullName>Muestra en Almacén Planta</fullName>
                <isActive>false</isActive>
                <label>Muestra en Almacén Planta</label>
            </value>
            <value>
                <fullName>Pendiente de recolección</fullName>
                <isActive>false</isActive>
                <label>Pendiente de recolección</label>
            </value>
            <value>
                <fullName>Pendiente de autorización</fullName>
                <isActive>false</isActive>
                <label>Solicitar autorización</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SolicitudMuestra__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Muestras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SolicitudMuestra__c/fields/tipo_muestra__c.field-meta.xml
<CustomField>
    <fullName>tipo_muestra__c</fullName>
    <label>Tipo de Muestra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Producto de Linea</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_de_materiales.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Lineas Generales</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Lineas Mayoristas</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Lineas Populares</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Commodity</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Especiales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Ultra Comodity</label>
    </customValue>
    <masterLabel>Grupo de materiales</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MuestraTrigger_Test.cls
/************************************************************************
Name: MuestraTrigger_Test
Copyright © 2022 Salesforce
========================================================================
Purpose:
Test class from the trigger Quote.
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      dmarcos@ts4.mx    15/02/2022     INITIAL        DEV CSR:
************************************************************************/
@isTest
public without sharing class MuestraTrigger_Test {

/******************************************************************* 
    Purpose: Inserts all information to run the class method.
    Information about changes (versions):
    ********************************************************************/    
    @testSetup static void setup(){
        
        Account cuenta = new Account();
        cuenta.name = 'Cuenta Prueba';
        cuenta.RFC__c = '0011MYA1';
        cuenta.CurrencyIsoCode = 'MXN';
        cuenta.centro_suministrador__c = 'AC01';
        cuenta.clave_delcanal__c = '04';
        cuenta.grupo__c = '01';
        insert cuenta;
        
        RecordType recordTypeOportunidad=[SELECT Name, DeveloperName,sobjecttype, Id FROM RecordType where sobjectType='Opportunity' and DeveloperName='Oportunidad'];
        
        Opportunity oportunidad = new Opportunity();
        oportunidad.AccountId = cuenta.Id;
        oportunidad.Name = 'Oportunidad Test';
        oportunidad.StageName = 'Plan';
        oportunidad.CurrencyIsoCode = 'MXN';
        oportunidad.CloseDate = Date.today().addDays(30);
        oportunidad.RecordTypeId=recordTypeOportunidad.Id;
        oportunidad.Amount=3850.6;
        oportunidad.Probability=100; 
        insert oportunidad;
        
        Product2 prod =new Product2();
        prod.Name = 'IMPERMEABILIZANTE';
        prod.ProductCode='IMP-12345';
        prod.Family = 'Naya';
        prod.Description = '';
        prod.IsActive = true;
        prod.CurrencyIsoCode='MXN';
        prod.Grupo_de_Materiales__c ='03';            
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId(); 

        PricebookEntry pbeSt = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            IsActive = true,
            CurrencyIsoCode='MXN',
            UnitPrice = 150,
            UseStandardPrice=false
        );
        
        insert pbeSt; 
        
        SolicitudMuestra__c solicitudMuestra = new SolicitudMuestra__c(
        Name = 'Solicitud prueba',
        Estatus__c ='Nuevo',
        tipo_muestra__c ='Desarrollo',
        Oportunidad__c = oportunidad.Id
        );
        
        insert solicitudMuestra;
        
        Muestras__c muestras = new Muestras__c (
        Name ='Muestra test',
        Lista_de_precios_del__c = pricebookId,
        Producto_del__c = prod.Id,
        Solicitud_de_muestra_del__c  = solicitudMuestra.Id
        );
        
        insert muestras;
        
        
    }
/******************************************************************* 
Purpose: Test class method to consult the PricebookEntry in relation to the Product and Price list of the sample.
Parameters:PricebookEntry pricebook , Id cotizacion.
Returns: 
Throws :
Information about changes (versions)
********************************************************************/   
    @isTest public static void crearMuestra(){
        Muestras__c muestra = [SELECT Id FROM Muestras__c WHERE Name ='Muestra test'];
    }
    

}