force-app/main/default/objects/Account/fields/centro_suministrador__c.field-meta.xml
<CustomField>
    <fullName>centro_suministrador__c</fullName>
    <label>Centro Suministrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC01</fullName>
                <label>Acapulco</label>
            </value>
            <value>
                <fullName>CA01</fullName>
                <label>Cancún</label>
            </value>
            <value>
                <fullName>CH01</fullName>
                <label>Chihuahua</label>
            </value>
            <value>
                <fullName>CU01</fullName>
                <label>Culiacán</label>
            </value>
            <value>
                <fullName>CV01</fullName>
                <label>Cuernavaca</label>
            </value>
            <value>
                <fullName>ERMI</fullName>
                <label>Ermita</label>
            </value>
            <value>
                <fullName>GD01</fullName>
                <label>Guadalajara</label>
            </value>
            <value>
                <fullName>HE01</fullName>
                <label>Hermosillo</label>
            </value>
            <value>
                <fullName>IMPQ</fullName>
                <label>Imperquimia</label>
            </value>
            <value>
                <fullName>IMPV</fullName>
                <label>Imperquimia Ventas</label>
            </value>
            <value>
                <fullName>LE01</fullName>
                <label>León</label>
            </value>
            <value>
                <fullName>ME01</fullName>
                <label>Mérida</label>
            </value>
            <value>
                <fullName>ME02</fullName>
                <label>Mérida II</label>
            </value>
            <value>
                <fullName>MIXC</fullName>
                <label>Mixcoac</label>
            </value>
            <value>
                <fullName>MT01</fullName>
                <label>Monterrey</label>
            </value>
            <value>
                <fullName>PSUR</fullName>
                <label>Perisur</label>
            </value>
            <value>
                <fullName>QE01</fullName>
                <label>Querétaro</label>
            </value>
            <value>
                <fullName>RAZA</fullName>
                <label>La Raza</label>
            </value>
            <value>
                <fullName>RIVI</fullName>
                <label>Riviera</label>
            </value>
            <value>
                <fullName>SATE</fullName>
                <label>Satélite</label>
            </value>
            <value>
                <fullName>TJ01</fullName>
                <label>Tijuana</label>
            </value>
            <value>
                <fullName>VE01</fullName>
                <label>Veracruz</label>
            </value>
            <value>
                <fullName>VI01</fullName>
                <label>Villahermosa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Credito_Acumulado__c.field-meta.xml
<CustomField>
    <fullName>Credito_Acumulado__c</fullName>
    <label>Crédito Acumulado</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/grupo__c.field-meta.xml
<CustomField>
    <fullName>grupo__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Distribuidor A</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Distribuidor B</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Distribuidor C</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidor D</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Contratistas A</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Contratistas B</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Contratistas C</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Multimarcas A</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Multimarcas B</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Multimarcas C</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Desarrollo de Negoci</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Aplicador A</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Contratistas Plus</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_Documentos30dias__c.field-meta.xml
<CustomField>
    <fullName>IMP_Documentos30dias__c</fullName>
    <label>Total vencido a 30 días</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_Documentos60dias__c.field-meta.xml
<CustomField>
    <fullName>IMP_Documentos60dias__c</fullName>
    <label>Total vencido a 60 días</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_Documentos90dias__c.field-meta.xml
<CustomField>
    <fullName>IMP_Documentos90dias__c</fullName>
    <label>Total vencido a 90 días</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_Saldo30__c.field-meta.xml
<CustomField>
    <fullName>IMP_Saldo30__c</fullName>
    <description>Captura el valor del saldo a 30 días mediante el servicio de  consulta de crédito</description>
    <label>Saldo a 30 días</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_Saldo60__c.field-meta.xml
<CustomField>
    <fullName>IMP_Saldo60__c</fullName>
    <description>Captura el valor del saldo a 60 días mediante el servicio de  consulta de crédito</description>
    <label>Saldo a 60 días</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_Saldo90__c.field-meta.xml
<CustomField>
    <fullName>IMP_Saldo90__c</fullName>
    <description>Captura el valor del saldo a 90 días mediante el servicio de  consulta de crédito</description>
    <label>Saldo a 90 días</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_SaldoComprometido__c.field-meta.xml
<CustomField>
    <fullName>IMP_SaldoComprometido__c</fullName>
    <description>Representa el saldo comprometido del cliente</description>
    <label>Saldo comprometido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_SaldoVencido__c.field-meta.xml
<CustomField>
    <fullName>IMP_SaldoVencido__c</fullName>
    <label>Saldo vencido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_TotalEstadosCuenta__c.field-meta.xml
<CustomField>
    <fullName>IMP_TotalEstadosCuenta__c</fullName>
    <label>Saldo Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_TotalFacturas__c.field-meta.xml
<CustomField>
    <fullName>IMP_TotalFacturas__c</fullName>
    <label>Líneas totales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMP_TotalFacturasVencidas__c.field-meta.xml
<CustomField>
    <fullName>IMP_TotalFacturasVencidas__c</fullName>
    <label>Número de documentos saldo vencido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/LineaCredito__c.field-meta.xml
<CustomField>
    <fullName>LineaCredito__c</fullName>
    <label>Línea de Crédito</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/RFC__c.field-meta.xml
<CustomField>
    <fullName>RFC__c</fullName>
    <description>RFC del cliente, para persona física 12 dígitos y para moral 13</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EstadoCuenta__c/EstadoCuenta__c.object-meta.xml
<CustomObject>
    <description>Este objeto almacena el detalle de los estados de cuenta de los clientes.</description>
    <label>Estado de cuenta</label>
    <nameField>
        <label>Número de documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados de cuenta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EstadoCuenta__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <description>Este campo genera la relación entre cuenta y Estado de cuenta</description>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Estados de cuenta</relationshipLabel>
    <relationshipName>Estados_de_cuenta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EstadoCuenta__c/fields/IMP_LlaveExclusiva__c.field-meta.xml
<CustomField>
    <fullName>IMP_LlaveExclusiva__c</fullName>
    <externalId>true</externalId>
    <label>Llave exclusiva</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EstadoCuenta__c/fields/Prefijo__c.field-meta.xml
<CustomField>
    <fullName>Prefijo__c</fullName>
    <label>Prefijo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EstadoCuenta__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <description>Este campo almacena el valor del estado de cuenta</description>
    <label>Saldo total de factura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/IMP_ConsultaCredito_tst.cls
/************************************************************************
Name: IMP_ConsultaCredito_tst
Copyright © 2022 Salesforce
========================================================================
Purpose: Class used to test the class IMP_ConsultaCredito
Controller
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
1.0      rotrejo@ts4.mx    22/03/2022     INITIAL        DEV CSR:
************************************************************************/

@isTest
public without sharing class IMP_ConsultaCredito_tst {
    
    /*******************************************************************
    Purpose: Inserta 1 cuenta de prueba.
    Information about changes (versions) []:
    ********************************************************************/
    @testSetup static void inicializarDatos()
    {
        Account cuenta = new Account();
        cuenta.name = 'Cuenta Prueba';
        cuenta.RFC__c = '123456789101';
        cuenta.CurrencyIsoCode = 'MXN';
        cuenta.centro_suministrador__c = 'AC01';
        cuenta.clave_delcanal__c = '04';
        cuenta.grupo__c = '01';
        cuenta.id_de_sap__c='10001';
        cuenta.Credito_Acumulado__c = 0;
        cuenta.IMP_TotalEstadosCuenta__c = 0;
        cuenta.IMP_SaldoVencido__c = 0;
        cuenta.IMP_SaldoComprometido__c = 0;
        cuenta.LineaCredito__c = 0;
        cuenta.IMP_Saldo30__c = 0;
        cuenta.IMP_Saldo60__c = 0;
        cuenta.IMP_Saldo90__c = 0;
        cuenta.IMP_Documentos30dias__c = 0;
        cuenta.IMP_Documentos60dias__c = 0;
        cuenta.IMP_Documentos90dias__c = 0;
        cuenta.IMP_TotalFacturas__c = 0;
        cuenta.IMP_TotalFacturasVencidas__c = 0;
        insert cuenta;
        
        EstadoCuenta__c edoCuenta = new EstadoCuenta__c();
        edoCuenta.Cuenta__c = cuenta.Id;
        edoCuenta.Prefijo__c ='RV';
        edoCuenta.Name = '1234';
        edoCuenta.Valor__c = 2300;
        edoCuenta.IMP_LlaveExclusiva__c= '1234';
        insert edoCuenta;
        
    }
    
    /*******************************************************************
    Purpose: Covertura del método updateCredito.
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void updateCreditoTest()
    {
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok','',null));
        Test.startTest();
        IMP_ConsultaCredito.updateCredito('10001', 30000);  
        Test.stopTest(); 
    }
  
    /*******************************************************************
    Purpose: Covertura del método IMP_ConsultaCredito/getCredito.
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void getCreditoTest()
    {
        IMP_ConsultaCredito credito = new IMP_ConsultaCredito();
        List<IMP_ConsultaCredito.cls_credito> creditoRespuesta = new List<IMP_ConsultaCredito.cls_credito>();
        IMP_ConsultaCredito.cls_credito newCredito = new IMP_ConsultaCredito.cls_credito();
        newCredito.KUNNR='10001';
        newCredito.KLIMK=10000;
        newCredito.KLIME=3000;
        creditoRespuesta.add(newCredito);
        credito.credito=creditoRespuesta;
        String body = JSON.serialize(credito);
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        IMP_ConsultaCredito.getCredito('10001');  
        Test.stopTest();
    }
    /*******************************************************************
    Purpose: Covertura del método consultaIdSAP.
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void consultaIdSAPTest()
    {
        Test.startTest();
        Account cuenta=[SELECT Id FROM Account];
        cuenta = IMP_ConsultaCredito.consultaIdSAP(cuenta.Id);
        Test.stopTest();
        
    }
    
    /*******************************************************************
    Purpose: Covertura del método updateCreditoCuentaTest.
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void updateCreditoCuentaTest()
    {
        IMP_ConsultaCredito credito = new IMP_ConsultaCredito();
        List<IMP_ConsultaCredito.cls_credito> creditoRespuesta = new List<IMP_ConsultaCredito.cls_credito>();
        IMP_ConsultaCredito.cls_credito newCredito = new IMP_ConsultaCredito.cls_credito();
        newCredito.KUNNR='10001';
        newCredito.KLIMK=10000;
        newCredito.KLIME=3000;
        creditoRespuesta.add(newCredito);
        credito.credito=creditoRespuesta;
        String body = JSON.serialize(credito);
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        IMP_ConsultaCredito.updateCreditoCuenta('10001');  
        Test.stopTest();
    }
    
    /*******************************************************************
    Purpose: Covertura del método updateCreditoCuenta.
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void updateCreditoCuentaError()
    {
        delete [SELECT Id FROM Account];
        IMP_ConsultaCredito credito = new IMP_ConsultaCredito();
        List<IMP_ConsultaCredito.cls_credito> creditoRespuesta = new List<IMP_ConsultaCredito.cls_credito>();
        IMP_ConsultaCredito.cls_credito newCredito = new IMP_ConsultaCredito.cls_credito();
        newCredito.KUNNR='10001';
        newCredito.KLIMK=10000;
        newCredito.KLIME=3000;
        creditoRespuesta.add(newCredito);
        credito.credito=creditoRespuesta;
        String body = JSON.serialize(credito);
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        IMP_ConsultaCredito.updateCreditoCuenta('10001');  
        Test.stopTest();
    }
    
     @isTest
    public static void updateEdoCuentaTest()
    {
        IMP_ConsultaCredito newCredito = new IMP_ConsultaCredito();
        List<IMP_ConsultaCredito.cls_IT_DOCUMENTOS> documentosRespuesta = new List<IMP_ConsultaCredito.cls_IT_DOCUMENTOS>();
        IMP_ConsultaCredito.cls_IT_DOCUMENTOS newDocumentos = new IMP_ConsultaCredito.cls_IT_DOCUMENTOS();
        newDocumentos.DATE_OFF = Date.today();
        newDocumentos.DOC_NO='12345';
        newDocumentos.DOC_TYPE ='RV';
        newDocumentos.LC_AMOUNT =5400;
        documentosRespuesta.add(newDocumentos);
        newCredito.IT_DOCUMENTOS = documentosRespuesta;
        newCredito.KUNNR='10001';
        newCredito.BUKRS='IMQ';
        newCredito.SALDO_TOTAL =23000;
        newCredito.V_COMPROMETIDO =23000;
        newCredito.V_LIMITE_CREDITO =23000;
        newCredito.V_SALDO_30_DIAS =23000;
        newCredito.V_SALDO_60_DIAS =23000;
        newCredito.V_SALDO_90_DIAS =23000;
        newCredito.V_TOTAL_30_DIAS =23000;
        newCredito.V_TOTAL_60_DIAS =23000;
        newCredito.V_TOTAL_90_DIAS =23000;
        newCredito.V_TOTAL_ACTUAL_LINE =23000;
        newCredito.V_TOTAL_LINE =23000;
        newCredito.V_TOTAL_VENCID_LINE =23000;
        newCredito.SALDO_VENCIDO =23000;
		Account cuenta=[SELECT Id FROM Account limit 1];
        String body = JSON.serialize(newCredito);
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(201,'Ok',body,null));
        Test.startTest();
        IMP_ConsultaCredito.updateEdoCuenta('10001',cuenta.Id);  
        Test.stopTest();
    }     
    
}