force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para almacenar las facturas del pedido</description>
    <label>Factura</label>
    <nameField>
        <label>Número de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/IMP_CanalVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_CanalVentas__c</fullName>
    <label>Canal de ventas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/IMP_FechaFactura__c.field-meta.xml
<CustomField>
    <fullName>IMP_FechaFactura__c</fullName>
    <description>Fecha de creación del registro de la factura SAP.</description>
    <label>Fecha de factura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/IMP_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>IMP_Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Asocia una factura a un vendedor</description>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Monto_Factura__c.field-meta.xml
<CustomField>
    <fullName>Monto_Factura__c</fullName>
    <formula>IF(  OR(IMP_ClaseFactura__c  = &quot;S1&quot;,IMP_ClaseFactura__c  = &quot;S3&quot;,IMP_ClaseFactura__c  = &quot;G2&quot;,IMP_ClaseFactura__c  = &quot;YBRE&quot;), IMP_MontoFactura__c  * -1, IMP_MontoFactura__c  * 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monto Factura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Importe__c.field-meta.xml
<CustomField>
    <fullName>Importe__c</fullName>
    <label>Importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/factura__c.field-meta.xml
<CustomField>
    <fullName>factura__c</fullName>
    <label>Número de Factura</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_CanalVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_CanalVentas__c</fullName>
    <label>Organización de ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Presupuesto__c/Presupuesto__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para almacenar el presupuesto de venta del usuario por mes y canal de venta.</description>
    <label>Forecast</label>
    <nameField>
        <label>Nombre de Presupuesto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecast</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Presupuesto__c/fields/IMP_CanalVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_CanalVentas__c</fullName>
    <label>Canal de ventas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Presupuesto__c/fields/IMP_FacturadoMes__c.field-meta.xml
<CustomField>
    <fullName>IMP_FacturadoMes__c</fullName>
    <label>Facturado en el mes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Presupuesto__c/fields/IMP_Fecha__c.field-meta.xml
<CustomField>
    <fullName>IMP_Fecha__c</fullName>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Presupuesto__c/fields/IMP_TotalOportunidadesPorCerrar__c.field-meta.xml
<CustomField>
    <fullName>IMP_TotalOportunidadesPorCerrar__c</fullName>
    <label>Total de oportunidades por cerrar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Presupuesto__c/fields/IMP_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>IMP_Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Presupuestos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IMP_HandleFacturas.cls
/************************************************************************
Name: IMP_HandleFacturas
Copyright © 2023 Salesforce
========================================================================
Purpose:
Obtiene lo montos faturados mensualmente
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
3.0      rotrejo@ts4.mx     26/05/2023     
************************************************************************/
public inherited sharing class IMP_HandleFacturas {

    /*******************************************************************
    Purpose: Obtiene las facturacion mensual de las facturas nuevas o modificadas
    Parameters: List<Factura__c> listFacts
    Returns: Order
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    public static void getMontos(List<Factura__c> listFacts){
        
        set<String> setCanales = new  set<String>();
        List<Date> setFechas = new  List<Date>();
        set<ID> setOwners = new  set<ID>();
        
        for(Factura__c factura:listFacts){
            setCanales.add(factura.IMP_CanalVentas__c);
            setFechas.add(factura.IMP_FechaFactura__c);
            setOwners.add(factura.IMP_Vendedor__c);
        }
        setFechas.sort();
        System.debug(setFechas.get(0));
        System.debug(setFechas.get(setFechas.size()-1));
        System.debug('CANALES '+setCanales);
        Date firstDayOfMonth =  Date.newInstance(setFechas.get(0).year(),setFechas.get(0).month() , 01);
        Date firstDayOfLastMonth = setFechas.get(setFechas.size()-1).toStartOfMonth();
        Date lastDayOfMonth = firstDayOfLastMonth.addDays(Date.daysInMonth(firstDayOfLastMonth.year(), firstDayOfLastMonth.month()) - 1);
        System.debug('First Date - '+ firstDayOfMonth);
        System.debug('Last Date - '+ lastDayOfMonth);
        
        Map<String,Decimal> mapReturn = new Map<String,Decimal>();
        for(Factura__c factura : [SELECT Id,Name,IMP_FechaFactura__c,IMP_CanalVentas__c,IMP_Vendedor__c,IMP_Vendedor__r.Name,Monto_Factura__c FROM Factura__c WHERE 
                                  IMP_CanalVentas__c IN: setCanales  AND IMP_FechaFactura__c>=:firstDayOfMonth AND 
                                  IMP_FechaFactura__c<=:lastDayOfMonth AND IMP_Vendedor__c IN :setOwners  AND IMP_Vendedor__c!= NULL]){
                                     System.debug(factura);
                                      String llave =factura.IMP_CanalVentas__c+'/'+factura.IMP_Vendedor__c+'/'+factura.IMP_FechaFactura__c.month()+'/'+factura.IMP_FechaFactura__c.year();
                                      if(!mapReturn.containsKey(llave)){
                                          mapReturn.put(llave,0);
                                      } 
                                      mapReturn.put(llave,mapReturn.get(llave)+factura.Monto_Factura__c );
                                  }
        
        Map<String,Presupuesto__c> mapPresupuestos = getPresupuestos(setCanales,firstDayOfMonth,lastDayOfMonth);
        Map<String,Decimal> mapOpps = getOpps(setOwners);
        System.debug(mapOpps);
        List<Presupuesto__c> listPresupuestos = new List<Presupuesto__c>();        
        for(String  key : mapReturn.keySet()){
            System.debug('KEY : '+ key+ '| MONTO: '+ mapReturn.get(key));
            List<String> split = key.split('/');
            String keyOpp = split.get(0)+'/'+split.get(1);
            if(mapPresupuestos.containsKey(key)){
                System.debug('PRESUPUESTO ENCONTRADO '+key );
                mapPresupuestos.get(key).IMP_FacturadoMes__c=mapReturn.get(key); 
                mapPresupuestos.get(key).IMP_TotalOportunidadesPorCerrar__c = mapOpps.containsKey(keyOpp) ?mapOpps.get(keyOpp):mapPresupuestos.get(key).IMP_TotalOportunidadesPorCerrar__c;
            }else{
                mapPresupuestos.put(key, new Presupuesto__c(
                    IMP_CanalVentas__c = split.get(0),
                    IMP_Vendedor__c  = split.get(1),
                    IMP_FacturadoMes__c=mapReturn.get(key), 
                    IMP_Fecha__c = Date.newInstance(Integer.valueOf(split.get(3)), Integer.valueOf(split.get(2)) , 1),
                    IMP_TotalOportunidadesPorCerrar__c = mapOpps.containsKey(keyOpp) ?mapOpps.get(keyOpp):0,
                    OwnerId =  split.get(1)
                ));
            }
        }
        System.debug(mapPresupuestos.values());
        upsert mapPresupuestos.values();
    }  
    
    /*******************************************************************
    Purpose: Obtiene las oportunidades actuales abiertas.
    Parameters: set<ID> ownersId
    Returns: Order
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    public static Map<String,Decimal> getOpps(set<ID> ownersId){
        Map<String,Decimal> mapOpps = new  Map<String,Decimal>();
        //Cuenta clave_delcanal__c 2 oppo
        try{
            
            for(Opportunity opp : [SELECT Id, CloseDate, AccountId, Account.clave_delcanal__c, OwnerId, Importe__c
                                   FROM Opportunity WHERE ownerId IN :ownersId AND StageName !=:'Ganada' AND StageName !=:'Perdida' AND CloseDate >=TODAY]){
                                       if(!mapOpps.containsKey(opp.Account.clave_delcanal__c+'/'+opp.ownerId)){
                                           mapOpps.put(opp.Account.clave_delcanal__c+'/'+opp.ownerId,0);
                                       } 
                                       mapOpps.put(opp.Account.clave_delcanal__c+'/'+opp.ownerId,mapOpps.get(opp.Account.clave_delcanal__c+'/'+opp.ownerId)+opp.Importe__c);
                                   }
        }catch(Exception exc){}
        return mapOpps;
    }
    
        /*******************************************************************
    Purpose: Obtiene los presupuestos dependiendo las fechas y el canal
    Parameters: Set<String> setCanales,Date firstDayOfMonth,Date lastDayOfMonth
    Returns: Order
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    public static Map<String,Presupuesto__c> getPresupuestos(Set<String> setCanales,Date firstDayOfMonth,Date lastDayOfMonth){
        
        Map<String,Presupuesto__c > mapPresupuesto= new  Map<String,Presupuesto__c >();
        
        try{
            for(Presupuesto__c presupuesto:[SELECT Id,IMP_CanalVentas__c,IMP_Vendedor__c,IMP_Fecha__c,IMP_TotalOportunidadesPorCerrar__c,
                                            IMP_FacturadoMes__c  FROM Presupuesto__c WHERE IMP_CanalVentas__c IN: setCanales
                                             AND IMP_Fecha__c>=:firstDayOfMonth AND  IMP_Fecha__c<=:lastDayOfMonth]){
                mapPresupuesto.put(presupuesto.IMP_CanalVentas__c+'/'+presupuesto.IMP_Vendedor__c+'/'+presupuesto.IMP_Fecha__c.month()+'/'+presupuesto.IMP_Fecha__c.year(), presupuesto);
            }
            
        }catch(Exception exc){}
        
        return mapPresupuesto;
    }
}