force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Credito_SAP__c.field-meta.xml
<CustomField>
    <fullName>Credito_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Seleccionado si el cliente tiene crédito SAP y falso si el crédito esta vencido</description>
    <label>Crédito SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RFC__c.field-meta.xml
<CustomField>
    <fullName>RFC__c</fullName>
    <description>RFC del cliente, para persona física 12 dígitos y para moral 13</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_persona__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_persona__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Marque es opción solo si la persona es física</inlineHelpText>
    <label>¿Es persona física?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/Integration_Logs__c.object-meta.xml
<CustomObject>
    <description>Se almacenan registros de errores de integración</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Integration Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IMP_CrearClienteSap_Test.cls
/************************************************************************
Name: IMP_CrearClienteSap_Test
Copyright © 2022 Salesforce
========================================================================
Purpose:
Test del controlador IMP_CrearClienteSap_CC
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      mvilchis@ts4.mx    11/04/2022     INITIAL        DEV CSR:
************************************************************************/
@isTest
public without sharing class IMP_CrearClienteSap_Test {
    /*******************************************************************
    Purpose: Inserta 1 cuenta de prueba.
    Information about changes (versions) []:
    ********************************************************************/
    @testSetup
    private static void testSetup() {
        Account acc = new Account();
        acc.Name='Test Test';
        acc.Tipo_de_persona__c=true;
        acc.RFC__c='AX091234ER5T6';
        acc.id_de_sap__c='2021';
        acc.clave_delcanal__c='07';
        acc.Credito_SAP__c=false;
        insert acc;
    }

    /*******************************************************************
    Purpose: Post de una cuenta con respuesta success.
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void postAccount() {
        Account cuenta=[SELECT Id FROM Account Where RFC__c='AX091234ER5T6' LIMIT 1];
        IMP_CrearClienteSap_CC returnWrapper = IMP_CrearClienteSap_CC.sapValidated(cuenta.Id);
        List<Id> lstAcc = new List<Id>{cuenta.Id};
        String token = '';
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(200, 'success', '{"E_CLIENTE": "0001036236","V_MSG": ""}', null));
        IMP_CrearClienteSap_CC.Wrapper response = IMP_CrearClienteSap_CC.postAccount(token, lstAcc);
        System.assertEquals('SUCCESS', response.status,'ok');
        Test.stopTest();
    }
    /*******************************************************************
    Purpose: Post de una cuenta con respuesta error.
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void postAccount2() {
        
        Account cuenta=[SELECT Id FROM Account Where RFC__c='AX091234ER5T6' LIMIT 1];
        List<Id> lstAcc = new List<Id>{cuenta.Id};
        String token = '';
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(200, 'success', '{"E_CLIENTE": "0001036236","V_MSG": " "}', null));
        IMP_CrearClienteSap_CC.Wrapper response = IMP_CrearClienteSap_CC.postAccount(token, lstAcc);
        System.assertEquals('ERROR', response.status,'ok');
        Test.stopTest();
    }
    /*******************************************************************
    Purpose: Post de cuenta con error.
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void postAccount1() {
        Account cuenta=[SELECT Id FROM Account Where RFC__c='AX091234ER5T6' LIMIT 1];
        List<Id> lstAcc = new List<Id>{cuenta.Id};
        String token = '';
        Test.startTest();
        IMP_CrearClienteSap_CC.postAccount(token, lstAcc);
        list<Integration_Logs__c> logs= [SELECT Id FROM Integration_Logs__c];
        System.assertEquals(1, logs.size(),'ok');
        Test.stopTest();
    }

    
    
    /*******************************************************************
    Purpose: Covertura del Trigger account_Trigger.
    Information about changes (versions) []:
    ********************************************************************/
    @isTest
    public static void triggerAccountTest() {
        Test.startTest();
        Account cuenta=[SELECT Id FROM Account Where RFC__c='AX091234ER5T6' LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new IMP_Mock(200, 'OK', '', null));
        cuenta.Credito_SAP__c=true;
        update cuenta;
        Test.stopTest();
       // System.assertEquals('2021', cuentaResponse.id_de_sap__c,'ok');
    }
    
}