force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/condiciones_de_pago__c.field-meta.xml
<CustomField>
    <fullName>condiciones_de_pago__c</fullName>
    <defaultValue>&quot;NT00&quot;</defaultValue>
    <label>Condiciones de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NT00</fullName>
                <label>Pagado a la recepcion</label>
            </value>
            <value>
                <fullName>NT08</fullName>
                <label>Vencimiento 08 dias</label>
            </value>
            <value>
                <fullName>NT15</fullName>
                <label>Vencimiento 15 dias</label>
            </value>
            <value>
                <fullName>NT20</fullName>
                <label>Vencimiento 20 dias</label>
            </value>
            <value>
                <fullName>NT30</fullName>
                <label>Vencimiento 30 dias</label>
            </value>
            <value>
                <fullName>NT45</fullName>
                <label>Vencimiento 45 dias</label>
            </value>
            <value>
                <fullName>NT60</fullName>
                <label>Vencimiento 60 dias</label>
            </value>
            <value>
                <fullName>NT90</fullName>
                <label>Vencimiento 90 dias</label>
            </value>
            <value>
                <fullName>NT120</fullName>
                <label>Vencimiento 120 dias</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/grupo__c.field-meta.xml
<CustomField>
    <fullName>grupo__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Distribuidor A</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Distribuidor B</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Distribuidor C</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidor D</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Contratistas A</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Contratistas B</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Contratistas C</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Multimarcas A</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Multimarcas B</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Multimarcas C</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Desarrollo de Negoci</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Aplicador A</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Contratistas Plus</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ViaPago__c.field-meta.xml
<CustomField>
    <fullName>ViaPago__c</fullName>
    <label>Vía de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>via_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Descuento__c/Descuento__c.object-meta.xml
<CustomObject>
    <label>Descuento</label>
    <nameField>
        <label>Nombre de Descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Descuento__c/fields/IMP_CanalVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_CanalVentas__c</fullName>
    <description>Canal de distribución que permite la entrega de la mercancía o prestación de servicios. Se debe enviar con clave SAP.</description>
    <label>Canal de ventas</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_NumeroCliente__c.field-meta.xml
<CustomField>
    <fullName>IMP_NumeroCliente__c</fullName>
    <description>Número de cliente registrado en SAP por el cual se debe filtrar la información a consultar.</description>
    <label>Número de cliente</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_OficinaVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_OficinaVentas__c</fullName>
    <label>Oficina de ventas</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/Integration_Logs__c.object-meta.xml
<CustomObject>
    <description>Se almacenan registros de errores de integración</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Integration Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Logs__c/fields/Body_JSON__c.field-meta.xml
<CustomField>
    <fullName>Body_JSON__c</fullName>
    <description>Json del Request que genero el error</description>
    <label>Body JSON</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/fields/Clase__c.field-meta.xml
<CustomField>
    <fullName>Clase__c</fullName>
    <description>Nombre de la clase de error</description>
    <label>Clase</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/fields/Linea__c.field-meta.xml
<CustomField>
    <fullName>Linea__c</fullName>
    <description>Línea en la que se genero el error</description>
    <label>Linea</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/fields/Mensaje_SFDC__c.field-meta.xml
<CustomField>
    <fullName>Mensaje_SFDC__c</fullName>
    <description>Exception de salesforce</description>
    <label>Mensaje SFDC</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Tipo de error</description>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CREACION_CLIENTES_SFDC</fullName>
            </value>
            <value>
                <fullName>CREACION_CLIENTES_SAP</fullName>
            </value>
            <value>
                <fullName>TOKEN_IIS</fullName>
            </value>
            <value>
                <fullName>CREAR_PEDIDO_SF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_CanalDistribucion__c.field-meta.xml
<CustomField>
    <fullName>IMP_CanalDistribucion__c</fullName>
    <label>Canal de distribución</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_CanalVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_CanalVentas__c</fullName>
    <label>Organización de ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_CentroBeneficio__c.field-meta.xml
<CustomField>
    <fullName>IMP_CentroBeneficio__c</fullName>
    <label>Centro de beneficio</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_ClaseDocumento__c.field-meta.xml
<CustomField>
    <fullName>IMP_ClaseDocumento__c</fullName>
    <label>Clase de documento</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_CreadoPor__c.field-meta.xml
<CustomField>
    <fullName>IMP_CreadoPor__c</fullName>
    <label>Creado por</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SF</fullName>
                <default>true</default>
                <label>SF</label>
            </value>
            <value>
                <fullName>TIO</fullName>
            </value>
            <value>
                <fullName>PLENUS</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_DescripcionCeBe__c.field-meta.xml
<CustomField>
    <fullName>IMP_DescripcionCeBe__c</fullName>
    <label>Descripción Ce Be</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_DescripcionGrupoVendedor__c.field-meta.xml
<CustomField>
    <fullName>IMP_DescripcionGrupoVendedor__c</fullName>
    <label>Descripción Grupo Vendedor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_GrupoVendedor__c.field-meta.xml
<CustomField>
    <fullName>IMP_GrupoVendedor__c</fullName>
    <label>Grupo vendedor</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_ModificacionPedidos__c.field-meta.xml
<CustomField>
    <fullName>IMP_ModificacionPedidos__c</fullName>
    <label>Log Modificación Pedidos</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_NumeroCliente__c.field-meta.xml
<CustomField>
    <fullName>IMP_NumeroCliente__c</fullName>
    <label>Número de cliente</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_OficinaVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_OficinaVentas__c</fullName>
    <label>Oficina de ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_SectorVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_SectorVentas__c</fullName>
    <label>Sector de Ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/pedido__c.field-meta.xml
<CustomField>
    <fullName>pedido__c</fullName>
    <description>Número de pedido en SAP</description>
    <externalId>true</externalId>
    <label>ID Pedido SAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ViaPago__c.field-meta.xml
<CustomField>
    <fullName>ViaPago__c</fullName>
    <label>Vía de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>via_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IMP_LlaveExclusiva__c.field-meta.xml
<CustomField>
    <fullName>IMP_LlaveExclusiva__c</fullName>
    <description>Número de pedido + posición + código del producto</description>
    <externalId>true</externalId>
    <label>Llave exclusiva</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/PoliticaDescuento__c.object-meta.xml
<CustomObject>
    <label>Política de descuento</label>
    <nameField>
        <label>Nombre de Política de descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Politicas de descuento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PoliticaDescuento__c/fields/Canaldistribucion__c.field-meta.xml
<CustomField>
    <fullName>Canaldistribucion__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanalDistribucion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/condiciones_de_pago__c.field-meta.xml
<CustomField>
    <fullName>condiciones_de_pago__c</fullName>
    <label>Condiciones de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CondicionesPago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CanalDistribucion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>E-Commerce</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Obras y Proyectos</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Des. Negocios</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Industriales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Exportación</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Call Center</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Ventas Directas</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Mayorista</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Otras Ventas</label>
    </customValue>
    <masterLabel>Canal de distribución</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CondicionesPago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NT00</fullName>
        <default>true</default>
        <label>Pagado a la recepcion</label>
    </customValue>
    <customValue>
        <fullName>NT08</fullName>
        <label>Vencimiento 08 dias</label>
    </customValue>
    <customValue>
        <fullName>NT15</fullName>
        <label>Vencimiento 15 dias</label>
    </customValue>
    <customValue>
        <fullName>NT20</fullName>
        <label>Vencimiento 20 dias</label>
    </customValue>
    <customValue>
        <fullName>NT30</fullName>
        <label>Vencimiento 30 dias</label>
    </customValue>
    <customValue>
        <fullName>NT45</fullName>
        <label>Vencimiento 45 dias</label>
    </customValue>
    <customValue>
        <fullName>NT60</fullName>
        <label>Vencimiento 60 dias</label>
    </customValue>
    <customValue>
        <fullName>NT90</fullName>
        <label>Vencimiento 90 dias</label>
    </customValue>
    <customValue>
        <fullName>NT120</fullName>
        <label>Vencimiento 120 dias</label>
    </customValue>
    <masterLabel>Condiciones de Pago</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/via_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>C</fullName>
        <label>Cheque</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>Deposito</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>Efectivo</label>
    </customValue>
    <customValue>
        <fullName>F</fullName>
        <label>Tarjeta de crédito</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Cheque Prod IQ</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>Tarjeta de Débito</label>
    </customValue>
    <customValue>
        <fullName>I</fullName>
        <label>Nota de Credito</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Por Definir</label>
    </customValue>
    <customValue>
        <fullName>T</fullName>
        <label>Transferencia Bancaria</label>
    </customValue>
    <masterLabel>Via de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_Pedido.cls
/****************************************************************************************************************
Name: IMP_Pedido.apxc
Copyright © 2023 Salesforce 
====================================================================================================================
Purpose: 

====================================================================================================================
History:
It is requested to migrate the quote's visual force page to a lightning component.
Creation
VERSION  AUTHOR               DATE          LINES     DETAIL           DESCRIPTION.
1.0      mvilchis@ts4.mx    15/04/2022      16-130    Order           
2.0.     rotrejo@ts4.mx     02/05/2023      16-169    Order               
********************************************************************************************************************/
@RestResource(urlMapping='/Order/*')
global class IMP_Pedido {
    /******************************************************************* 
    Purpose: Gets the answer if the order transactions was created or modified correctly.
    Parameters:
    Returns: SapResponse.
    Throws :
    Information about changes (versions)
    ********************************************************************/ 
    @HttpPost
    global static SapResponse upsertOrder() {
        
        SapResponse respuestaSap = new SapResponse();
        Map<String,String> mapResponseTransaccion= new Map<String,String>();
        List<OrderItem> listOrder = new  List<OrderItem>();
        List<Decimal> listPos= new  List<Decimal>();
        set<String> listCodigos= new  set<String>();
        set<String> setKeys = new set<String>();
        set<String> setPbes = new set<String>();
        Map<String, PricebookEntry> mapPricebookEntry = new Map<String, PricebookEntry>();
        Map<String, String> mapProducts = new Map<String, String>();
        String mensajePedido;
        System.debug('---BODY---');
        System.debug(RestContext.request.requestBody.toString());
        IMP_EnvioPedidoSAP nuevoPedido = (IMP_EnvioPedidoSAP) JSON.deserialize(RestContext.request.requestBody.toString(),IMP_EnvioPedidoSAP.class);
        Account cuenta = getAccount(nuevoPedido.I_KUNNR+nuevoPedido.I_VKORG+nuevoPedido.I_VTWEG+nuevoPedido.SPART);
        Order pedido;
        try{
            
            System.debug(nuevoPedido.I_KUNNR+nuevoPedido.I_VKORG+nuevoPedido.I_VTWEG+nuevoPedido.SPART);
            pedido = new Order(pedido__c =  nuevoPedido.E_VBELN,
                               ViaPago__c = nuevoPedido.ZLSCH,
                               EffectiveDate =nuevoPedido.BSTDK.length()==8 && nuevoPedido.BSTDK!= '00000000'? Date.valueOf(nuevoPedido.BSTDK.substring(0,4)+'-'+nuevoPedido.BSTDK.substring(4,6)+'-'+nuevoPedido.BSTDK.substring(6,8)):nuevoPedido.BSTDK =='00000000'? Date.today() : Date.valueOf(nuevoPedido.BSTDK),
                               IMP_ClaseDocumento__c  = nuevoPedido.AUART,
                               IMP_OficinaVentas__c = nuevoPedido.I_VKBUR,
                               IMP_CanalVentas__c = nuevoPedido.I_VKORG,
                               IMP_SectorVentas__c = nuevoPedido.SPART,
                               IMP_NumeroCliente__c = nuevoPedido.I_KUNNR,
                               IMP_GrupoVendedor__c = nuevoPedido.I_VKGRP,
                               IMP_DescripcionGrupoVendedor__c = nuevoPedido.BEZEI,
                               IMP_DescripcionCeBe__c  = nuevoPedido.LTEXT,
                               IMP_CentroBeneficio__c = nuevoPedido.PRCTR,
                               Precio_Total__c  = nuevoPedido.NETWR != null && nuevoPedido.NETWR!= ''?Decimal.valueOf(nuevoPedido.NETWR.replace(' ', '')):0,
                               IMP_CreadoPor__c  = nuevoPedido.ERNAM,
                               Status = nuevoPedido.GBSTK != null ? nuevoPedido.GBSTK :'Draft',
                               condiciones_de_pago__c = nuevoPedido.ZTERM,
                               IMP_CanalDistribucion__c = nuevoPedido.I_VTWEG,
                               IMP_ModificacionPedidos__c = RestContext.request.requestBody.toString());
            
            if(nuevoPedido.I_KUNNR != null && nuevoPedido.I_VKORG != null && nuevoPedido.I_VTWEG != null && nuevoPedido.SPART != null){
                pedido.AccountId=cuenta.Id!= null?pedido.AccountId=cuenta.Id: System.label.IMP_Cuenta ;
                pedido.OwnerId= getOwner(nuevoPedido.I_VKGRP,nuevoPedido.EXT1);
            }
            upsert pedido pedido__c;
            mensajePedido='Pedido Actualizado';
        }catch(Exception e){
            mensajePedido='Error en el pedido : '+ e.getMessage();
            System.debug(e.getMessage()+' - '+e.getLineNumber());
            insert new Integration_Logs__c(Tipo__c='CREAR_PEDIDO_SF',Body_JSON__c=RestContext.request.requestBody.toString().replace('"',''),Clase__c=e.getTypeName()+' '+e.getCause()+' '+e.getStackTraceString()+', Fecha : '+ DateTime.now().format('yyyy/MM/dd hh:mm:ss'), Linea__c= String.valueOf(e.getLineNumber()), Mensaje_SFDC__c=e.getMessage());
        }
        
        if(nuevoPedido.I_ITEM != null && nuevoPedido.I_ITEM.size()>0){
            for(IMP_EnvioPedidoSAP.cls_I_ITEM prodPedido : nuevoPedido.I_ITEM){
                listCodigos.add(prodPedido.MATNR.replaceFirst('^0+', ''));
            }
            for (OrderItem oi :[SELECT Id,IMP_LlaveExclusiva__c FROM Orderitem WHERE Order.pedido__c=:pedido.pedido__c])
            {
                setKeys.add(oi.IMP_LlaveExclusiva__c);
            }
            Order pedidoSf=[SELECT Id, Pricebook2id,pedido__c,Account.clave_delcanal__c,Account.grupo__c FROM Order WHERE pedido__c=:pedido.pedido__c];
            for(PricebookEntry pb:[SELECT Id,ProductCode,product2.Grupo_de_Materiales__c,UnitPrice FROM PricebookEntry WHERE ProductCode IN: listCodigos AND Pricebook2Id=:pedidoSf.Pricebook2Id AND UnitPrice>0])
            {
                mapPricebookEntry.put(pb.ProductCode, pb);
                setPbes.add(pb.product2.Grupo_de_Materiales__c);
            }
            Map<String,PoliticaDescuento__c> mapDescuentosSAP = new Map<String,PoliticaDescuento__c>();
            System.debug('Clave del canal : '+pedidoSf.Account.clave_delcanal__c);
            System.debug('Grupo del Producto : '+pedidoSf.Account.grupo__c);
            List<PoliticaDescuento__c> politicas =[SELECT Id, Activa__c, Canaldistribucion__c,GrupoProducto__c, Descuento__c,
                                                   Grupo_de_cliente_del__c, CreatedDate FROM PoliticaDescuento__c WHERE Activa__c = true
                                                   AND Canaldistribucion__c =:pedidoSf.Account.clave_delcanal__c
                                                   AND Grupo_de_cliente_del__c =:pedidoSf.Account.grupo__c
                                                   AND GrupoProducto__c IN:setPbes  ORDER BY CreatedDate ASC];
            for(PoliticaDescuento__c politica :politicas){
                mapDescuentosSAP.put(politica.GrupoProducto__c, politica);   
            }
            
            for(IMP_EnvioPedidoSAP.cls_I_ITEM prodPedido : nuevoPedido.I_ITEM){
                String llave=nuevoPedido.E_VBELN + '-' + prodPedido.POSNR.replaceFirst('^0+', '') + '-' + prodPedido.MATNR.replaceFirst('^0+', '');
                listPos.add(Decimal.valueOf(prodPedido.POSNR));
                if(setKeys.contains(llave))
                {
                    listOrder.add(new OrderItem (
                        Quantity = prodPedido.KWMENG,
                        DescuentoManual__c  = prodPedido.KAWRT/10,
                        IMP_LlaveExclusiva__c =llave,
                        IMP_Posicion__c=Decimal.valueOf(prodPedido.POSNR.replaceFirst('^0+', ''))
                    ));
                    mapProducts.put(llave,mapPricebookEntry.get(prodPedido.MATNR.replaceFirst('^0+', '')).product2.Grupo_de_Materiales__c);
                }else {
                    if(mapPricebookEntry.containsKey(prodPedido.MATNR.replaceFirst('^0+', '')))
                    {
                        listOrder.add(new OrderItem (
                            Quantity = prodPedido.KWMENG,
                            OrderId=pedidoSf.Id,
                            PricebookEntryId=mapPricebookEntry.get(prodPedido.MATNR.replaceFirst('^0+', '')).Id,
                            UnitPrice=mapPricebookEntry.get(prodPedido.MATNR.replaceFirst('^0+', '')).UnitPrice,
                            DescuentoManual__c  = prodPedido.KAWRT/10,
                            IMP_LlaveExclusiva__c =llave,
                            IMP_Posicion__c=Decimal.valueOf(prodPedido.POSNR.replaceFirst('^0+', ''))
                        ));
                        mapProducts.put(llave,mapPricebookEntry.get(prodPedido.MATNR.replaceFirst('^0+', '')).product2.Grupo_de_Materiales__c);
                    }
                }
            }
            delete [SELECT Id FROM OrderItem WHERE IMP_Posicion__c NOT IN : listPos  AND Order.pedido__c=:nuevoPedido.E_VBELN];
            List<OrderItem> newOrderItem = new  List<OrderItem>();
            Database.UpsertResult[] results =  Database.upsert(listOrder,OrderItem.IMP_LlaveExclusiva__c, false);
            Integer size = results.size();
            for(Integer index = 0; index < size; index++) {
                if(results[index].isSuccess()) {
                    if(results[index].isCreated()) {
                        if(mapProducts.get(listOrder[index].IMP_LlaveExclusiva__c) != null){
                            System.debug('Grupo Prod '+mapProducts.get(listOrder[index].IMP_LlaveExclusiva__c));
                           // System.debug('Descuento : ' + mapDescuentosSAP.get(mapProducts.get(listOrder[index].IMP_LlaveExclusiva__c)).Descuento__c);
                            listOrder[index].DescuentoSAP__c=mapDescuentosSAP.containsKey(mapProducts.get(listOrder[index].IMP_LlaveExclusiva__c))?mapDescuentosSAP.get(mapProducts.get(listOrder[index].IMP_LlaveExclusiva__c)).Descuento__c:0;
                            newOrderItem.add(listOrder[index]);
                        }
                        
                        mapResponseTransaccion.put(String.valueOf(listOrder[index].IMP_Posicion__c),'Partida Creada ' + nuevoPedido.I_ITEM[index].MATNR.replaceFirst('^0+', '')); 
                    } else {
                        mapResponseTransaccion.put(String.valueOf(listOrder[index].IMP_Posicion__c),'Partida Modificada ' + nuevoPedido.I_ITEM[index].MATNR.replaceFirst('^0+', '')); 
                    }
                }else{
                    mapResponseTransaccion.put(String.valueOf(listOrder[index].IMP_Posicion__c), String.valueOf(results[index].getErrors()));
                }
                if(!newOrderItem.isEmpty()){
                    update newOrderItem;
                }
            }
        }
        
        //noPedido+codigopro+pos
        respuestaSap.VBELN=nuevoPedido.E_VBELN +' : '+mensajePedido;
        respuestaSap.MSGNR=mapResponseTransaccion;
        return respuestaSap;
    }
    /******************************************************************* 
    Purpose: Gets an Account by the LLaveExclusiva__c
    Parameters:
    Returns: SapResponse.
    Throws :
    Information about changes (versions)
    ********************************************************************/ 
    public static Account getAccount(String llave){
        Account cuenta = new Account();
        try{
            cuenta =[SELECT ID FROM ACCOUNT WHERE IMP_LlaveExterna__c =:llave];
        } catch(Exception e){
        }
        return cuenta;
    }
    /******************************************************************* 
    Purpose: Gets an owner by GrupoVendedor__c AND Sucursal
    Parameters:
    Returns: SapResponse.
    Throws :
    Information about changes (versions)
    ********************************************************************/ 
    public static ID getOwner(String grupoVendedor,String sucursalParam){
        system.debug('sucursalParam ' + sucursalParam);
        Map<String,User> mapUsers= new  Map<String,User>();
        for(User usuario:[SELECT Id,Grupo_de_Vendedor__c,Name FROM User WHERE (Grupo_de_Vendedor__c =: Decimal.valueOf(grupoVendedor) OR Name LIKE 'Sucursal%') AND IsActive=true AND Name != 'SAP Integrator']){
            mapUsers.put(String.valueOf(usuario.Grupo_de_Vendedor__c), usuario);
            mapUsers.put(String.valueOf(usuario.Name), usuario);
           
        }
        map<String,String> mapCentroSuministrador = new map<String,String>();
        Schema.DescribeFieldResult fieldResult = Account.centro_suministrador__c.getDescribe();
        for( Schema.PicklistEntry f : fieldResult.getPicklistValues())
        {
            mapCentroSuministrador.put(f.getValue(),f.getLabel());
        } 
        String sucursal='Sucursal '+mapCentroSuministrador.get(sucursalParam);
        String sucursalSinAcento=sucursal.replaceAll('á', 'a').replaceAll('é', 'e').replaceAll('í', 'i').replace('ó', 'o').replaceAll('ú', 'u');
        return (grupoVendedor=='001')?mapUsers.containsKey(sucursal)?mapUsers.get(sucursal).Id:mapUsers.containsKey(sucursalSinAcento)?mapUsers.get(sucursalSinAcento).Id:UserInfo.getUserId():mapUsers.containsKey(grupoVendedor)?mapUsers.get(grupoVendedor).Id:UserInfo.getUserId();        
    }
    
    global class SapResponse{
        Public String VBELN;
        public Map<String,String> MSGNR;   
    } 
}