force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/grupo__c.field-meta.xml
<CustomField>
    <fullName>grupo__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Distribuidor A</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Distribuidor B</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Distribuidor C</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidor D</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Contratistas A</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Contratistas B</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Contratistas C</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Multimarcas A</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Multimarcas B</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Multimarcas C</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Desarrollo de Negoci</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Aplicador A</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Contratistas Plus</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OrganizacionVentas__c.field-meta.xml
<CustomField>
    <fullName>OrganizacionVentas__c</fullName>
    <label>Organización de Ventas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GOGA</fullName>
                <label>Gogal</label>
            </value>
            <value>
                <fullName>GRAV</fullName>
                <label>Graviq</label>
            </value>
            <value>
                <fullName>IMPQ</fullName>
                <default>true</default>
                <label>Imperquimia SA de CV</label>
            </value>
            <value>
                <fullName>IQSE</fullName>
                <label>IQ Servicios</label>
            </value>
            <value>
                <fullName>LEMA</fullName>
                <label>Lemma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Descuento__c/Descuento__c.object-meta.xml
<CustomObject>
    <label>Descuento</label>
    <nameField>
        <label>Nombre de Descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Descuento__c/fields/IMP_ImportePorcentaje__c.field-meta.xml
<CustomField>
    <fullName>IMP_ImportePorcentaje__c</fullName>
    <description>Importe o porcentaje que establece de qué modo debe calcular el sistema esta condición al efectuar la determinación automática de precios. La clase de condición determina si se trata de un importe fijo o de un porcentaje.</description>
    <label>Importe/Porcentaje</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_UnidadCondicion__c.field-meta.xml
<CustomField>
    <fullName>IMP_UnidadCondicion__c</fullName>
    <label>Unidad de condición(Moneda o Porcentaje)</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/PoliticaDescuento__c.object-meta.xml
<CustomObject>
    <label>Política de descuento</label>
    <nameField>
        <label>Nombre de Política de descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Politicas de descuento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PoliticaDescuento__c/fields/Activa__c.field-meta.xml
<CustomField>
    <fullName>Activa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/fields/Canaldistribucion__c.field-meta.xml
<CustomField>
    <fullName>Canaldistribucion__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanalDistribucion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/fields/Descuento__c.field-meta.xml
<CustomField>
    <fullName>Descuento__c</fullName>
    <inlineHelpText>Este valor calcula el descuento para la política</inlineHelpText>
    <label>Descuento</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/fields/Grupo_de_cliente_del__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_cliente_del__c</fullName>
    <label>Grupo de cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_de_Cliente</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/fields/GrupoProducto__c.field-meta.xml
<CustomField>
    <fullName>GrupoProducto__c</fullName>
    <label>Grupo de materiales</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_de_materiales</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Lista_de_precios_SAP__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_precios_SAP__c</fullName>
    <label>Lista de precios SAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lista_de_precios_SAP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Grupo_de_art_culos__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_art_culos__c</fullName>
    <label>Grupo de artículos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ESPA</fullName>
                <label>Espacios</label>
            </value>
            <value>
                <fullName>GUARQM</fullName>
                <label>Guardquim</label>
            </value>
            <value>
                <fullName>IMPERC</fullName>
                <label>Impercryl</label>
            </value>
            <value>
                <fullName>NAYA</fullName>
                <label>Naya</label>
            </value>
            <value>
                <fullName>QUIMCR</fullName>
                <label>Quimicret</label>
            </value>
            <value>
                <fullName>SELLAQ</fullName>
                <label>Sellaquim</label>
            </value>
            <value>
                <fullName>SOPORT</fullName>
                <label>Soporte</label>
            </value>
            <value>
                <fullName>DOCFIN</fullName>
                <label>Documento Financiero</label>
            </value>
            <value>
                <fullName>ACCESO</fullName>
                <label>Accesorio</label>
            </value>
            <value>
                <fullName>IQ</fullName>
                <label>Imperquimia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Grupo_de_Materiales__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Materiales__c</fullName>
    <label>Grupo de Materiales</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_de_materiales</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>DescuentoSAP__c</fullName>
    <label>Descuento SAP</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IMP_Descuento__c.field-meta.xml
<CustomField>
    <fullName>IMP_Descuento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Descuento que aplica de acuerdo a promociones</description>
    <label>Descuento</label>
    <referenceTo>Descuento__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IMP_DescuentoPromo__c.field-meta.xml
<CustomField>
    <fullName>IMP_DescuentoPromo__c</fullName>
    <description>Descuento de promoción de acuerdo a criterios de descuentos promocionales de SAP</description>
    <label>Descuento promoción</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IMP_OmitirDescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>IMP_OmitirDescuentoSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para identificar cuando se omite el descuento sap con base al grupo del cliente 17 Aplicador A y canal 02 Mostrador</description>
    <label>Omitir descuento SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PoliticaDescuento__c.field-meta.xml
<CustomField>
    <fullName>PoliticaDescuento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Política de descuento</label>
    <referenceTo>PoliticaDescuento__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrecioTotalConDescuentos__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotalConDescuentos__c</fullName>
    <label>Precio Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/CanalDistribucion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>E-Commerce</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Obras y Proyectos</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Des. Negocios</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Industriales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Exportación</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Call Center</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Ventas Directas</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Mayorista</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Otras Ventas</label>
    </customValue>
    <masterLabel>Canal de distribución</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_de_Cliente.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Distribuidor A</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Distribuidor B</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Distribuidor C</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidor D</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Contratistas A</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Contratistas B</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Contratistas C</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Multimarcas A</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Multimarcas B</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Multimarcas C</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>Obras y Proyectos</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Industriales</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Exportación</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Desarrollo de Negoci</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Call Center</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>Aplicador A</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>Contratistas Plus</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>Retail</label>
    </customValue>
    <masterLabel>Grupo de Cliente</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_de_materiales.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Lineas Generales</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Lineas Mayoristas</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Lineas Populares</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Commodity</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Especiales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Ultra Comodity</label>
    </customValue>
    <masterLabel>Grupo de materiales</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lista_de_precios_SAP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <masterLabel>Lista de precios SAP</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_HandleDescuentos.cls
/************************************************************************
Name: IMP_HandleDescuentos
Copyright © 2023 Salesforce
========================================================================
Purpose:
Aplica los descuentos a la partida de la cotización
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
3.0      rotrejo@ts4.mx     11/05/2023     
************************************************************************/
public inherited sharing class IMP_HandleDescuentos {
    
    /*******************************************************************
    Purpose: Aplica descuentos a la partida de cotización
    Parameters: List<QuoteLineItem> listOrderItem
    Returns: 
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    public static void applyDiscounts(List<QuoteLineItem> listOrderItem){
        
        Quote quote = [SELECT Id,Account.clave_delcanal__c, Account.id_de_sap__c,Account.OrganizacionVentas__c,
                       Pricebook2.Sucursal__c,Pricebook2.Lista_de_precios_SAP__c,Account.grupo__c
                       FROM Quote WHERE Id=: listOrderItem[0].QuoteId];
        set<Id> setProdIds = new set<Id>();
        set<Id> setPbeIds = new set<Id>();
        for(QuoteLineItem quoteLineItem : listOrderItem){
            setProdIds.add(quoteLineItem.Product2Id);
            setPbeIds.add(quoteLineItem.PricebookEntryId);
        }
        Map<Id,PricebookEntry> mapPbe = new Map<Id,PricebookEntry>([SELECT Id,Product2.Grupo_de_art_culos__c,UnitPrice,Product2.Grupo_de_Materiales__c,Product2.ProductCode FROM PricebookEntry WHERE Id IN:setPbeIds]);
        Map<String,PoliticaDescuento__c> mapPoliticas =  getDiscountPolitica(quote);
        IMP_DescuentosManager.WrapperSecuences mapSecuences = IMP_DescuentosManager.getDiscountByQuote(quote);
        String grupoClientePromo = System.label.IMP_GrupoClientePromo;

        for(QuoteLineItem quoteLineItem : listOrderItem){
            
            Descuento__c descuentoPromo = getDiscountByLineItem(quoteLineItem,quote,mapSecuences,mapPbe);
            Decimal PrecioTotalDescuentos =  mapPbe.get(quoteLineItem.PricebookEntryId).UnitPrice *  quoteLineItem.Quantity;
            PoliticaDescuento__c politica = new PoliticaDescuento__c();
            String grupoMateriales = mapPbe.get(quoteLineItem.PricebookEntryId).Product2.Grupo_de_Materiales__c;
            politica = mapPoliticas.ContainsKey(quote.Account.clave_delcanal__c+quote.Account.grupo__c+grupoMateriales) ? mapPoliticas.get(quote.Account.clave_delcanal__c+quote.Account.grupo__c+grupoMateriales):null ;
            
            PrecioTotalDescuentos = politica!= null ?PrecioTotalDescuentos - (PrecioTotalDescuentos * (politica.Descuento__c  / 100)):PrecioTotalDescuentos ;
            quoteLineItem.Discount = politica!= null ? politica.Descuento__c : 0;
            quoteLineItem.DescuentoSAP__c = politica!= null ? politica.Descuento__c : 0;
            quoteLineItem.PoliticaDescuento__c =  politica!= null ? politica.Id : null;

            if(descuentoPromo != null){
                
                if(descuentoPromo.IMP_ImportePorcentaje__c > 0){
                    
                    if(quote.Account.clave_delcanal__c == System.label.IMP_CanalPromo && quote.Account.grupo__c == grupoClientePromo){
                        PrecioTotalDescuentos =  mapPbe.get(quoteLineItem.PricebookEntryId).UnitPrice * quoteLineItem.Quantity;
                        quoteLineItem.DescuentoSAP__c = 0;
                        quoteLineItem.Discount = 0;
                        quoteLineItem.IMP_OmitirDescuentoSAP__c = true;
                        quoteLineItem.PrecioTotalConDescuentos__c = PrecioTotalDescuentos;
                    }
                    quoteLineItem.IMP_DescuentoPromo__c = descuentoPromo.IMP_ImportePorcentaje__c;
                    quoteLineItem.IMP_Descuento__c = descuentoPromo.Id;
                    if(descuentoPromo.IMP_UnidadCondicion__c.trim() == '%'){
                        PrecioTotalDescuentos =  PrecioTotalDescuentos - (PrecioTotalDescuentos * (descuentoPromo.IMP_ImportePorcentaje__c  / 100));
                        System.debug('PRECIO TOTAL DESCUENTOS::'+PrecioTotalDescuentos);
                    }
                    else {
                        PrecioTotalDescuentos = PrecioTotalDescuentos - descuentoPromo.IMP_ImportePorcentaje__c;
                    }
                  
                }
            }
            quoteLineItem.PrecioTotalConDescuentos__c = PrecioTotalDescuentos;
        }
    }
    
    /*******************************************************************
    Purpose: Obtiene el descuento Temporal por partida
    Parameters: List<QuoteLineItem> listOrderItem
    Returns: 
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    public static Descuento__c getDiscountByLineItem(QuoteLineItem quoteLineItem, Quote quote,IMP_DescuentosManager.WrapperSecuences mapSecuences,Map<Id,PricebookEntry> mapProducts){
       System.debug('getDiscountByLineItem');
        Descuento__c descuentoPromo = new Descuento__c();
        IMP_DescuentosManager.WrapperSecuencesParam param = new IMP_DescuentosManager.WrapperSecuencesParam();
        param.OrgVentas = quote.Account.OrganizacionVentas__c;
        param.canalVentas = quote.Account.clave_delcanal__c;
        param.numeroCliente = quote.Account.id_de_sap__c;
        param.numeroMaterial = mapProducts.containsKey(quoteLineItem.PricebookEntryId) ? mapProducts.get(quoteLineItem.PricebookEntryId).Product2.ProductCode : '';
        param.OficinaVentas = quote.PriceBook2.Sucursal__c;
        param.ListaPrecios = quote.Pricebook2.Lista_de_precios_SAP__c;
        param.GrupoMateriales = mapProducts.containsKey(quoteLineItem.PricebookEntryId) ? mapProducts.get(quoteLineItem.PricebookEntryId).Product2.Grupo_de_Materiales__c : '';
        param.GrupoArticulos = mapProducts.containsKey(quoteLineItem.PricebookEntryId) ? mapProducts.get(quoteLineItem.PricebookEntryId).Product2.Grupo_de_art_culos__c : '';
        param.GrupoClientes = quote.Account.grupo__c;
        param.ClaseDoc = System.label.IMP_ClasePedido;
        param.CanalPromocion = System.label.IMP_CanalPromo;
        descuentoPromo =  IMP_DescuentosManager.getDiscountByToApply(param, mapSecuences);
        return descuentoPromo;
        
    }
    
    /*******************************************************************
    Purpose: Aplica el descuento por politica a la partida de cotización
    Parameters: List<QuoteLineItem> listOrderItem
    Returns: 
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    public static Map<String,PoliticaDescuento__c> getDiscountPolitica(Quote quote){
        Map<String,PoliticaDescuento__c> mapPoliticas = new  Map<String,PoliticaDescuento__c>();
        for(PoliticaDescuento__c politica : [SELECT Id,Activa__c,Canaldistribucion__c, GrupoProducto__c,Descuento__c,Grupo_de_cliente_del__c
                                                        FROM PoliticaDescuento__c WHERE Activa__c = true AND Canaldistribucion__c =:quote.Account.clave_delcanal__c
                                                        AND Grupo_de_cliente_del__c =:quote.Account.grupo__c]){
         mapPoliticas.put(politica.Canaldistribucion__c+politica.Grupo_de_cliente_del__c+politica.GrupoProducto__c,politica);
        }
        return mapPoliticas;
    }
    
}