force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OrganizacionVentas__c.field-meta.xml
<CustomField>
    <fullName>OrganizacionVentas__c</fullName>
    <label>Organización de Ventas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GOGA</fullName>
                <label>Gogal</label>
            </value>
            <value>
                <fullName>GRAV</fullName>
                <label>Graviq</label>
            </value>
            <value>
                <fullName>IMPQ</fullName>
                <default>true</default>
                <label>Imperquimia SA de CV</label>
            </value>
            <value>
                <fullName>IQSE</fullName>
                <label>IQ Servicios</label>
            </value>
            <value>
                <fullName>LEMA</fullName>
                <label>Lemma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <default>true</default>
                <label>Asfalticos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IMP_JsonOutput.cls
/************************************************************************
Name: IMP_JsonOutput
Copyright © 2022 Salesforce
========================================================================
Purpose:
Wrapper de la respuesta para exposición de servicio retorna clave y
id_salesforce o en su caso el error.
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  2.0      mvilchis@ts4.mx    11/04/2022     Limpieza y optimización de 
  código
************************************************************************/
public with sharing class IMP_JsonOutput {
    /*******************************************************************
    Purpose: Wrapper de la respuesta de la exposición del servicio,
    se retorna id salesforce y la clave SAP.
    Parameters: List<Account> lstAccIns
    Returns: String
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    public static string output(List<Account> lstAccIns) {
        List<ErrorWrapper> lstError = new List<ErrorWrapper>();
        List<CreacionClientesWrapper> lstAccount = new List<CreacionClientesWrapper>();
        for(Account acc : lstAccIns) {
            system.debug('Entro al JSOn ');
            CreacionClientesWrapper creacion = new CreacionClientesWrapper();
            creacion.id_SFDC = acc.Id;
            creacion.clave_SAP = acc.id_de_sap__c;
            creacion.VKORG=acc.OrganizacionVentas__c;
            creacion.VTWEG=acc.clave_delcanal__c;
            creacion.SPART=acc.Sector__c;
            lstAccount.add(creacion);
        }
        for(Account acc : lstAccIns) {
            ErrorWrapper error = new ErrorWrapper();
            error.mensaje = '';
            error.time_stamp = '';
            lstError.add(error);
        }
        ResponseWrapper jsonRes = new ResponseWrapper();
        jsonRes.status_SFDC = 'SUCESS';
        jsonRes.error_SFDC = lstError;
        jsonRes.creacion_SFDC = lstAccount;
        String output = (String)JSON.serialize(jsonRes);
        return output;
    }
    public class ResponseWrapper {
        public String status_SFDC {get;set;}
        public List<ErrorWrapper> error_SFDC {get;set;}
        public List<CreacionClientesWrapper> creacion_SFDC {get;set;}
    }
    public class ErrorWrapper {
        public String mensaje {get;set;}
        public String time_stamp {get;set;}
    }
    public class CreacionClientesWrapper {
        public String id_SFDC {get;set;}
        public String clave_SAP {get;set;}
        public String VKORG {get;set;}
        public String VTWEG {get;set;}
        public String SPART {get;set;}
    }
}