force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/grupo__c.field-meta.xml
<CustomField>
    <fullName>grupo__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Distribuidor A</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Distribuidor B</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Distribuidor C</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidor D</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Contratistas A</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Contratistas B</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Contratistas C</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Multimarcas A</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Multimarcas B</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Multimarcas C</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Desarrollo de Negoci</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Aplicador A</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Contratistas Plus</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Descuento__c/Descuento__c.object-meta.xml
<CustomObject>
    <label>Descuento</label>
    <nameField>
        <label>Nombre de Descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Descuento__c/fields/IMP_ImportePorcentaje__c.field-meta.xml
<CustomField>
    <fullName>IMP_ImportePorcentaje__c</fullName>
    <description>Importe o porcentaje que establece de qué modo debe calcular el sistema esta condición al efectuar la determinación automática de precios. La clase de condición determina si se trata de un importe fijo o de un porcentaje.</description>
    <label>Importe/Porcentaje</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DescuentoAdicional__c.field-meta.xml
<CustomField>
    <fullName>DescuentoAdicional__c</fullName>
    <description>Copia el descuento adicional de la cotización</description>
    <label>Descuento adicional</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>DescuentoSAP__c</fullName>
    <description>Descuento que tiene el producto desde SAP</description>
    <label>Descuento SAP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/IMP_DescuentoPromo__c.field-meta.xml
<CustomField>
    <fullName>IMP_DescuentoPromo__c</fullName>
    <description>Descuento por promoción</description>
    <label>Descuento promoción</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/IMP_OmitirDescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>IMP_OmitirDescuentoSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para identificar cuando se omite el descuento sap con base al grupo del cliente 17 Aplicador A y canal 02 Mostrador</description>
    <label>Omitir descuento SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DescuentoManual__c.field-meta.xml
<CustomField>
    <fullName>DescuentoManual__c</fullName>
    <description>Campo usado para almacenar el descuento total.</description>
    <label>Descuento Manual</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>DescuentoSAP__c</fullName>
    <description>Campo usado para capturar el descuento de SAP</description>
    <label>Descuento SAP</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IMP_Descuento__c.field-meta.xml
<CustomField>
    <fullName>IMP_Descuento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Descuento que aplica de acuerdo a promociones</description>
    <label>Descuento promoción relacion</label>
    <referenceTo>Descuento__c</referenceTo>
    <relationshipLabel>Productos de pedidos</relationshipLabel>
    <relationshipName>Productos_de_pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/PoliticaDescuento__c.object-meta.xml
<CustomObject>
    <label>Política de descuento</label>
    <nameField>
        <label>Nombre de Política de descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Politicas de descuento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PoliticaDescuento__c/fields/Activa__c.field-meta.xml
<CustomField>
    <fullName>Activa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/fields/Canaldistribucion__c.field-meta.xml
<CustomField>
    <fullName>Canaldistribucion__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanalDistribucion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/fields/Descuento__c.field-meta.xml
<CustomField>
    <fullName>Descuento__c</fullName>
    <inlineHelpText>Este valor calcula el descuento para la política</inlineHelpText>
    <label>Descuento</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/fields/Grupo_de_cliente_del__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_cliente_del__c</fullName>
    <label>Grupo de cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_de_Cliente</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/fields/GrupoProducto__c.field-meta.xml
<CustomField>
    <fullName>GrupoProducto__c</fullName>
    <label>Grupo de materiales</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_de_materiales</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Grupo_de_art_culos__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_art_culos__c</fullName>
    <label>Grupo de artículos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ESPA</fullName>
                <label>Espacios</label>
            </value>
            <value>
                <fullName>GUARQM</fullName>
                <label>Guardquim</label>
            </value>
            <value>
                <fullName>IMPERC</fullName>
                <label>Impercryl</label>
            </value>
            <value>
                <fullName>NAYA</fullName>
                <label>Naya</label>
            </value>
            <value>
                <fullName>QUIMCR</fullName>
                <label>Quimicret</label>
            </value>
            <value>
                <fullName>SELLAQ</fullName>
                <label>Sellaquim</label>
            </value>
            <value>
                <fullName>SOPORT</fullName>
                <label>Soporte</label>
            </value>
            <value>
                <fullName>DOCFIN</fullName>
                <label>Documento Financiero</label>
            </value>
            <value>
                <fullName>ACCESO</fullName>
                <label>Accesorio</label>
            </value>
            <value>
                <fullName>IQ</fullName>
                <label>Imperquimia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Grupo_de_Materiales__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Materiales__c</fullName>
    <label>Grupo de Materiales</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_de_materiales</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Lista_precios__c.field-meta.xml
<CustomField>
    <fullName>Lista_precios__c</fullName>
    <label>Tipo de lista de precios</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lista_de_precios_SAP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>DescuentoSAP__c</fullName>
    <label>Descuento SAP</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IMP_Descuento__c.field-meta.xml
<CustomField>
    <fullName>IMP_Descuento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Descuento que aplica de acuerdo a promociones</description>
    <label>Descuento</label>
    <referenceTo>Descuento__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IMP_DescuentoPromo__c.field-meta.xml
<CustomField>
    <fullName>IMP_DescuentoPromo__c</fullName>
    <description>Descuento de promoción de acuerdo a criterios de descuentos promocionales de SAP</description>
    <label>Descuento promoción</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IMP_OmitirDescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>IMP_OmitirDescuentoSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para identificar cuando se omite el descuento sap con base al grupo del cliente 17 Aplicador A y canal 02 Mostrador</description>
    <label>Omitir descuento SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PoliticaDescuento__c.field-meta.xml
<CustomField>
    <fullName>PoliticaDescuento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Política de descuento</label>
    <referenceTo>PoliticaDescuento__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/CanalDistribucion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>E-Commerce</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Obras y Proyectos</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Des. Negocios</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Industriales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Exportación</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Call Center</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Retail</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Ventas Directas</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Mayorista</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Otras Ventas</label>
    </customValue>
    <masterLabel>Canal de distribución</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_de_Cliente.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Distribuidor A</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Distribuidor B</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Distribuidor C</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidor D</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Contratistas A</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Contratistas B</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Contratistas C</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Multimarcas A</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Multimarcas B</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Multimarcas C</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>Obras y Proyectos</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Industriales</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Exportación</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Desarrollo de Negoci</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Call Center</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>Aplicador A</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>Contratistas Plus</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>Retail</label>
    </customValue>
    <masterLabel>Grupo de Cliente</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_de_materiales.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Lineas Generales</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Lineas Mayoristas</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Lineas Populares</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Commodity</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Especiales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Ultra Comodity</label>
    </customValue>
    <masterLabel>Grupo de materiales</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lista_de_precios_SAP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <masterLabel>Lista de precios SAP</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_CreateOrder_CC.cls
/************************************************************************
Name: IMP_CreateOrder_CC
Copyright © 2022 Salesforce
========================================================================
Purpose:
Clase controller que crea un pedido a partir de las partidas de
oportunidad 
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
 2.0      mvilchis@ts4.mx    29/03/2022     
************************************************************************/
public with sharing class IMP_CreateOrder_CC {
   /*******************************************************************
   Purpose: Valida si existen partidas asociadas para crear un pedido
   de lo contrario regresa un mensaje de error.
   Parameters: String oppRec
   Returns: String
   Throws [Exceptions]:
   Information about changes (versions) []:
   ********************************************************************/
    @AuraEnabled
    public static String getOpportunity(String oppRec) {
        String idOrder;
        Opportunity opp =[SELECT Id,StageName,AccountId,Account.grupo__c, Account.clave_delcanal__c, CloseDate,Pricebook2Id,SyncedQuoteId FROM Opportunity WHERE Id =: oppRec ];
        list<OpportunityLineItem> lstOppL = [SELECT Id
                                        , OpportunityId,Product2.Grupo_de_Materiales__c
                                        , TotalPrice, UnitPrice, Quantity, PricebookEntryId, Product2Id,
                                        ProductCode, Opportunity.AccountId, DescuentoAdicional__c,
                                        IMP_DescuentoPromo__c, DescuentoSAP__c, IMP_OmitirDescuentoSAP__c,
                                        Opportunity.Pricebook2.Sucursal__c, Opportunity.Account.grupo__c
                                        , Product2.Lista_precios__c, Product2.Grupo_de_art_culos__c
                                        FROM OpportunityLineItem WHERE OpportunityId =:oppRec];
        if(lstOppL.size() > 0) {
            idOrder=createdOrder(lstOppL, opp);
        }
        else {
            throw new AuraHandledException('No puede crear un pedido, no tiene partidas asociadas');
        }
        return [SELECT Id, OrderNumber FROM Order WHERE Id=:idOrder].OrderNumber;
    }
    /*******************************************************************
    Purpose: Inserta el pedido a partir de la información de la oportunidad.
    Parameters: List<OpportunityLineItem> lstOppItem, Opportunity opp
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    private static String createdOrder(List<OpportunityLineItem> lstOppItem, Opportunity opp) {
        Order prodOrder = new Order (AccountId = opp.AccountId, Status = 'Draft', OpportunityId = opp.Id,
                                    EffectiveDate = opp.CloseDate,Pricebook2Id = opp.Pricebook2Id);
        insert prodOrder;
        createdOrderItem(lstOppItem, opp, prodOrder.Id);
        return prodOrder.Id;
    }
    /*******************************************************************
    Purpose: Crea las partidas del pedido
    Parameters: List<OpportunityLineItem> lstOppItem,String pedidoId
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    private static void createdOrderItem (List<OpportunityLineItem> lstOppItem,Opportunity opor,  String pedidoId) {
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        List<String> lstOpp = new List<String>();
        Map<String,Id> mapOrdOpp = new Map<String,Id>();
        String grupoClientePromo = '';
        String CanalPromocion = '';
        
        try {
            Map<String,Decimal> mapDescuentos = getDiscounts(lstOppItem,pedidoId);
            Map<String,Descuento__c> mapDescuentosPromo = getDiscountsPromo(opor, lstOppItem);
            grupoClientePromo = System.label.IMP_GrupoClientePromo;
            CanalPromocion = System.label.IMP_CanalPromo;

            for(OpportunityLineItem oppl : lstOppItem) {
                OrderItem prodOrderItem = new OrderItem (
                    UnitPrice = oppl.UnitPrice,Quantity = oppl.Quantity,OrderId = pedidoId,
                    PricebookEntryId = oppl.PricebookEntryId,DescuentoSAP__c= mapDescuentos.get(oppl.Id),
                    Product2Id = oppl.Product2Id , DescuentoManual__c =oppl.DescuentoAdicional__c 
                    );

                if(mapDescuentosPromo.containsKey(oppl.Id)){
                    Descuento__c descuento = mapDescuentosPromo.get(oppl.Id);
                    
                    if(opor.Account.clave_delcanal__c == CanalPromocion && opor.Account.grupo__c == grupoClientePromo){
                        prodOrderItem.DescuentoSAP__c = 0;
                        prodOrderItem.IMP_OmitirDescuentoSAP__c = true;
                    }
                    prodOrderItem.IMP_DescuentoPromo__c = descuento.IMP_ImportePorcentaje__c;
                    prodOrderItem.IMP_Descuento__c = descuento.Id;
                }
                lstOrderItem.add(prodOrderItem);
            }
            insert lstOrderItem;

        }
        catch(DmlException e) {
            AuraHandledException errorAura = new AuraHandledException('');
            errorAura.setMessage(e.getMessage());
            throw errorAura;
        }
    }
    /*******************************************************************
    Purpose: Obtiene los descuentos de cada producto
    Parameters: List<OpportunityLineItem> listaProds,String pedidoId
    Returns: Map<String,Decimal> 
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    private static Map<String,Decimal> getDiscounts(List<OpportunityLineItem> listaProds,String pedidoId){
        Map<String,PoliticaDescuento__c> mapDescuentos = new  Map<String,PoliticaDescuento__c> ();
        Map<String,Decimal> mapReturn = new  Map<String,Decimal>();
        Order pedido = [SELECT Id, AccountId,Account.Clave_delcanal__c,Account.Grupo__c FROM Order WHERE Id =: pedidoId];

        for(PoliticaDescuento__c politicaDesc : [SELECT Id,Activa__c,Canaldistribucion__c,GrupoProducto__c, Descuento__c,Grupo_de_cliente_del__c
                                                 FROM PoliticaDescuento__c WHERE Activa__c = true AND Canaldistribucion__c =:pedido.Account.Clave_delcanal__c
                                                 AND Grupo_de_cliente_del__c =:pedido.Account.Grupo__c])
        {
            mapDescuentos.put(politicaDesc.GrupoProducto__c, politicaDesc) ;  
        }
        for(OpportunityLineItem prodOppor: listaProds){
            mapReturn.put(prodOppor.Id,mapDescuentos.containsKey(prodOppor.Product2.Grupo_de_Materiales__c)? mapDescuentos.get(prodOppor.Product2.Grupo_de_Materiales__c).Descuento__c : 0);
        }
        return mapReturn;
    }
    /*******************************************************************
    Purpose: Obtiene los descuentos de promoción de cada producto
    Parameters: List<OpportunityLineItem> listaProds,String pedidoId
    Returns: Map<String,Decimal> 
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    private static Map<String,Descuento__c> getDiscountsPromo(Opportunity opor, List<OpportunityLineItem> listLineOpp){
        Map<String,Descuento__c> mapDescuentos = new  Map<String ,Descuento__c> ();
        List<QuoteLineItem> listaProds = new List<QuoteLineItem>();
        Decimal PrecioTotalDescuentos = 0;
       

        Quote cot = [SELECT Id, isSyncing, Account.grupo__c, Account.clave_delcanal__c
        , Account.OrganizacionVentas__c
        , Account.id_de_sap__c
        , Account.centro_suministrador__c
        , Pricebook2.Lista_de_precios_SAP__c
        ,Requiereaprobacion__c,Pricebook2.Sucursal__c 
        FROM Quote WHERE Id =:opor.SyncedQuoteId];

        Descuento__c descuentoPromo = new Descuento__c();
        IMP_DescuentosManager.WrapperSecuences DiscountsBySecuence = new IMP_DescuentosManager.WrapperSecuences();
        IMP_DescuentosManager.WrapperSecuencesParam param = new IMP_DescuentosManager.WrapperSecuencesParam();
        
        DiscountsBySecuence = IMP_DescuentosManager.getDiscountByQuote(cot);
        
        for(OpportunityLineItem oLineItem: listLineOpp){
            param.OrgVentas = cot.Account.OrganizacionVentas__c;
            param.canalVentas = cot.Account.clave_delcanal__c;
            param.numeroCliente = cot.Account.id_de_sap__c;
            param.numeroMaterial = oLineItem.ProductCode;
            param.OficinaVentas = cot.Pricebook2.Sucursal__c; //Account.centro_suministrador__c , pedido.Pricebook2.Sucursal__c
            param.ListaPrecios = cot.Pricebook2.Lista_de_precios_SAP__c;//cot.Account.Grupo_de_precios__c; 03 Mostrador, 04 Distribuidores, Account.ListaPrecios__c = 03 Mostrador, 04 Distribuidores
            param.GrupoMateriales = oLineItem.Product2.Grupo_de_Materiales__c;
            param.GrupoArticulos = oLineItem.Product2.Grupo_de_art_culos__c;
            param.GrupoClientes = cot.Account.grupo__c;
            param.ClaseDoc = System.label.IMP_ClasePedido;
          
            System.debug('Parametros usados en trigger');
            System.debug(param);

            descuentoPromo = IMP_DescuentosManager.getDiscountByToApply(param, DiscountsBySecuence);
            if(descuentoPromo != null){
                if(descuentoPromo.IMP_ImportePorcentaje__c > 0){
                    mapDescuentos.put(oLineItem.Id, descuentoPromo);
                }
            }
        }

        
        return mapDescuentos;
    }
    
}