force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Credito_Acumulado__c.field-meta.xml
<CustomField>
    <fullName>Credito_Acumulado__c</fullName>
    <label>Crédito Acumulado</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credito_Disponible__c.field-meta.xml
<CustomField>
    <fullName>Credito_Disponible__c</fullName>
    <description>Almacena el crédito del cliente para visualizarlo a nivel cuenta</description>
    <formula>LineaCredito__c - Credito_Acumulado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credito Disponible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ViaPago__c.field-meta.xml
<CustomField>
    <fullName>ViaPago__c</fullName>
    <label>Vía de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>via_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/pedido__c.field-meta.xml
<CustomField>
    <fullName>pedido__c</fullName>
    <description>Número de pedido en SAP</description>
    <externalId>true</externalId>
    <label>ID Pedido SAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/TotalPedido__c.field-meta.xml
<CustomField>
    <fullName>TotalPedido__c</fullName>
    <description>Almacena el total del pedido</description>
    <label>Total de Pedido</label>
    <summarizedField>OrderItem.PrecioTotal__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/ViaPago__c.field-meta.xml
<CustomField>
    <fullName>ViaPago__c</fullName>
    <label>Vía de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>via_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DescuentoManual__c.field-meta.xml
<CustomField>
    <fullName>DescuentoManual__c</fullName>
    <description>Campo usado para almacenar el descuento total.</description>
    <label>Descuento Manual</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>DescuentoSAP__c</fullName>
    <description>Campo usado para capturar el descuento de SAP</description>
    <label>Descuento SAP</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PrecioTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotal__c</fullName>
    <description>Precio total del producto de pedido y el descuento aplicado</description>
    <formula>((1- DescuentoSAP__c )*(UnitPrice * Quantity )  * (1-IMP_DescuentoPromo__c))   *(1- DescuentoManual__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/TS4_SemaforoDisp__c.field-meta.xml
<CustomField>
    <fullName>TS4_SemaforoDisp__c</fullName>
    <defaultValue>&quot;Error&quot;</defaultValue>
    <description>Campo usado para determinar la disponibilidad de un producto.</description>
    <label>Semaforo Disponibilidad</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Lista_de_precios_SAP__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_precios_SAP__c</fullName>
    <label>Lista de precios SAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lista_de_precios_SAP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lista_de_precios_SAP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <masterLabel>Lista de precios SAP</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/via_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>C</fullName>
        <label>Cheque</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>Deposito</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>Efectivo</label>
    </customValue>
    <customValue>
        <fullName>F</fullName>
        <label>Tarjeta de crédito</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Cheque Prod IQ</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>Tarjeta de Débito</label>
    </customValue>
    <customValue>
        <fullName>I</fullName>
        <label>Nota de Credito</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Por Definir</label>
    </customValue>
    <customValue>
        <fullName>T</fullName>
        <label>Transferencia Bancaria</label>
    </customValue>
    <masterLabel>Via de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_PedidoSAPController.cls
/************************************************************************
Name: IMP_PedidoSAPController
Copyright © 2022 Salesforce
========================================================================
Purpose:
Controller
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      rotrejo@ts4.mx    22/03/2022     INITIAL        DEV CSR:
************************************************************************/

public without sharing class IMP_PedidoSAPController {
    
    /*******************************************************************
    Purpose: Obtiene los datos de los productos del pedido, incluyendo la disponbilidad
    Parameters: String pedidoId
    Returns: List<OrderItem>
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    @auraEnabled
    public static Wrapper getDatosPedido(String pedidoId){
        System.debug('Pedido ID: ' + pedidoId);
        List<OrderItem> listItems= [SELECT Id, Product2.ProductCode,DescuentoManual__c ,DescuentoSAP__c,IMP_DescuentoPromo__c, PrecioTotal__c , Product2.Name,TS4_SemaforoDisp__c , Quantity, CurrencyIsoCode, UnitPrice, ListPrice, TotalPrice, OrderItemNumber FROM OrderItem WHERE orderId=:pedidoId];
        System.debug('List de Pedidos: ' + listItems);
        List<String> listaCodigos = new List<String>();
        
        for(OrderItem item:listItems){
            listaCodigos.add(item.Product2.ProductCode);
        }        
        System.debug('List de Codigos: ' + listaCodigos);
        Wrapper newWrapper = new Wrapper();
        try{ 
            Order pedido=[SELECT Id,Ordernumber,Pricebook2Id,pedido__c,Account.clave_delcanal__c, EffectiveDate,TotalAmount,Account.Credito_Disponible__c,Account.Credito_Acumulado__c ,TotalPedido__c, Account.Name,Account.id_de_sap__c,ViaPago__c,Pricebook2.Sucursal__c,
                          Pricebook2.Lista_de_precios_SAP__c FROM Order WHERE Id=:pedidoId];
            Pricebook2 listaPrecios =[SELECT Id,Sucursal__c FROM Pricebook2 WHERE Id=:pedido.Pricebook2Id];
            Map<String,Decimal> mapResponse = new Map<String,Decimal>();
            List<IMP_InventarioManager.cls_ZINVENTARIOS> listProdsResponse =  IMP_InventarioManager.getInventario(listaCodigos,listaPrecios.Sucursal__c);
            newWrapper.pedido=pedido;
            if(listProdsResponse != null){
                for(IMP_InventarioManager.cls_ZINVENTARIOS product:listProdsResponse){
                    if(mapResponse.containsKey(product.MATNR.replaceFirst('^0+', ''))){
                        mapResponse.put(product.MATNR.replaceFirst('^0+', ''),mapResponse.get(product.MATNR.replaceFirst('^0+', ''))+product.CLABS); 
                    }else{
                        mapResponse.put(product.MATNR.replaceFirst('^0+', ''),product.CLABS);
                    }
                }
                for(OrderItem item:listItems){
                    if(mapResponse.containsKey(item.Product2.ProductCode)){
                        if(mapResponse.get(item.Product2.ProductCode) > item.Quantity){
                            item.TS4_SemaforoDisp__c='Success';
                        }else{
                            item.TS4_SemaforoDisp__c='Error';
                        }
                    }else{
                        item.TS4_SemaforoDisp__c='Error';
                    }
                }
                newWrapper.codigo='SUCCESS';
                
            }else{
                for(OrderItem item:listItems){
                    item.TS4_SemaforoDisp__c='Error';
                }
                newWrapper.codigo='ERROR';
            }
           // update listItems;
        }
        catch(Exception e)
        {
            System.debug('IMP_PedidoSAPController : '+ e.getMessage());
            newWrapper.codigo='ERROR';
        }
        newWrapper.listProds=listItems;
        return newWrapper;
    }
    
    /*******************************************************************
    Purpose: Elimina un producto de pedido
    Parameters: String orderItemId
    Returns:
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/ 
     @auraEnabled
    public static void deleteOrderItem(String orderItemId){
        delete [SELECT Id FROM OrderItem WHERE Id=:orderItemId]; 
    }
    
    /*******************************************************************
    Purpose: Obtiene los datos del pedido
    Parameters: String pedidoId
    Returns: Order
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    /*@auraEnabled
    public static Order getPedido(String pedidoId){
        return [SELECT Id,Ordernumber,Pricebook2Id,pedido__c,Account.clave_delcanal__c, EffectiveDate,TotalAmount,Account.Credito_Disponible__c,Account.Credito_Acumulado__c ,TotalPedido__c, Account.Name,Account.id_de_sap__c,ViaPago__c,Pricebook2.Sucursal__c,
                Pricebook2.Lista_de_precios_SAP__c FROM Order WHERE Id=:pedidoId];
    }*/
    
    
    /*******************************************************************
    Purpose: Envia el pedido a SAP
    Parameters: Order pedido
    Returns: Order
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
     @auraEnabled
    public static IMP_EnvioPedidoSAP.Wrapper enviarPedioSAP(Order pedido){
        return IMP_EnvioPedidoSAP.getOrder(pedido);
    }
    
    public class Wrapper{
        @AuraEnabled public List<OrderItem> listProds;
        @AuraEnabled public Order pedido;
        @AuraEnabled public String codigo;
        
    }
}