force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/grupo__c.field-meta.xml
<CustomField>
    <fullName>grupo__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Distribuidor A</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Distribuidor B</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Distribuidor C</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidor D</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Contratistas A</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Contratistas B</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Contratistas C</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Multimarcas A</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Multimarcas B</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Multimarcas C</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Desarrollo de Negoci</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Aplicador A</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Contratistas Plus</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ListaPrecios__c.field-meta.xml
<CustomField>
    <fullName>ListaPrecios__c</fullName>
    <label>Lista de precios SAP</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>03</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OrganizacionVentas__c.field-meta.xml
<CustomField>
    <fullName>OrganizacionVentas__c</fullName>
    <label>Organización de Ventas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GOGA</fullName>
                <label>Gogal</label>
            </value>
            <value>
                <fullName>GRAV</fullName>
                <label>Graviq</label>
            </value>
            <value>
                <fullName>IMPQ</fullName>
                <default>true</default>
                <label>Imperquimia SA de CV</label>
            </value>
            <value>
                <fullName>IQSE</fullName>
                <label>IQ Servicios</label>
            </value>
            <value>
                <fullName>LEMA</fullName>
                <label>Lemma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Requiereaprobacion__c.field-meta.xml
<CustomField>
    <fullName>Requiereaprobacion__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Marque este campo para solicitar el alta de clientes</inlineHelpText>
    <label>¿Requiere Alta?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrecioTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotal__c</fullName>
    <label>Precio total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requiereaprobacion__c.field-meta.xml
<CustomField>
    <fullName>Requiereaprobacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Requiere aprobación?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalPartidas__c.field-meta.xml
<CustomField>
    <fullName>TotalPartidas__c</fullName>
    <label>Total</label>
    <summarizedField>OpportunityLineItem.TotalPrice</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/TotalPartidas__c.field-meta.xml
<CustomField>
    <fullName>TotalPartidas__c</fullName>
    <label>Total</label>
    <summarizedField>OrderItem.UnitPrice</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Grupo_de_art_culos__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_art_culos__c</fullName>
    <label>Grupo de artículos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ESPA</fullName>
                <label>Espacios</label>
            </value>
            <value>
                <fullName>GUARQM</fullName>
                <label>Guardquim</label>
            </value>
            <value>
                <fullName>IMPERC</fullName>
                <label>Impercryl</label>
            </value>
            <value>
                <fullName>NAYA</fullName>
                <label>Naya</label>
            </value>
            <value>
                <fullName>QUIMCR</fullName>
                <label>Quimicret</label>
            </value>
            <value>
                <fullName>SELLAQ</fullName>
                <label>Sellaquim</label>
            </value>
            <value>
                <fullName>SOPORT</fullName>
                <label>Soporte</label>
            </value>
            <value>
                <fullName>DOCFIN</fullName>
                <label>Documento Financiero</label>
            </value>
            <value>
                <fullName>ACCESO</fullName>
                <label>Accesorio</label>
            </value>
            <value>
                <fullName>IQ</fullName>
                <label>Imperquimia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Grupo_de_Materiales__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Materiales__c</fullName>
    <label>Grupo de Materiales</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_de_materiales</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/PrecioTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotal__c</fullName>
    <label>Precio Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Requiereaprobacion__c.field-meta.xml
<CustomField>
    <fullName>Requiereaprobacion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Este campo se marcará cuando la cotización tenga  al menos un descuento en alguno de sus productos.</description>
    <label>¿Requiere aprobación?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TotalPartidas__c.field-meta.xml
<CustomField>
    <fullName>TotalPartidas__c</fullName>
    <label>Total</label>
    <summarizedField>QuoteLineItem.PrecioTotalConDescuentos__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Descuento_adicional__c.field-meta.xml
<CustomField>
    <fullName>Descuento_adicional__c</fullName>
    <description>Este descuento se ingresa de forma manual</description>
    <label>Descuento adicional</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>DescuentoSAP__c</fullName>
    <label>Descuento SAP</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IMP_DescuentoPromo__c.field-meta.xml
<CustomField>
    <fullName>IMP_DescuentoPromo__c</fullName>
    <description>Descuento de promoción de acuerdo a criterios de descuentos promocionales de SAP</description>
    <label>Descuento promoción</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IMP_Disponibilidad__c.field-meta.xml
<CustomField>
    <fullName>IMP_Disponibilidad__c</fullName>
    <label>Disponibilidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IMP_OmitirDescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>IMP_OmitirDescuentoSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para identificar cuando se omite el descuento sap con base al grupo del cliente 17 Aplicador A y canal 02 Mostrador</description>
    <label>Omitir descuento SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PoliticaDescuento__c.field-meta.xml
<CustomField>
    <fullName>PoliticaDescuento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Política de descuento</label>
    <referenceTo>PoliticaDescuento__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrecioTotalConDescuentos__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotalConDescuentos__c</fullName>
    <label>Precio Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_de_materiales.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Lineas Generales</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Lineas Mayoristas</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Lineas Populares</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Commodity</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Especiales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Ultra Comodity</label>
    </customValue>
    <masterLabel>Grupo de materiales</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_CotizadorProductosController.cls
/************************************************************************
Name: IMP_CotizadorProductosController
Copyright © 2022 Salesforce
========================================================================
Purpose:
Class to get information related to the Quote, QuoteLineItems,Products,PricebookEntry,Pricebook2 and show it in the quoter.
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      dmarcos@ts4.mx    12/01/2021     INITIAL        DEV CSR:
************************************************************************/
public without sharing class IMP_CotizadorProductosController {
    /******************************************************************* 
    Purpose: Obtains the information of items of the quote.
    Parameters: Quote cotizacionId.
    Returns: DataQuoteWrapper.
    Throws :
    Information about changes (versions)
    ********************************************************************/
    @auraEnabled
    public static DataQuoteWrapper getInitialData(String cotizacionId){
        DataQuoteWrapper returnData = new dataQuoteWrapper();
        returnData=getAllData(cotizacionId,true);
        return returnData;
    }
    
    /******************************************************************* 
    Purpose: The products that match the search code or description are obtained.
    Parameters: String nombre,Id listaPrecios, Integer pageSize, Integer pageNumber, String  recordId.
    Returns: DataReturnProducts.
    Throws :
    Information about changes (versions)
    ********************************************************************/
    @auraEnabled
    public static DataReturnProducts getProductos(String nombre,Id listaPrecios, Integer pageSize, Integer pageNumber, String  recordId){
        
        String whereArgs;      
        String searchProductBy;
        String searchProductByCode;
        String nombreProducto;
        nombreProducto = nombre;
        
        Quote cot = [SELECT id,Pricebook2Id from Quote WHERE id=:recordId];
        if(cot.Pricebook2Id != listaPrecios){
            cot.Pricebook2Id = listaPrecios;
            update cot; 
        }
               
        if(nombreProducto != null){
            if(nombreProducto.contains(' ')){
                nombreProducto = nombre.replace(' ', '');
            } else{
                nombreProducto = nombre;
            }
            if(nombreProducto.contains(',')){
                searchProductBy='(Product2.ProductCode IN '+ nombreProducto + ' OR Product2.Name IN '+ nombreProducto +')';
            }else{
                searchProductBy='(Product2.Name LIKE \'%' + nombreProducto + '%\' OR Product2.ProductCode LIKE \'%' + nombreProducto + '%\')';
            }
            
            whereArgs = ' IsActive = true AND Product2.IsActive = true AND Pricebook2Id = \'' + cot.Pricebook2Id + '\' AND ' + searchProductBy;
            
        }
        
        Integer resultSize= Database.countQuery('SELECT count() FROM PricebookEntry WHERE ' + whereArgs + ' Limit 2000');
        Integer totalPages = Math.mod(resultSize, pageSize) > 0 ? resultSize / pageSize + 1 : resultSize / pageSize;
        pageNumber = pageNumber > totalPages ? (totalPages == 0 ? 1 : totalPages) : pageNumber;
        Integer pageEnd = pageSize * pageNumber > resultSize ? resultSize : pageSize * pageNumber;
        Integer offset = Math.abs(pageSize * (pageNumber - 1));
        
        list<PricebookEntry> pricebookEntries = Database.query('SELECT Id, Name, UnitPrice,Product2.Grupo_de_art_culos__c, Product2.IsActive, Product2.Name, Product2.Description,Product2.Family, Product2.ProductCode,Product2.Grupo_de_Materiales__c FROM PricebookEntry WHERE ' + whereArgs + 'ORDER BY Product2.Name LIMIT ' + pageSize + ' OFFSET ' + offset);
        DataReturnProducts retornoDatos= new DataReturnProducts();
        
        retornoDatos.listProducts=pricebookEntries;
        retornoDatos.totalProducts=resultSize;
        retornoDatos.totalPages=totalPages;
        retornoDatos.pageEnd=pageEnd;
        retornoDatos.pageNumber=pageNumber;     
        return retornoDatos;
        
    }
    
    public static Map<String,Decimal> updateDisponibilidad(List<String> listaCodigos, String almacen){
        Map<String,Decimal> mapResponse = new Map<String,Decimal>();
        try{
        List<IMP_InventarioManager.cls_ZINVENTARIOS> listProdsResponse =  IMP_InventarioManager.getInventario(listaCodigos,almacen);
        if(listProdsResponse != null){
            for(IMP_InventarioManager.cls_ZINVENTARIOS product:listProdsResponse){
                if(mapResponse.containsKey(product.MATNR.replaceFirst('^0+', ''))){
                    mapResponse.put(product.MATNR.replaceFirst('^0+', ''),mapResponse.get(product.MATNR.replaceFirst('^0+', ''))+product.CLABS); 
                }else{
                    mapResponse.put(product.MATNR.replaceFirst('^0+', ''),product.CLABS);
                }
            }
        }
        }catch(Exception ex){
        }
        return mapResponse;
    }
    
    /******************************************************************* 
    Purpose: Obtains all the information of the quotation , quotation items
    and validates that no inactive products are found in the quote.
    Parameters: Id cotizacionId.
    Returns: DataQuoteWrapper.
    Throws :
    Information about changes (versions)
    ********************************************************************/
    private static DataQuoteWrapper getAllData(Id cotizacionId,boolean flag){
        
        DataQuoteWrapper returnData = new DataQuoteWrapper();
        
        list<Pricebook2> listaPrecios = [SELECT Id, Name, Description FROM Pricebook2 ORDER BY Name ASC]; 
        Double impuestoCotizacion = 0;
        
        Quote cotizacion=[SELECT Id ,Name, Pricebook2Id,Pricebook2.Sucursal__c, CurrencyIsoCode, Opportunity.Id, Opportunity.Name,
                          Status, IsSyncing,TotalPrice,Tax,GrandTotal,Requiereaprobacion__c,Account.Name, Account.ListaPrecios__c,
                          TotalPartidas__c,PrecioTotal__c
                          FROM Quote WHERE Id =: cotizacionId];
        
        if(cotizacion.Pricebook2.Sucursal__c == 'TJ01'){
            impuestoCotizacion = cotizacion.TotalPartidas__c * 0.08;
        }else{
            impuestoCotizacion = cotizacion.TotalPartidas__c * 0.16;
            
        }
        cotizacion.Tax = impuestoCotizacion;
        cotizacion.PrecioTotal__c  = cotizacion.Tax + cotizacion.TotalPartidas__c;
        update cotizacion;
        
        Quote cotizacionUpdate=[SELECT Id ,Name, Pricebook2Id,Pricebook2.Sucursal__c, CurrencyIsoCode, Opportunity.Id, Opportunity.Name,
                                Status, IsSyncing,TotalPrice,Tax,GrandTotal,Requiereaprobacion__c,Account.Name, Account.ListaPrecios__c, 
                                TotalPartidas__c,PrecioTotal__c
                                FROM Quote WHERE Id =: cotizacionId];
        
        list<QuoteLineItem> listQuoteslines=[SELECT Id,Discount, Quantity, TotalPrice,PoliticaDescuento__c,DescuentoSAP__c,IMP_OmitirDescuentoSAP__c,
                                             UnitPrice,PricebookEntryId, PricebookEntry.Id, PricebookEntry.Name, PricebookEntry.UnitPrice,
                                             PricebookEntry.Product2.Id,PricebookEntry.Product2.IsActive,Product2.Name, PricebookEntry.Product2.Description, Product2.Family,
                                             Product2.ProductCode,Product2.Grupo_de_Materiales__c,IMP_Disponibilidad__c,
                                             Product2.IsActive,QuoteId,Descuento_adicional__c,IMP_DescuentoPromo__c, PrecioTotalConDescuentos__c
                                             FROM QuoteLineItem WHERE QuoteId = :cotizacionUpdate.Id ORDER BY CreatedDate];
        
        
        String inactiveProducts=''; 
        List<String> listCodigos = new List<String>();
        for (QuoteLineItem quotedProduct : listQuoteslines) {
            listCodigos.add(quotedProduct.Product2.ProductCode);
            if(quotedProduct.product2.IsActive==false){
                
                inactiveProducts+=quotedProduct.product2.ProductCode+',\n';
                returnData.status='WARNING';
                returnData.mensaje = 'Se encontraron productos inactivos en la cotización : '+inactiveProducts+' .'; 
                
            }
        }
        if(listCodigos.size()>0 && flag){
            Map<String,Decimal> mapResponse = updateDisponibilidad(listCodigos,cotizacion.Pricebook2.Sucursal__c);
            for(QuoteLineItem item:listQuoteslines){
                item.IMP_Disponibilidad__c  = mapResponse.containsKey(item.Product2.ProductCode) ? mapResponse.get(item.Product2.ProductCode):  item.IMP_Disponibilidad__c  != null ? item.IMP_Disponibilidad__c  : 0 ;
            }
            update listQuoteslines;
        }

        returnData.status='SUCCESS';
        returnData.cotizacion=cotizacionUpdate;
        returnData.listQuoteLineItems=listQuoteslines;      
        returnData.listPrecios=listaPrecios;
        
        return returnData;
        
    }
    /******************************************************************* 
    Purpose: When a new product is added to the quote, a quote item is created.
    Parameters: PricebookEntry pbe, Quote cotizacion.
    Returns: DataQuoteWrapper.
    Throws :
    Information about changes (versions)
    ********************************************************************/    
    @auraEnabled
    public static DataQuoteWrapper crearQuoteLineItem(PricebookEntry pbe, String cotizacion){ 
        Integer orden = 0;
        Decimal PrecioTotalDescuentos = 0;
        String grupoClientePromo = '';
        DataQuoteWrapper returnData = new DataQuoteWrapper(); 
        
        list<QuoteLineItem> listQuoteslines=[SELECT Id,Product2.ProductCode,Descuento_adicional__c, DescuentoSAP__c,IMP_OmitirDescuentoSAP__c, PrecioTotalConDescuentos__c 
                                             FROM QuoteLineItem WHERE QuoteId = :cotizacion ORDER BY CreatedDate];
        orden = listQuoteslines.size() + 1;
        Quote cot = [SELECT Id,Account.grupo__c, Account.clave_delcanal__c
                    , Account.OrganizacionVentas__c
                    , Account.id_de_sap__c
                    , Account.centro_suministrador__c
                    , Pricebook2.Lista_de_precios_SAP__c
                    ,Requiereaprobacion__c,Pricebook2.Sucursal__c 
                    FROM Quote WHERE Id =:cotizacion];
        Map<String,Decimal> mapResponse = updateDisponibilidad(new List<String>{pbe.Product2.ProductCode},cot.Pricebook2.Sucursal__c);
        
        try{
            QuoteLineItem quoteLineItem = new QuoteLineItem(
                QuoteId=cotizacion,
                PricebookEntryId = pbe.Id,
                Quantity = 1,
                Discount = 0,
                IMP_OmitirDescuentoSAP__c = false,
                UnitPrice = pbe.UnitPrice);

            quoteLineItem.IMP_Disponibilidad__c = mapResponse.containsKey(pbe.Product2.ProductCode)? mapResponse.get(pbe.Product2.ProductCode):0;


            insert quoteLineItem;
            returnData=getAllData(cotizacion,false);
            returnData.status='SUCCESS';
            returnData.mensaje= 'Guardado Exitoso.';  


        }
        catch(Exception e){
            System.debug(e.getMessage());
            System.debug(e.getLineNumber());
            returnData.status='ERROR';
            returnData.mensaje = 'ERROR--'+e.getMessage()+e.getLineNumber();
        }
        
        return returnData;
    }
    @auraEnabled  
    public static DataQuoteWrapper deleteQuoteLineItem(QuoteLineItem qli){
        DataQuoteWrapper returnData = new DataQuoteWrapper();
        delete qli;
        returnData=getAllData(qli.QuoteId, false);
        returnData.status='SUCCESS';
        return returnData;
    }

    /******************************************************************* 
    Purpose: Quote items are updated.
    Parameters: QuoteLineItem productEdit, String tipoACampo.
    Returns: DataQuoteWrapper.
    Throws :
    Information about changes (versions)
    ********************************************************************/    
    @auraEnabled
    public static DataQuoteWrapper updateQuoteLineItem(QuoteLineItem productEdit, String tipoACampo){
        DataQuoteWrapper returnData = new DataQuoteWrapper();
        update productEdit;
        System.debug('Id: '+productEdit.Id);
        try{
             
            QuoteLineItem quoteLine=[SELECT Id,Discount,IMP_Disponibilidad__c ,Quantity, TotalPrice,Descuento_adicional__c,
                                         UnitPrice, PricebookEntry.Id, PricebookEntry.Name, PricebookEntry.UnitPrice,
                                         PricebookEntry.Product2.Id,PricebookEntry.Product2.IsActive,Product2.Name, PricebookEntry.Product2.Description, Product2.Family,
                                         Product2.ProductCode,QuoteId,DescuentoSAP__c,IMP_DescuentoPromo__c, IMP_OmitirDescuentoSAP__c, PrecioTotalConDescuentos__c
                                         FROM QuoteLineItem WHERE Id = :productEdit.Id];
            quoteLine.Quantity = productEdit.Quantity;  
            quoteLine.PrecioTotalConDescuentos__c = quoteLine.TotalPrice;
            if(quoteLine.Descuento_adicional__c !=null){
                   quoteLine.PrecioTotalConDescuentos__c = quoteLine.TotalPrice - (quoteLine.TotalPrice * (quoteLine.Descuento_adicional__c / 100));
            }

            if(quoteLine.IMP_DescuentoPromo__c !=null){
                
                quoteLine.PrecioTotalConDescuentos__c = quoteLine.PrecioTotalConDescuentos__c - (quoteLine.PrecioTotalConDescuentos__c * (quoteLine.IMP_DescuentoPromo__c / 100));
            }
            
            update quoteLine;
            Quote cotizacionUpdate=[SELECT Id ,Name, Pricebook2Id,Pricebook2.Sucursal__c, CurrencyIsoCode, Opportunity.Id, Opportunity.Name,PrecioTotal__c, 
                                Status, IsSyncing,TotalPrice,Tax,GrandTotal,Requiereaprobacion__c,Account.Name, Account.ListaPrecios__c, TotalPartidas__c
                                FROM Quote WHERE Id =: productEdit.QuoteId LIMIT 1];
            Double impuestoCotizacion = 0;
            if(cotizacionUpdate.Pricebook2.Sucursal__c == 'TJ01'){
                impuestoCotizacion = cotizacionUpdate.TotalPartidas__c * 0.08;
            }else{
                impuestoCotizacion = cotizacionUpdate.TotalPartidas__c * 0.16;
                
            }
            cotizacionUpdate.Tax = impuestoCotizacion;
            cotizacionUpdate.PrecioTotal__c  = cotizacionUpdate.Tax + cotizacionUpdate.TotalPartidas__c;
            update cotizacionUpdate;
            returnData.cotizacion = cotizacionUpdate;
            returnData.quoteLineProduct = quoteLine;
            returnData.status='SUCCESS';
            returnData.mensaje= 'Se ha actualizado correctamente.';

        }
        catch(Exception e){
            returnData.status='ERROR';
            returnData.mensaje=e.getMessage();
            System.debug(e.getLineNumber()+' - '+ e.getMessage());
            
        }
        
        return returnData;
    }
/******************************************************************* 
Purpose: Update the QuoteLineItem with the added discount
Parameters: QuoteLineItem productEdit, Double valueDesc.
Returns: DataQuoteWrapper.
Throws :
Information about changes (versions)
********************************************************************/     
    @auraEnabled
    public static DataQuoteWrapper procesoDescuento(QuoteLineItem productEdit, Double valueDesc){
        DataQuoteWrapper returnData = new DataQuoteWrapper();
        update productEdit;
        
        Double descuentoAdicional  = 0;
        Double descuentoPromo = 0;
        
        try{            
            
            QuoteLineItem quotesLines=[SELECT Id,Discount,Quantity, TotalPrice,Descuento_adicional__c,
                                       UnitPrice, PricebookEntry.Id, PricebookEntry.Name, PricebookEntry.UnitPrice,
                                       PricebookEntry.Product2.Id,PricebookEntry.Product2.IsActive,Product2.Name, PricebookEntry.Product2.Description, Product2.Family,
                                       Product2.ProductCode,QuoteId,DescuentoSAP__c, IMP_OmitirDescuentoSAP__c, IMP_DescuentoPromo__c, PrecioTotalConDescuentos__c 
                                       FROM QuoteLineItem WHERE Id = :productEdit.Id];
            quotesLines.Descuento_adicional__c = valueDesc;
            descuentoAdicional = valueDesc / 100;
            
            quotesLines.PrecioTotalConDescuentos__c = quotesLines.TotalPrice - (quotesLines.TotalPrice * descuentoAdicional);
            if(quotesLines.IMP_DescuentoPromo__c != null){
                descuentoPromo = quotesLines.IMP_DescuentoPromo__c / 100;
                quotesLines.PrecioTotalConDescuentos__c = quotesLines.PrecioTotalConDescuentos__c  - (quotesLines.PrecioTotalConDescuentos__c * descuentoPromo);
            }
            update quotesLines;

            Quote cotizacion=[SELECT Id ,Name, Pricebook2Id,Pricebook2.Sucursal__c, CurrencyIsoCode, Opportunity.Id, Opportunity.Name,PrecioTotal__c, 
                                Status, IsSyncing,TotalPrice,Tax,GrandTotal,Requiereaprobacion__c,Account.Name, Account.ListaPrecios__c, TotalPartidas__c 
                                FROM Quote WHERE Id =: productEdit.QuoteId LIMIT 1];
            Double impuestoCotizacion = 0;
            if(cotizacion.Pricebook2.Sucursal__c == 'TJ01'){
                impuestoCotizacion = cotizacion.TotalPartidas__c * 0.08;
            }else{
                impuestoCotizacion = cotizacion.TotalPartidas__c * 0.16;
                
            }
            cotizacion.Tax = impuestoCotizacion;
            cotizacion.PrecioTotal__c  = cotizacion.Tax + cotizacion.TotalPartidas__c;
            update cotizacion;
            list<QuoteLineItem> listAllQuoteslines=[SELECT Id,IMP_Disponibilidad__c,Product2.ProductCode,Descuento_adicional__c, DescuentoSAP__c,IMP_DescuentoPromo__c, IMP_OmitirDescuentoSAP__c, QuoteId,PrecioTotalConDescuentos__c
                                                    FROM QuoteLineItem WHERE QuoteId = :productEdit.QuoteId];
            
            
            returnData.cotizacion=[SELECT Id ,Name, Pricebook2Id, Pricebook2.Sucursal__c,CurrencyIsoCode, Opportunity.Id, Opportunity.Name,TotalPrice,Tax,
                                   GrandTotal, Requiereaprobacion__c, TotalPartidas__c,PrecioTotal__c
                                   FROM Quote WHERE Id =: productEdit.QuoteId];
            returnData.quoteLineProduct=[SELECT Id,IMP_Disponibilidad__c,Discount,Quantity, TotalPrice,Descuento_adicional__c,
                                         UnitPrice, PricebookEntry.Id, PricebookEntry.Name, PricebookEntry.UnitPrice,
                                         PricebookEntry.Product2.Id,PricebookEntry.Product2.IsActive,Product2.Name, PricebookEntry.Product2.Description, Product2.Family,
                                         Product2.ProductCode,QuoteId, DescuentoSAP__c,IMP_OmitirDescuentoSAP__c, IMP_DescuentoPromo__c, PrecioTotalConDescuentos__c
                                         FROM QuoteLineItem WHERE Id = :productEdit.Id];

            for(Integer i=0; i<listAllQuoteslines.size();i++){
                if(listAllQuoteslines[i].Descuento_adicional__c !=0){
                    returnData.cotizacion.Requiereaprobacion__c = true;	
                    
                }
            }
            update returnData.cotizacion;
            update returnData.quoteLineProduct;

            returnData.status='SUCCESS';
            returnData.mensaje= 'Se ha actualizado correctamente.';
            
        }catch(DmlException ex){
            System.debug('procesoDescuento');
            System.debug(ex.getMessage() + ', ' + ex.getCause() + ', ' + ex.getLineNumber());
            returnData.mensaje = 'No se pudo actualizar  :' + ex.getMessage();
            returnData.status = 'Error';
        }
        return returnData;
        
    }
   /******************************************************************* 
    Purpose: Inner class for Declaration of variables to get the information.
    ********************************************************************/ 
    public class DataReturnProducts{
        @auraEnabled public list<PricebookEntry> listProducts {get;set;}
        @auraEnabled public Integer totalProducts;
        @auraEnabled public Integer totalPages;
        @auraEnabled public Integer pageEnd;
        @auraEnabled public Integer pageNumber; 
    }
    /******************************************************************* 
    Purpose: Inner class for Declaration of variables to get the information.
    ********************************************************************/    
    public class DataQuoteWrapper{
        @auraEnabled public Quote cotizacion {get; set;}
        @auraEnabled public list<QuoteLineItem> listQuoteLineItems {get; set;}
        @auraEnabled public QuoteLineItem quoteLineProduct {get; set;}
        @AuraEnabled public  string mensaje {get; set;}
        @auraEnabled public String status {get;set;}
        @auraEnabled public list<Pricebook2> listPrecios {get;set;}
    }
    
}