force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/grupo__c.field-meta.xml
<CustomField>
    <fullName>grupo__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Distribuidor A</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Distribuidor B</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Distribuidor C</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidor D</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Contratistas A</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Contratistas B</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Contratistas C</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Multimarcas A</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Multimarcas B</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Multimarcas C</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Desarrollo de Negoci</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Aplicador A</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Contratistas Plus</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OrganizacionVentas__c.field-meta.xml
<CustomField>
    <fullName>OrganizacionVentas__c</fullName>
    <label>Organización de Ventas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GOGA</fullName>
                <label>Gogal</label>
            </value>
            <value>
                <fullName>GRAV</fullName>
                <label>Graviq</label>
            </value>
            <value>
                <fullName>IMPQ</fullName>
                <default>true</default>
                <label>Imperquimia SA de CV</label>
            </value>
            <value>
                <fullName>IQSE</fullName>
                <label>IQ Servicios</label>
            </value>
            <value>
                <fullName>LEMA</fullName>
                <label>Lemma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Descuento__c/Descuento__c.object-meta.xml
<CustomObject>
    <label>Descuento</label>
    <nameField>
        <label>Nombre de Descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Descuento__c/fields/IMP_CanalVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_CanalVentas__c</fullName>
    <description>Canal de distribución que permite la entrega de la mercancía o prestación de servicios. Se debe enviar con clave SAP.</description>
    <label>Canal de ventas</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_ClaseCondicion__c.field-meta.xml
<CustomField>
    <fullName>IMP_ClaseCondicion__c</fullName>
    <description>La clase de condición indica, por ejemplo, si el sistema debe utilizar recargos o descuentos u otros elementos de precios como los costes de transporte e impuestos en la determinación de precios.</description>
    <label>Clase de condición</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_ClaseDocumentoVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_ClaseDocumentoVentas__c</fullName>
    <label>Clase de documento de ventas</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_FechaFinal__c.field-meta.xml
<CustomField>
    <fullName>IMP_FechaFinal__c</fullName>
    <description>Fecha en la que deja de tener vigencia el registro de condición.</description>
    <label>Fecha final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_FechaInicial__c.field-meta.xml
<CustomField>
    <fullName>IMP_FechaInicial__c</fullName>
    <description>Fecha a partir de la cual es válida la condición.</description>
    <label>Fecha inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_GrupoArticulos__c.field-meta.xml
<CustomField>
    <fullName>IMP_GrupoArticulos__c</fullName>
    <label>Grupo de artículos</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_GrupoClientes__c.field-meta.xml
<CustomField>
    <fullName>IMP_GrupoClientes__c</fullName>
    <description>a pertenencia de un cliente a un determinado grupo se define ya sea en el registro maestro del solicitante o bien directamente en el documento de ventas.</description>
    <label>Grupo de clientes</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_GrupoMateriales__c.field-meta.xml
<CustomField>
    <fullName>IMP_GrupoMateriales__c</fullName>
    <description>El grupo de materiales es la agrupación de materiales para los que son válidas las mismas condiciones.</description>
    <label>Grupo de materiales</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IMP_IdExterno__c</fullName>
    <description>Campo usado para almacenar el id externo de los descuentos</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_ImportePorcentaje__c.field-meta.xml
<CustomField>
    <fullName>IMP_ImportePorcentaje__c</fullName>
    <description>Importe o porcentaje que establece de qué modo debe calcular el sistema esta condición al efectuar la determinación automática de precios. La clase de condición determina si se trata de un importe fijo o de un porcentaje.</description>
    <label>Importe/Porcentaje</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_ListaPrecios__c.field-meta.xml
<CustomField>
    <fullName>IMP_ListaPrecios__c</fullName>
    <label>Lista de precios</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_Lote__c.field-meta.xml
<CustomField>
    <fullName>IMP_Lote__c</fullName>
    <description>El número de lote es la asignación que se le da a el material fabricado en lotes, partidas o lotes de producción a un lote determinado de forma unívoca.</description>
    <label>Lote</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_NumeroCliente__c.field-meta.xml
<CustomField>
    <fullName>IMP_NumeroCliente__c</fullName>
    <description>Número de cliente registrado en SAP por el cual se debe filtrar la información a consultar.</description>
    <label>Número de cliente</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_NumeroMaterial__c.field-meta.xml
<CustomField>
    <fullName>IMP_NumeroMaterial__c</fullName>
    <description>ID del material registrado en SAP.</description>
    <label>Número material</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_OficinaVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_OficinaVentas__c</fullName>
    <label>Oficina de ventas</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_OrganizacionVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_OrganizacionVentas__c</fullName>
    <description>Establece la organización de ventas responsable del tratamiento del pedido.</description>
    <label>Organización de ventas</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_SecuenciaAcceso__c.field-meta.xml
<CustomField>
    <fullName>IMP_SecuenciaAcceso__c</fullName>
    <label>Secuencia de acceso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A305</fullName>
            </value>
            <value>
                <fullName>A999</fullName>
            </value>
            <value>
                <fullName>A993</fullName>
            </value>
            <value>
                <fullName>A996</fullName>
            </value>
            <value>
                <fullName>A997</fullName>
            </value>
            <value>
                <fullName>A940</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_UnidadCondicion__c.field-meta.xml
<CustomField>
    <fullName>IMP_UnidadCondicion__c</fullName>
    <label>Unidad de condición(Moneda o Porcentaje)</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/IMP_Valido__c.field-meta.xml
<CustomField>
    <fullName>IMP_Valido__c</fullName>
    <formula>IMP_FechaInicial__c &lt;= TODAY() &amp;&amp;  IMP_FechaFinal__c &gt;= TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valido</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_CanalVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_CanalVentas__c</fullName>
    <label>Organización de ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_NumeroCliente__c.field-meta.xml
<CustomField>
    <fullName>IMP_NumeroCliente__c</fullName>
    <label>Número de cliente</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IMP_OficinaVentas__c.field-meta.xml
<CustomField>
    <fullName>IMP_OficinaVentas__c</fullName>
    <label>Oficina de ventas</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Lista_de_precios_SAP__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_precios_SAP__c</fullName>
    <label>Lista de precios SAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lista_de_precios_SAP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lista_de_precios_SAP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Mostrador</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Distribuidores</label>
    </customValue>
    <masterLabel>Lista de precios SAP</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_DescuentosManager.cls
/************************************************************************
Name: IMP_DescuentosManager
Copyright © 2023 Salesforce
========================================================================
Purpose:
Servicio web para la consulta de descuentos desde SAP 
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
3.0      rotrejo@ts4.mx     09/05/2023     
************************************************************************/
public inherited sharing class IMP_DescuentosManager {

    public List<T_A000> T_A305;
    public List<T_A000> T_A940;
    public List<T_A000> T_A993;
    public List<T_A000> T_A996;
    public List<T_A000> T_A997;
    public List<T_A000> T_A999;
    
    public class T_A000{
        public String KSCHL;//Clase de Condición
        public String VKORG;//Organizacion de Ventas
        public String VTWEG;//Canal de Ventas
        public String KUNNR;//Numero del cliente
        public String MATNR;//Número del material
        public String KBETR;//Importe/Porcentaje
        public String KONWA;//Unidad de condición (Moneda o porcentaje)
        public String DATAB;//Fecha Inicial
        public String DATBI;//Fecha Final
        public String VKBUR;//Oficina de Ventas
        public String CHARG;//Lote
        public String PLTYP;//Lista de Precios
        public String KDGRP;//Grupo de Clientes
        public String MATKL;//Grupo de Articulos
        public String KONDM;//Grupo de Materiales      
        public String AUART_SD;//Clase de Documento de Ventas
        public String KNUMH;
        
    }

    
    /*******************************************************************
    Purpose: Actualiza el listado de descuento.
    Parameters:
    Returns: 
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    public static void upsertDiscounts(){
        IMP_DescuentosManager newDiscount = new IMP_DescuentosManager();
        List<IMP_DescuentosManager.T_A000> listDiscount = new  List<IMP_DescuentosManager.T_A000>();
        IMP_DescuentosManager.T_A000 itemDiscount = new IMP_DescuentosManager.T_A000();
        listDiscount.add(itemDiscount);
        newDiscount.T_A305 = listDiscount;
        newDiscount.T_A940 = listDiscount;
        newDiscount.T_A993 = listDiscount;
        newDiscount.T_A996 = listDiscount;
        newDiscount.T_A997 = listDiscount;
        newDiscount.T_A999 = listDiscount;
        String body = JSON.serialize(newDiscount);
        HttpResponse response = IMP_CalloutUtils.getResponse(body,IMP_ServiceConstants.DESCUENTOS_API_URL);
        List<Descuento__c> listDescuento = new List<Descuento__c>();
        Set<String> setId = new  Set<String>();
        System.debug('Body '+response.getBody());
        IMP_DescuentosManager discountResponse = (IMP_DescuentosManager)JSON.deserialize(response.getBody(),IMP_DescuentosManager.class); 
        for(IMP_DescuentosManager.T_A000 descuento: discountResponse.T_A305){
            listDescuento.add(getDescuento('A305',descuento));
            setId.add(descuento.KNUMH);
        }
        for(IMP_DescuentosManager.T_A000 descuento: discountResponse.T_A999){
            listDescuento.add(getDescuento('A999',descuento));
            setId.add(descuento.KNUMH);
        }
        for(IMP_DescuentosManager.T_A000 descuento: discountResponse.T_A993){
            listDescuento.add(getDescuento('A993',descuento));
            setId.add(descuento.KNUMH);
        }
        for(IMP_DescuentosManager.T_A000 descuento: discountResponse.T_A996){
            listDescuento.add(getDescuento('A996',descuento));
            setId.add(descuento.KNUMH);
        }
        for(IMP_DescuentosManager.T_A000 descuento: discountResponse.T_A997){
            listDescuento.add(getDescuento('A997',descuento));
            setId.add(descuento.KNUMH);
        }
        for(IMP_DescuentosManager.T_A000 descuento: discountResponse.T_A940){
            listDescuento.add( getDescuento('A940',descuento));
            setId.add(descuento.KNUMH);
        } 
        System.debug('LISTA DE DESC');
        System.debug(listDescuento.size());
        List<Descuento__c> listDesc = [SELECT Id,IMP_IdExterno__c,IMP_SecuenciaAcceso__c,IMP_FechaFinal__c,Name FROM Descuento__c WHERE IMP_IdExterno__c NOT IN : setId];
        for(Descuento__c descDesco: listDesc){
            System.debug(descDesco.IMP_SecuenciaAcceso__c+'-'+descDesco.IMP_IdExterno__c);
            descDesco.IMP_FechaFinal__c = date.today()-1;
            
        }
        System.debug(listDescuento);
        Database.executeBatch(new IMP_BatchDescuentos(listDesc),1000);  
        Database.executeBatch(new BatchUpsertDiscounts(listDescuento),1000);  
        

        /*List<Database.SaveResult> resultUpdate = Database.update(listDesc, FALSE);
        for(Database.SaveResult itemResult :resultUpdate ){
            if(!itemResult.isSuccess()){
                system.debug(itemResult.getErrors());
            }
        }
        List<Database.UpsertResult> results = Database.upsert(listDescuento,Descuento__c.IMP_IdExterno__c , FALSE);
        for(Database.UpsertResult itemResult : results){
            if(!itemResult.isSuccess()){
                system.debug(itemResult.getErrors());
            }
        }*/
    }
    
    
    /*******************************************************************
    Purpose: Obtiene el descuento por cotización
    Parameters:Quote
    Returns:WrapperSecuences 
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    public static WrapperSecuences getDiscountByQuote(Quote quote){
        WrapperSecuences wrapperReturn = new WrapperSecuences();
        Map<String,Descuento__c> mapSecuenceA305 = new  Map<String,Descuento__c>();
        Map<String,Descuento__c> mapSecuenceA999 = new  Map<String,Descuento__c>();
        Map<String,List<Descuento__c>> mapSecuenceA999Aux = new  Map<String,List<Descuento__c>>();
        Map<String,Descuento__c> mapSecuenceA993 = new  Map<String,Descuento__c>();
        Map<String,Descuento__c> mapSecuenceA996 = new  Map<String,Descuento__c>();
        Map<String,Descuento__c> mapSecuenceA997 = new  Map<String,Descuento__c>();
        Map<String,Descuento__c> mapSecuence9A40 = new  Map<String,Descuento__c>();

        for(Descuento__c disc : [SELECT Id, IMP_ClaseCondicion__c, IMP_OrganizacionVentas__c, IMP_CanalVentas__c, IMP_NumeroCliente__c,
                                      IMP_NumeroMaterial__c, IMP_ImportePorcentaje__c, IMP_UnidadCondicion__c, IMP_FechaInicial__c, 
                                      IMP_FechaFinal__c, IMP_OficinaVentas__c, IMP_Lote__c, IMP_ListaPrecios__c, IMP_GrupoClientes__c,
                                      IMP_GrupoArticulos__c, IMP_GrupoMateriales__c, IMP_ClaseDocumentoVentas__c, IMP_SecuenciaAcceso__c,
                                      IMP_Valido__c FROM Descuento__c  WHERE IMP_Valido__c = true  AND 
                                      ((IMP_OrganizacionVentas__c=:quote.Account.OrganizacionVentas__c AND IMP_CanalVentas__c=:quote.Account.clave_delcanal__c AND IMP_NumeroCliente__c=:quote.Account.id_de_sap__c)
                                      OR (IMP_OrganizacionVentas__c=:quote.Account.OrganizacionVentas__c AND IMP_OficinaVentas__c=:quote.Pricebook2.Sucursal__c AND IMP_ListaPrecios__c =: quote.Pricebook2.Lista_de_precios_SAP__c)
                                      OR IMP_GrupoClientes__c=:quote.Account.grupo__c
                                      OR (IMP_OrganizacionVentas__c=:quote.Account.OrganizacionVentas__c AND  IMP_OficinaVentas__c=:quote.Pricebook2.Sucursal__c AND IMP_GrupoClientes__c=:quote.Account.grupo__c )
                                      OR IMP_ClaseDocumentoVentas__c='TA')
                                      ORDER BY IMP_FechaInicial__c ASC]){
                                          if(disc.IMP_SecuenciaAcceso__c=='A305'){
                                              mapSecuenceA305.put(disc.IMP_OrganizacionVentas__c+'-'+disc.IMP_CanalVentas__c+'-'+disc.IMP_NumeroCliente__c+'-'+disc.IMP_NumeroMaterial__c, disc);
                                          }
                                          if(disc.IMP_SecuenciaAcceso__c=='A999'){
                                             // mapSecuenceA999.put(disc.IMP_OrganizacionVentas__c+'-'+disc.IMP_OficinaVentas__c+'-'+disc.IMP_ListaPrecios__c+'-'+disc.IMP_NumeroMaterial__c+'-'+disc.IMP_Lote__c, disc);
                                              if(!mapSecuenceA999Aux.containsKey(disc.IMP_NumeroMaterial__c)){
                                                  mapSecuenceA999Aux.put(disc.IMP_NumeroMaterial__c, new List<Descuento__c>());
                                              }
                                              mapSecuenceA999Aux.get(disc.IMP_NumeroMaterial__c).add(disc);
                                          }
                                          if(disc.IMP_SecuenciaAcceso__c=='A993'){
                                              mapSecuenceA993.put(disc.IMP_GrupoClientes__c+'-'+disc.IMP_GrupoArticulos__c, disc);
                                          }
                                          if(disc.IMP_SecuenciaAcceso__c=='A996'){
                                              mapSecuenceA996.put(disc.IMP_OrganizacionVentas__c+'-'+disc.IMP_OficinaVentas__c+'-'+disc.IMP_ListaPrecios__c+'-'+disc.IMP_NumeroMaterial__c, disc);
                                          }
                                          if(disc.IMP_SecuenciaAcceso__c=='A997'){
                                              mapSecuenceA997.put(disc.IMP_OrganizacionVentas__c+'-'+disc.IMP_OficinaVentas__c+'-'+disc.IMP_GrupoClientes__c+'-'+disc.IMP_GrupoMateriales__c, disc);
                                          }
                                          if(disc.IMP_SecuenciaAcceso__c=='A940'){
                                              mapSecuence9A40.put(disc.IMP_ClaseDocumentoVentas__c, disc);
                                          }
                                   
                                      }
        for(String key : mapSecuenceA999Aux.keySet()){
            System.debug('--------------------');
            List<String> listLotes = new  List<String>();
            System.debug('Número del Material '+ key);
            System.debug( mapSecuenceA999Aux.get(key));
            Map<String,Descuento__c> mapDescLote = new Map<String,Descuento__c>();
            for(Descuento__c disc : mapSecuenceA999Aux.get(key)){
                listLotes.add(disc.IMP_Lote__c);
                mapDescLote.put(disc.IMP_Lote__c,disc);
            }
            listLotes.sort();
            String lote = listLotes.size()>=1 ? listLotes.get(0): '';
            System.debug('LOTE CORRECTO ::'+ lote);  
            mapSecuenceA999.put(mapSecuenceA999Aux.get(key).get(0).IMP_OrganizacionVentas__c+'-'+mapSecuenceA999Aux.get(key).get(0).IMP_OficinaVentas__c+'-'+mapSecuenceA999Aux.get(key).get(0).IMP_ListaPrecios__c+'-'+key, mapDescLote.get(lote));
        }
        
        for(String key : mapSecuenceA305.keySet()){
            System.debug('Llave -> A305 ('+ key+')');
            System.debug(mapSecuenceA305.get(key));
        }
        
        for(String key : mapSecuenceA999.keySet()){
            System.debug('Llave -> A999 ('+ key+')');
            System.debug(mapSecuenceA999.get(key));
        }
        System.debug('-------------------------');
        for(String key : mapSecuenceA993.keySet()){
            System.debug('Llave -> A993 ('+ key+')');
            System.debug(mapSecuenceA993.get(key));
        }
        System.debug('-------------------------');
        for(String key : mapSecuenceA996.keySet()){
            System.debug('Llave -> A996 ('+ key+')');
            System.debug(mapSecuenceA996.get(key));
        }
        System.debug('-------------------------');
        for(String key : mapSecuenceA997.keySet()){
            System.debug('Llave -> A997 ('+ key+')');
            System.debug(mapSecuenceA997.get(key));
        }
        System.debug('-------------------------');
        for(String key : mapSecuence9A40.keySet()){
            System.debug('Llave -> A940 ('+ key+')');
            System.debug(mapSecuence9A40.get(key));
        }

        wrapperReturn.mapSecuenceA305=mapSecuenceA305;
        wrapperReturn.mapSecuenceA999=mapSecuenceA999;
        wrapperReturn.mapSecuenceA993=mapSecuenceA993;
        wrapperReturn.mapSecuenceA996=mapSecuenceA996;
        wrapperReturn.mapSecuenceA997=mapSecuenceA997;
        wrapperReturn.mapSecuence9A40=mapSecuence9A40;
        return wrapperReturn;
    }

    /*******************************************************************
    Purpose: Obtiene el que aplica
    Parameters: WrapperSecuencesParam Param, WrapperSecuences DiscountsBySecuence
    Returns: Descuento__c 
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    public static Descuento__c getDiscountByToApply(WrapperSecuencesParam Param, WrapperSecuences DiscountsBySecuence){
       
        Descuento__c descuentoPromo = new Descuento__c();
        String sKeyA305 = Param.OrgVentas +'-'+ Param.canalVentas +'-'+ Param.numeroCliente +'-'+ Param.numeroMaterial; //Ok, si aplica número de material
        String sKeyA999 = Param.OrgVentas + '-'+ Param.OficinaVentas +'-'+ Param.ListaPrecios +'-'+ Param.numeroMaterial; //Ok, si aplica número de material, aplica el lote, no se ha ubicado el campo en SF?
        String sKeyA993 = Param.GrupoClientes +'-'+ Param.GrupoArticulos; // Gr.client.-Gpo.artíc va sin material
        String sKeyA996 = Param.OrgVentas +'-'+ Param.OficinaVentas +'-'+ Param.ListaPrecios + '-'+Param.numeroMaterial; //OK
        String sKeyA997 = Param.OrgVentas +'-'+ Param.OficinaVentas +'-'+ Param.GrupoClientes + '-'+ Param.GrupoMateriales; //En lugar de numeroMaterial es GrupoMateriales
        String sKey9A40 = Param.ClaseDoc;        
        System.debug('Secuencia sKeyA305: ' + sKeyA305);
        System.debug('Secuencia sKeyA999: ' + sKeyA999);
        System.debug('Secuencia sKeyA993: ' + sKeyA993);
        System.debug('Secuencia sKeyA996: ' + sKeyA996);
        System.debug('Secuencia sKeyA997: ' + sKeyA997);
        System.debug('Secuencia sKey9A40: ' + sKey9A40);
        if(DiscountsBySecuence.mapSecuenceA305.containsKey(sKeyA305) ){ 
            descuentoPromo = DiscountsBySecuence.mapSecuenceA305.get(sKeyA305);
            System.debug('Secuencia encontrada sKeyA305: ' + sKeyA305);
        }
        else if(DiscountsBySecuence.mapSecuenceA999.containsKey(sKeyA999)){
            descuentoPromo = DiscountsBySecuence.mapSecuenceA999.get(sKeyA999);
        }
        else if(DiscountsBySecuence.mapSecuenceA993.containsKey(sKeyA993)){
            descuentoPromo = DiscountsBySecuence.mapSecuenceA993.get(sKeyA993);
        }
        else if(DiscountsBySecuence.mapSecuenceA996.containsKey(sKeyA996)){
            descuentoPromo = DiscountsBySecuence.mapSecuenceA996.get(sKeyA996);
        }
        else if(DiscountsBySecuence.mapSecuenceA997.containsKey(sKeyA997)){
            descuentoPromo = DiscountsBySecuence.mapSecuenceA997.get(sKeyA997);
        }
        else if(DiscountsBySecuence.mapSecuence9A40.containsKey(sKey9A40)){
            descuentoPromo = DiscountsBySecuence.mapSecuence9A40.get(sKey9A40);
        }
        System.debug('Descuento promo: '+ descuentoPromo);
        return descuentoPromo;
    }
    
    
    public class WrapperSecuences{
        @AuraEnabled public Map<String,Descuento__c> mapSecuenceA305;
        @AuraEnabled public Map<String,Descuento__c> mapSecuenceA999;
        @AuraEnabled public Map<String,Descuento__c> mapSecuenceA993;
        @AuraEnabled public Map<String,Descuento__c> mapSecuenceA996;
        @AuraEnabled public Map<String,Descuento__c> mapSecuenceA997;
        @AuraEnabled public Map<String,Descuento__c> mapSecuence9A40;
    }
    public class WrapperSecuencesParam{
        @AuraEnabled public String OrgVentas;
        @AuraEnabled public String canalVentas;
        @AuraEnabled public String numeroCliente;
        @AuraEnabled public String numeroMaterial;
        @AuraEnabled public String OficinaVentas;
        @AuraEnabled public String ListaPrecios;
        @AuraEnabled public String GrupoMateriales;
        @AuraEnabled public String GrupoArticulos;
        @AuraEnabled public String GrupoClientes;
        @AuraEnabled public String ClaseDoc;
        @AuraEnabled public String CanalPromocion;
    }

    /*******************************************************************
    Purpose: Genera un objeto Descuento__c
    Parameters: WrapperSecuencesParam Param, WrapperSecuences DiscountsBySecuence
    Returns: Descuento__c 
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    public static Descuento__c getDescuento(String codigoSecuencia,IMP_DescuentosManager.T_A000 descuento){
        
        Descuento__c descuentoSF = new Descuento__c(
            IMP_SecuenciaAcceso__c  = codigoSecuencia,
            IMP_ClaseCondicion__c = descuento.KSCHL,
            IMP_OrganizacionVentas__c  = descuento.VKORG,
            IMP_CanalVentas__c = descuento.VTWEG,
            IMP_NumeroCliente__c  = descuento.KUNNR,
            IMP_NumeroMaterial__c  =descuento.MATNR!= null? descuento.MATNR.replaceFirst('^0+', ''):'',
            IMP_ImportePorcentaje__c  =descuento.KBETR != null ?  Decimal.valueOf(descuento.KBETR.trim().replaceAll('-', '')): 0,
            IMP_UnidadCondicion__c  = descuento.KONWA,
            IMP_FechaInicial__c = Date.valueOf(descuento.DATAB.substring(0,4)+'-'+descuento.DATAB.substring(4,6)+'-'+descuento.DATAB.substring(6,8)),
            IMP_FechaFinal__c = descuento.DATBI =='99991231' ? Date.valueOf(2100+'-'+descuento.DATBI.substring(4,6)+'-'+descuento.DATBI.substring(6,8)):Date.valueOf(descuento.DATBI.substring(0,4)+'-'+descuento.DATBI.substring(4,6)+'-'+descuento.DATBI.substring(6,8)),
            IMP_OficinaVentas__c = descuento.VKBUR,
            IMP_Lote__c = descuento.CHARG,
            IMP_ListaPrecios__c = descuento.PLTYP,
            IMP_GrupoClientes__c = descuento.KDGRP,
            IMP_GrupoArticulos__c = descuento.MATKL,
            IMP_GrupoMateriales__c = descuento.KONDM,
            IMP_ClaseDocumentoVentas__c  = descuento.AUART_SD,
            Name =  descuento.KNUMH ,
            IMP_IdExterno__c  = descuento.KNUMH );
        return descuentoSF;
    }
}