force-app/main/default/objects/Account/fields/clave_delcanal__c.field-meta.xml
<CustomField>
    <fullName>clave_delcanal__c</fullName>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Obras y Proyectos</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Des. Negocios</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Industriales</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Exportación</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Call Center</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ventas Directas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Mayorista</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Otras Ventas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/id_de_sap__c.field-meta.xml
<CustomField>
    <fullName>id_de_sap__c</fullName>
    <externalId>true</externalId>
    <label>Id de Sap</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ViaPago__c.field-meta.xml
<CustomField>
    <fullName>ViaPago__c</fullName>
    <label>Vía de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>via_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Descuento__c/Descuento__c.object-meta.xml
<CustomObject>
    <label>Descuento</label>
    <nameField>
        <label>Nombre de Descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Descuento__c/fields/IMP_Lote__c.field-meta.xml
<CustomField>
    <fullName>IMP_Lote__c</fullName>
    <description>El número de lote es la asignación que se le da a el material fabricado en lotes, partidas o lotes de producción a un lote determinado de forma unívoca.</description>
    <label>Lote</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/pedido__c.field-meta.xml
<CustomField>
    <fullName>pedido__c</fullName>
    <description>Número de pedido en SAP</description>
    <externalId>true</externalId>
    <label>ID Pedido SAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ViaPago__c.field-meta.xml
<CustomField>
    <fullName>ViaPago__c</fullName>
    <label>Vía de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>via_pago</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DescuentoManual__c.field-meta.xml
<CustomField>
    <fullName>DescuentoManual__c</fullName>
    <description>Campo usado para almacenar el descuento total.</description>
    <label>Descuento Manual</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IMP_Descuento__c.field-meta.xml
<CustomField>
    <fullName>IMP_Descuento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Descuento que aplica de acuerdo a promociones</description>
    <label>Descuento promoción relacion</label>
    <referenceTo>Descuento__c</referenceTo>
    <relationshipLabel>Productos de pedidos</relationshipLabel>
    <relationshipName>Productos_de_pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IMP_LlaveExclusiva__c.field-meta.xml
<CustomField>
    <fullName>IMP_LlaveExclusiva__c</fullName>
    <description>Número de pedido + posición + código del producto</description>
    <externalId>true</externalId>
    <label>Llave exclusiva</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IMP_Posicion__c.field-meta.xml
<CustomField>
    <fullName>IMP_Posicion__c</fullName>
    <description>Almacena el valor de la posición que se envia a SAP</description>
    <label>Posición</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Grupo_de_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Vendedor__c</fullName>
    <label>Grupo de Vendedor</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/via_pago.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>C</fullName>
        <label>Cheque</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>Deposito</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>Efectivo</label>
    </customValue>
    <customValue>
        <fullName>F</fullName>
        <label>Tarjeta de crédito</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Cheque Prod IQ</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>Tarjeta de Débito</label>
    </customValue>
    <customValue>
        <fullName>I</fullName>
        <label>Nota de Credito</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Por Definir</label>
    </customValue>
    <customValue>
        <fullName>T</fullName>
        <label>Transferencia Bancaria</label>
    </customValue>
    <masterLabel>Via de pago</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_EnvioPedidoSAP.cls
/************************************************************************
Name: IMP_EnvioPedidoSAP
Copyright © 2022 Salesforce
========================================================================
Purpose:Enviar un pedido a SAP.
Controller
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      rotrejo@ts4.mx    22/03/2022     INITIAL        DEV CSR:
************************************************************************/
public without sharing class IMP_EnvioPedidoSAP {
  public String I_BSTKD; //Test3
  public cls_I_ITEM[] I_ITEM;
  public String I_KUNNR; //0001036070
  public String I_PURCHDATE; //
  public String I_VKBUR; //MIXC
  public String I_VKGRP; //001
  public String I_VKORG; //IMPQ
  public String I_VTWEG; //02
  public String I_ZWELS; //
  public String E_VBELN;
  public String E_TEXT;
  public String ZLSCH;
  public String BSTDK;

  ///////SAP v2///////
  public String AUART;
  public String SPART;
  public String PRCTR;
  public String NETWR;
  public String ERNAM;
  public String GBSTK;
  public String ZTERM;
  public String EXT1;
  public String EXT2;
  public Decimal EXT3;
  public String BEZEI;
  public String LTEXT;

  public class cls_I_ITEM {
    public String POSNR; //10
    public String MATNR; //000000000010001377
    public String ARKTX; //
    public Decimal KWMENG; //1
    public String ZLSCH; //T
    public String KSCHL; //
    public Decimal KAWRT; //0
    public String CHARG; //Lote
  }

  /*******************************************************************
    Purpose: Genera el cuerpo de la solicitud a enviar.
    Parameters: Order pedido
    Returns: String
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
  public static String generateJSON(Order pedido) {
    User usuario = [
      SELECT Id, Username, Grupo_de_Vendedor__c
      FROM User
      WHERE Id = :UserInfo.getUserId()
    ];
    String fechaFinal = System.Now().format('YYYY/MM/dd');
    IMP_EnvioPedidoSAP newPedido = new IMP_EnvioPedidoSAP();
    newPedido.I_BSTKD = 'SFDC' + pedido.Ordernumber;
    newPedido.ZLSCH = '';
    newPedido.I_KUNNR = pedido.Account.id_de_sap__c; //Numero Cliente Id_sap__c/cuenta
    newPedido.I_PURCHDATE = fechaFinal.replace('/', ''); //Fecha de confirmacion del pedido
    newPedido.I_VKBUR = pedido.Pricebook2.Sucursal__c; //Centro subministrador  Pricebook2/Sucursal__c
    newPedido.I_VKGRP = String.valueOf(usuario.Grupo_de_Vendedor__c) == null
      ? ''
      : String.valueOf(usuario.Grupo_de_Vendedor__c); //Grupo vendedor / Grupo_de_Vendedor__c/User
    newPedido.I_VKORG = 'IMPQ'; //Valor campturado por SAP
    newPedido.I_VTWEG = pedido.Account.clave_delcanal__c; //Lista de Precios SAP / Pricebook2
    newPedido.I_ZWELS = pedido.ViaPago__c; //no se envia
    newPedido.BSTDK = '';
    List<cls_I_ITEM> listProducts = new List<cls_I_ITEM>();

    set<Id> IdDiscounts = new Set<Id>();
    List<OrderItem> ListItem = [
      SELECT
        Id,
        Product2.ProductCode,
        Quantity,
        DescuentoManual__c,
        IMP_Descuento__c
      FROM OrderItem
      WHERE OrderId = :pedido.Id
      ORDER BY CreatedDate
    ];
    for (OrderItem oItem : ListItem) {
      IdDiscounts.add(oItem.IMP_Descuento__c);
    }
    Map<Id, Descuento__c> MapLote = new Map<Id, Descuento__c>(
      [
        SELECT Id, IMP_Lote__c
        FROM Descuento__c
        WHERE ID IN :IdDiscounts AND IMP_Lote__c != NULL
      ]
    );

    Integer counter = 10;
    for (OrderItem item : ListItem) {
      cls_I_ITEM prod = new cls_I_ITEM();
      prod.POSNR = String.valueOf(counter);
      item.IMP_Posicion__c = counter;
      prod.MATNR = item.Product2.ProductCode; //Codigo del producto SF
      prod.ARKTX = ''; //Vacio
      prod.KWMENG = item.Quantity; //Cantidad /Quantity/ OrderItem
      prod.ZLSCH = pedido.ViaPago__c; //Via de pago //Pedido /ViaPago__c
      prod.KSCHL = ''; //vacio
      prod.KAWRT = item.DescuentoManual__c == null
        ? 0
        : item.DescuentoManual__c; //Descuento
      prod.CHARG = MapLote.containsKey(item.IMP_Descuento__c)
        ? MapLote.get(item.IMP_Descuento__c).IMP_Lote__c
        : '';
      listProducts.add(prod);
      counter += 10;
      System.debug('Prueba lote');
      System.debug(prod.MATNR);
      System.debug(prod.CHARG);
    }
    //update listItems;
    newPedido.I_ITEM = listProducts;
    System.debug('BODY PEDIDO Json request');
    System.debug(JSON.serialize(newPedido));
    Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(
      JSON.serialize(newPedido)
    );

    // Modificar la estructura de "I_ITEM" de un objeto a un mapa con una lista
    Map<String, Object> iItemMap = new Map<String, Object>();
    iItemMap.put('item', jsonMap.get('I_ITEM'));
    jsonMap.put('I_ITEM', iItemMap);

    String modifiedJSON = JSON.serialize(jsonMap);
    System.debug('JSON modificado: ' + modifiedJSON);
    return modifiedJSON;
  }

  /*******************************************************************
    Purpose: Envia el pedido a SAP
    Parameters: Order pedido
    Returns: Wrapper
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
  public static Wrapper getOrder(Order pedido) {
    Wrapper salida = new Wrapper();
    String body = generateJSON(pedido);
    HttpResponse response = IMP_CalloutUtils.getResponse(
      body,
      IMP_ServiceConstants.PEDIDO_API_URL
    );
    System.debug('Response body: ' + response.getBody());
    Map<String, Object> jsonData = (Map<String, Object>) JSON.deserializeUntyped(
        response.getBody()
      );
    
      convertirAListaSiNecesario(jsonData, 'I_ITEM');
    
      String modifiedJson = JSON.serialize(jsonData);
      System.debug('Response body Moficado 1: ' + modifiedJson);
      String newJsonString = convertObjectToArray(modifiedJson, 'I_ITEM');
    System.debug('Response body Moficado 2: ' + newJsonString);
    IMP_EnvioPedidoSAP reponseOrder = (IMP_EnvioPedidoSAP) JSON.deserialize(
      newJsonString,
      IMP_EnvioPedidoSAP.class
    );
    if (reponseOrder.E_VBELN != '') {
      salida.mensaje = reponseOrder.E_VBELN;
      salida.status = 'SUCCESS';
      pedido.pedido__c = reponseOrder.E_VBELN;
      update pedido;
      salida.pedido = pedido;
      List<OrderItem> listItems = [
        SELECT Id, Product2.ProductCode, Quantity, DescuentoManual__c
        FROM OrderItem
        WHERE OrderId = :pedido.Id
        ORDER BY CreatedDate
      ];
      Integer pos = 10;
      for (OrderItem item : listItems) {
        item.IMP_Posicion__c = pos;
        item.IMP_LlaveExclusiva__c =
          reponseOrder.E_VBELN +
          '-' +
          pos +
          '-' +
          item.Product2.ProductCode;
        pos += 10;
      }
      System.debug(
        'Pedido :' + pedido.pedido__c + '  Via de pago : ' + pedido.ViaPago__c
      );
      update listItems;
    } else {
      salida.mensaje = reponseOrder.E_TEXT;
      salida.status = 'ERROR';
    }
    return salida;
  }

  public class Wrapper {
    @AuraEnabled
    public String mensaje { get; set; }
    @auraEnabled
    public String status { get; set; }
    @auraEnabled
    public Order pedido { get; set; }
  }

  public static String convertObjectToArray(
    String jsonString,
    String objectKey
  ) {
    // Convertir el JSON original a un mapa de objetos sin tipo
    Map<String, Object> jsonData = (Map<String, Object>) JSON.deserializeUntyped(
      jsonString
    );
    if (jsonData.containsKey(objectKey)) {
      Object ObjectJson = jsonData.get(objectKey);
      if (ObjectJson instanceof Map<String, Object>) {
        Map<String, Object> MapObject = (Map<String, Object>) ObjectJson;
        if (
          MapObject.containsKey('item') &&
          MapObject.get('item') instanceof List<Object>
        ) {
          List<Object> itemList = (List<Object>) MapObject.get('item');
          jsonData.put(objectKey, itemList);
          jsonData.remove('item');
        }
      }
    }
    String updatedJsonDataString = JSON.serialize(jsonData);

    // Paso 4: Convertir el mapa en formato JSON
    return JSON.serialize(jsonData);
  }

  public static void convertirAListaSiNecesario(
    Map<String, Object> jsonData,
    String clave
  ) {
    Object objeto = jsonData.get(clave);
    if (String.valueOf(objeto).contains('{item={')) {
      Map<String, Object> mapa = (Map<String, Object>) objeto;
      List<Object> lista = new List<Object>();
      lista.add(mapa.get('item'));
      mapa.put('item', lista);
    }
  }
}