force-app/main/default/objects/Account/fields/ListaPrecios__c.field-meta.xml
<CustomField>
    <fullName>ListaPrecios__c</fullName>
    <label>Lista de precios SAP</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>clave_delcanal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>03</fullName>
                <label>Mostrador</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Distribuidores</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Requiereaprobacion__c.field-meta.xml
<CustomField>
    <fullName>Requiereaprobacion__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Marque este campo para solicitar el alta de clientes</inlineHelpText>
    <label>¿Requiere Alta?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrecioTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotal__c</fullName>
    <label>Precio total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requiereaprobacion__c.field-meta.xml
<CustomField>
    <fullName>Requiereaprobacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Requiere aprobación?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalPartidas__c.field-meta.xml
<CustomField>
    <fullName>TotalPartidas__c</fullName>
    <label>Total</label>
    <summarizedField>OpportunityLineItem.TotalPrice</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/TotalPartidas__c.field-meta.xml
<CustomField>
    <fullName>TotalPartidas__c</fullName>
    <label>Total</label>
    <summarizedField>OrderItem.UnitPrice</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/PoliticaDescuento__c/PoliticaDescuento__c.object-meta.xml
<CustomObject>
    <label>Política de descuento</label>
    <nameField>
        <label>Nombre de Política de descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Politicas de descuento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook2/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Centro_suministrador</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Grupo_de_Materiales__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Materiales__c</fullName>
    <label>Grupo de Materiales</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grupo_de_materiales</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/AprobacionCliente__c.field-meta.xml
<CustomField>
    <fullName>AprobacionCliente__c</fullName>
    <description>Estatus de la aprobación</description>
    <label>Aprobación cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/PrecioTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotal__c</fullName>
    <label>Precio Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Requiereaprobacion__c.field-meta.xml
<CustomField>
    <fullName>Requiereaprobacion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Este campo se marcará cuando la cotización tenga  al menos un descuento en alguno de sus productos.</description>
    <label>¿Requiere aprobación?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TotalPartidas__c.field-meta.xml
<CustomField>
    <fullName>TotalPartidas__c</fullName>
    <label>Total</label>
    <summarizedField>QuoteLineItem.PrecioTotalConDescuentos__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Descuento_adicional__c.field-meta.xml
<CustomField>
    <fullName>Descuento_adicional__c</fullName>
    <description>Este descuento se ingresa de forma manual</description>
    <label>Descuento adicional</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DescuentoSAP__c.field-meta.xml
<CustomField>
    <fullName>DescuentoSAP__c</fullName>
    <label>Descuento SAP</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PoliticaDescuento__c.field-meta.xml
<CustomField>
    <fullName>PoliticaDescuento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Política de descuento</label>
    <referenceTo>PoliticaDescuento__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrecioTotalConDescuentos__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotalConDescuentos__c</fullName>
    <label>Precio Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Centro_suministrador.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AC01</fullName>
        <label>Acapulco</label>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
        <label>Cancún</label>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
        <label>Chihuahua</label>
    </customValue>
    <customValue>
        <fullName>CU01</fullName>
        <label>Culiacán</label>
    </customValue>
    <customValue>
        <fullName>CV01</fullName>
        <label>Cuernavaca</label>
    </customValue>
    <customValue>
        <fullName>ERMI</fullName>
        <label>Ermita</label>
    </customValue>
    <customValue>
        <fullName>GD01</fullName>
        <label>Guadalajara</label>
    </customValue>
    <customValue>
        <fullName>HE01</fullName>
        <label>Hermosillo</label>
    </customValue>
    <customValue>
        <fullName>IMPQ</fullName>
        <label>Imperquimia</label>
    </customValue>
    <customValue>
        <fullName>LE01</fullName>
        <label>León</label>
    </customValue>
    <customValue>
        <fullName>ME01</fullName>
        <label>Mérida</label>
    </customValue>
    <customValue>
        <fullName>ME02</fullName>
        <label>Mérida II</label>
    </customValue>
    <customValue>
        <fullName>MIXC</fullName>
        <label>Mixcoac</label>
    </customValue>
    <customValue>
        <fullName>MT01</fullName>
        <label>Monterrey</label>
    </customValue>
    <customValue>
        <fullName>PSUR</fullName>
        <label>Perisur</label>
    </customValue>
    <customValue>
        <fullName>QE01</fullName>
        <label>Querétaro</label>
    </customValue>
    <customValue>
        <fullName>RAZA</fullName>
        <label>La Raza</label>
    </customValue>
    <customValue>
        <fullName>RIVI</fullName>
        <label>Riviera</label>
    </customValue>
    <customValue>
        <fullName>SATE</fullName>
        <label>Satélite</label>
    </customValue>
    <customValue>
        <fullName>TJ01</fullName>
        <label>Tijuana</label>
    </customValue>
    <customValue>
        <fullName>VE01</fullName>
        <label>Veracruz</label>
    </customValue>
    <customValue>
        <fullName>VI01</fullName>
        <label>Villahermosa</label>
    </customValue>
    <customValue>
        <fullName>IMPV</fullName>
        <label>Imperquimia Ventas</label>
    </customValue>
    <customValue>
        <fullName>ICAC</fullName>
        <label>ICA CONVENIO</label>
    </customValue>
    <masterLabel>Centro suministrador</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grupo_de_materiales.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Lineas Generales</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Lineas Mayoristas</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Lineas Populares</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Commodity</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Especiales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Ultra Comodity</label>
    </customValue>
    <masterLabel>Grupo de materiales</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IMP_AprobarCotizacionController.cls
/************************************************************************
Name: IMP_AprobarCotizacionController
Copyright © 2022 Salesforce
========================================================================
Purpose:
Clase controller para mostrar datos de la cotización en el componente de IMP_AprobarCotizacion
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
 2.0      dmarcos@ts4.mx     11/03/2022     
************************************************************************/
public without sharing class IMP_AprobarCotizacionController {
    
    /*******************************************************************
   Purpose: Mostrar información de la cotización en el componente IMP_AprobarCotizacion .
   Parameters: Id cotizacionId
   Returns: DataQuoteWrapper
   Throws [Exceptions]:
   Information about changes (versions) []:
   ********************************************************************/
    @auraEnabled
    public static DataQuoteWrapper getInitialData(Id cotizacionId){
        
        DataQuoteWrapper returnData = new DataQuoteWrapper();
          
        Quote cotizacion=[SELECT Id ,Name, Pricebook2Id,Pricebook2.Sucursal__c, CurrencyIsoCode, Opportunity.Id, Opportunity.Name,
                          Status, IsSyncing,TotalPrice,Tax,GrandTotal,Requiereaprobacion__c,Account.Name, Account.ListaPrecios__c,
                          TotalPartidas__c,PrecioTotal__c, QuoteNumber,AprobacionCliente__c
                          FROM Quote WHERE Id =: cotizacionId];
        
        list<QuoteLineItem> listQuoteslines=[SELECT Id,Discount, Quantity, TotalPrice,PoliticaDescuento__c,DescuentoSAP__c,
                                             UnitPrice,PricebookEntryId, PricebookEntry.Id, PricebookEntry.Name, PricebookEntry.UnitPrice,
                                             PricebookEntry.Product2.Id,PricebookEntry.Product2.IsActive,Product2.Name, PricebookEntry.Product2.Description, Product2.Family,
                                             Product2.ProductCode,Product2.Grupo_de_Materiales__c,
                                             Product2.IsActive,QuoteId,Descuento_adicional__c,PrecioTotalConDescuentos__c
                                             FROM QuoteLineItem WHERE QuoteId = :cotizacionId ORDER BY CreatedDate];
        
        
        returnData.status='SUCCESS';
        returnData.cotizacion=cotizacion;
        returnData.listQuoteLineItems=listQuoteslines;      
        return returnData;
        
    }
    
    /*******************************************************************
   Purpose: Actualiza la cotización con estatus de Aprobada o Rechazada según el valor de la lista de selección.
   Parameters: String cotizacionId,String valuePickList
   Returns: DataQuoteWrapper
   Throws [Exceptions]:
   Information about changes (versions) []:
   ********************************************************************/
    @AuraEnabled
    public static DataQuoteWrapper actualizarCotizacion(String cotizacionId, String valuePickList){
        DataQuoteWrapper returnData = new DataQuoteWrapper();
        try {
            Quote cotizacion = [SELECT Id,AprobacionCliente__c
                                              FROM Quote 
                                              WHERE Id =: cotizacionId];
            cotizacion.AprobacionCliente__c=valuePickList;
            upsert cotizacion;
            returnData.status = 'Ok';
            
        } catch(Exception e) {
            returnData.status = 'Error';
        }
        
        return returnData;
    }
    
    /*******************************************************************
   Purpose: Mostrar valores del campo AprobacionCliente__c en el componente IMP_AprobarCotizacion.
   Parameters: 
   Returns: Map<String, String>
   Throws [Exceptions]:
   Information about changes (versions) []:
   ********************************************************************/
    @AuraEnabled 
    public static Map<String, String> getAprobacionFieldValue(){
        Map<String, String> options = new Map<String, String>();
        
        Schema.DescribeFieldResult fieldResult = Quote.AprobacionCliente__c.getDescribe();
        
        List<Schema.PicklistEntry> pValues = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p: pValues) {
            
            options.put(p.getValue(), p.getLabel());
        }
        return options;
    }
    
    public class DataQuoteWrapper{
        @auraEnabled public Quote cotizacion {get; set;}  
        @auraEnabled public list<QuoteLineItem> listQuoteLineItems {get; set;}
        @auraEnabled public String status {get;set;}

    }
}