force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para almacenar las facturas del pedido</description>
    <label>Factura</label>
    <nameField>
        <label>Número de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/IMP_LlaveExclusiva__c.field-meta.xml
<CustomField>
    <fullName>IMP_LlaveExclusiva__c</fullName>
    <description>Campo usado para realizar modificaciones desde un servicio externo</description>
    <externalId>true</externalId>
    <label>Llave Exclusiva</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IMP_Documentos_Shedule.cls
/************************************************************************
Name: IMP_Documentos_Shedule
Copyright © 2023 Salesforce
========================================================================
Purpose:
Scheduler que se ejecuta en un horario predeterminado en trabajos
programados, realiza la consulta de documentos de acuerdo a la fecha.
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
  1.0      rotrejo@ts4.mx    02/05/2023     INITIAL        DEV CSR:
************************************************************************/
global class IMP_Documentos_Shedule implements Schedulable,Database.AllowsCallouts {
    public void execute(SchedulableContext ctx) {
        getDailyDocs();
    }
    
    @future(callout=true) public static void getDailyDocs(){
        String fechaInicial = (System.now()-1).format('dd/MM/YYYY');
        String fechaFinal= System.now().format('dd/MM/YYYY');
        IMP_FlujoDocumentos.Wrapper newWrapper = IMP_FlujoDocumentos.getFacturasWrapper(null,fechaInicial.replace('/','.'),fechaFinal.replace('/','.'));
        Database.upsert(newWrapper.listFacturas,Factura__c.IMP_LlaveExclusiva__c , FALSE);
    }
}