force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para almacenar las facturas del pedido</description>
    <label>Factura</label>
    <nameField>
        <label>Número de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/IMP_LlaveExclusiva__c.field-meta.xml
<CustomField>
    <fullName>IMP_LlaveExclusiva__c</fullName>
    <description>Campo usado para realizar modificaciones desde un servicio externo</description>
    <externalId>true</externalId>
    <label>Llave Exclusiva</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IMP_BatchDocumentos.cls
public inherited sharing class IMP_BatchDocumentos implements Database.Batchable<sObject>,Database.AllowsCallouts, Database.Stateful{
    private List<sObject>  listFacts;
    
    public IMP_BatchDocumentos( List<sObject>  listFacts){
        this.listFacts=listFacts;
    }
    
    public Iterable<sObject> start(Database.BatchableContext BC){
        return this.listFacts;
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        System.debug(scope.size());
        if(scope.size()>0){
            List<Database.UpsertResult> results =  Database.upsert(scope,Factura__c.IMP_LlaveExclusiva__c , FALSE);
            for(Database.UpsertResult itemResult : results){
                if(itemResult.isSuccess()){
                    System.debug(itemResult.id+' - Registro Creado');
                }else{
                    System.debug(itemResult.getId() +' - Error: '+itemResult.getErrors());
                }
            }
        }
    }
    
    public void finish(Database.BatchableContext BC){
    }
    
}