force-app/main/default/objects/Lead/fields/Clase__c.field-meta.xml
<CustomField>
    <fullName>Clase__c</fullName>
    <description>Clase de Lead restringidos los valores de la lista</description>
    <label>Clase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Infraestructura</fullName>
            </value>
            <value>
                <fullName>Vivienda</fullName>
            </value>
            <value>
                <fullName>Edificacion</fullName>
            </value>
            <value>
                <fullName>Edificación</fullName>
                <isActive>false</isActive>
                <label>Edificación</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Clave_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Clave_Proyecto__c</fullName>
    <label>Clave Proyecto</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Descripcion_de_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_de_Proyecto__c</fullName>
    <description>Área de texto largo para almacenar la descripción del proyecto</description>
    <label>Descripcion del Proyecto</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DireccionCompania__c.field-meta.xml
<CustomField>
    <fullName>DireccionCompania__c</fullName>
    <description>Área de texto para dirección de la compañia</description>
    <label>Dirección de la compañia</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EtapaBIMSA__c.field-meta.xml
<CustomField>
    <fullName>EtapaBIMSA__c</fullName>
    <description>Etapa del lead para BIMSA</description>
    <label>EtapaBIMSA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Plan</fullName>
            </value>
            <value>
                <fullName>Plan</fullName>
            </value>
            <value>
                <fullName>Pre-Inicio</fullName>
            </value>
            <value>
                <fullName>Proyecto</fullName>
            </value>
            <value>
                <fullName>Inicio</fullName>
            </value>
            <value>
                <fullName>Obra Negociada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Fecha_de_inicio_del_proyecto__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio_del_proyecto__c</fullName>
    <description>Almacena la fecha de inicio del proyecto</description>
    <label>Fecha de inicio del proyecto</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/fecha_de_termino_proyecto__c.field-meta.xml
<CustomField>
    <fullName>fecha_de_termino_proyecto__c</fullName>
    <description>Almacena la fecha de termino</description>
    <label>Fecha de termino del proyecto</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/fecha_publicacion__c.field-meta.xml
<CustomField>
    <fullName>fecha_publicacion__c</fullName>
    <description>Fecha de publicación desde el servicio</description>
    <label>Fecha de publicación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/InversionBimsa__c.field-meta.xml
<CustomField>
    <fullName>InversionBimsa__c</fullName>
    <description>Monto de inversión de BR</description>
    <label>Inversión</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/numero_de_niveles__c.field-meta.xml
<CustomField>
    <fullName>numero_de_niveles__c</fullName>
    <description>Número de niveles desde la integración con BR</description>
    <label>Número de niveles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/numero_de_unidades__c.field-meta.xml
<CustomField>
    <fullName>numero_de_unidades__c</fullName>
    <description>Número de unidades desde la integración de BR</description>
    <label>Número de Unidades</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Productos__c.field-meta.xml
<CustomField>
    <fullName>Productos__c</fullName>
    <description>Almacena los productos de la integración de BR</description>
    <label>Productos</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <description>Sector desde la integración de BR</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gobierno</fullName>
            </value>
            <value>
                <fullName>Privado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/superficie_urbanizada__c.field-meta.xml
<CustomField>
    <fullName>superficie_urbanizada__c</fullName>
    <description>Superficie urbanizada desde la integración con BR</description>
    <label>Superficie Urbanizada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/superficieonstruida__c.field-meta.xml
<CustomField>
    <fullName>superficieonstruida__c</fullName>
    <description>Superficie urbanizada desde la integración con BRAnalytics</description>
    <label>Superficie Construida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/tipo_de_desarrollo__c.field-meta.xml
<CustomField>
    <fullName>tipo_de_desarrollo__c</fullName>
    <description>Tipo de desarrollo desde la integración con BRAnalytics</description>
    <label>Tipo de Desarrollo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Obra Nueva</fullName>
            </value>
            <value>
                <fullName>Adecuacion</fullName>
            </value>
            <value>
                <fullName>Remodelación</fullName>
            </value>
            <value>
                <fullName>Ampliacion</fullName>
            </value>
            <value>
                <fullName>Mantenimiento</fullName>
            </value>
            <value>
                <fullName>Rehabilitacion</fullName>
            </value>
            <value>
                <fullName>Rehabilitación</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/tipo_de_proyecto__c.field-meta.xml
<CustomField>
    <fullName>tipo_de_proyecto__c</fullName>
    <description>Tipo de proyecto desde BR Analytics</description>
    <label>Tipo de Proyecto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proyectos de Inversión</fullName>
            </value>
            <value>
                <fullName>Proyectos Contratados</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/unidad_superficie_urbanizada__c.field-meta.xml
<CustomField>
    <fullName>unidad_superficie_urbanizada__c</fullName>
    <description>Unidad superficie urbanizada desde la integración de BRAnalytics</description>
    <label>Unidad de Superficie Urbanizada</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/unidad_superficieonstruida__c.field-meta.xml
<CustomField>
    <fullName>unidad_superficieonstruida__c</fullName>
    <description>Unidad superficie construida desde la integración con BRAnalytics</description>
    <label>Unidad superficie construida</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Productos__c/Productos__c.object-meta.xml
<CustomObject>
    <label>Material Solicitado</label>
    <nameField>
        <label>Nombre de Material Solicitado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materiales Solicitados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/IMP_BRAnalyticsIntegration.cls
/************************************************************************
Name: IMP_BRAnalyticsIntegration
Copyright © 2022 Salesforce
========================================================================
Purpose:
Servicio web para la creación de prospectos desde BR Analytics
========================================================================
History:

VERSION        AUTHOR           DATE         DETAIL       Description   
2.0      dmarcos@ts4.mx     06/04/2022     
************************************************************************/
public without sharing class IMP_BRAnalyticsIntegration {
    
    /*******************************************************************
    Purpose: Obtener la respuesta del token.
    Parameters: 
    Returns: String
    Throws [Exceptions]:
    Information about changes (versions) []:
    ********************************************************************/
    @auraEnabled
    public static String retriveToken(){
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setHeader('Content-Type','application/x-www-form-urlencoded');
        req.setEndpoint(System.label.IMP_LinkToken);
        String user = System.label.IMP_UserBimsa;
        String password = System.label.IMP_PasswordBimsa;
        req.setBody('TUsr='+user + '&TWSPss='+password);
        Http http = new Http();
        HTTPResponse response = http.send(req);
        string[] listToken = String.valueOf(response.getBody()).split('>');
        string[] listTokenFinal = String.valueOf(listToken[2]).split('<');
        String token = listTokenFinal[0];
        return token;
    }
    
    /*******************************************************************
Purpose: Obtener xml de los proyectos publicados e insertar los prospectos.
Parameters: 
Returns: String
Throws [Exceptions]:
Information about changes (versions) []:
********************************************************************/
    @future(callout=true)
    public static void getDataAnalytics(String fechaConsulta){
        Map<String,List<String>> mapProductos = getProducts(fechaConsulta);
        List<Lead> listLeads = new List<Lead>();
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setHeader('Content-Type','application/x-www-form-urlencoded');
        req.setEndpoint(System.label.IMP_LinkProyectos);
        String user = System.label.IMP_UserBimsa;
        String password = System.label.IMP_PasswordBimsa;
        String fecha = fechaConsulta;
        String token = IMP_BRAnalyticsIntegration.retriveToken();
        req.setBody('Usr='+user + '&WSPss='+password +  '&Fecha='+fecha + '&TKN='+token);
        Http http = new Http();
        HTTPResponse response = http.send(req);
        
        Dom.Document doc = response.getBodyDocument();
        Dom.XMLNode datos = doc.getRootElement();
        List<Lead> listaLeads =[SELECT Id, Clave_Proyecto__c FROM Lead];
        map<String,Id> mappLe = new map<String,Id>();
        for(Lead l : listaLeads){
            mappLe.put(l.Clave_Proyecto__c,l.Id);
        }
        
        for(Dom.XMLNode child2 : datos.getChildElements()) {
            system.debug( child2.getChildElement('Clave_Proyecto',null).getText());   
            String tipoProyecto = child2.getChildElement('Clave_Proyecto',null).getText().substring(0,2);
            String productosDesc ='';
            if(mapProductos.containsKey(child2.getChildElement('Clave_Proyecto',null).getText())){
                for(String producto : mapProductos.get(child2.getChildElement('Clave_Proyecto',null).getText())){
                    productosDesc += producto+ ',';
                }
                
            }
            if(!mappLe.containsKey(child2.getChildElement('Clave_Proyecto',null).getText())){
                Lead lead = new Lead(
                    Description = child2.getChildElement('Proyecto ',null) != null ? child2.getChildElement('Proyecto',null).getText():'',
                    Clave_Proyecto__c = child2.getChildElement('Clave_Proyecto',null) != null ? child2.getChildElement('Clave_Proyecto',null).getText():'',
                    Company = child2.getChildElement('Compania',null) != null ? child2.getChildElement('Compania',null).getText():'',
                    EtapaBIMSA__c = child2.getChildElement('Etapa',null) != null ? child2.getChildElement('Etapa',null).getText():'',
                    Fecha_de_inicio_del_proyecto__c = date.valueOf(child2.getChildElement('Fecha_Inicio',null) != null ? child2.getChildElement('Fecha_Inicio',null).getText():''),
                    fecha_publicacion__c = date.valueOf(child2.getChildElement('Fecha_Publicacion',null) != null ? child2.getChildElement('Fecha_Publicacion',null).getText():''),
                    fecha_de_termino_proyecto__c = date.valueOf(child2.getChildElement('Fecha_Terminacion',null) != null ? child2.getChildElement('Fecha_Terminacion',null).getText():''),
                    InversionBimsa__c = Decimal.valueOf(child2.getChildElement('Inversion',null) != null ? child2.getChildElement('Inversion',null).getText():''),
                    Street = child2.getChildElement('Localizacion1',null) != null ? child2.getChildElement('Localizacion1',null).getText():'',
                    Postalcode = child2.getChildElement('C.P.',null) != null ? child2.getChildElement('C.P.',null).getText():'',
                    City = child2.getChildElement('Del_Cd_Mun_Proyecto',null) != null ? child2.getChildElement('Del_Cd_Mun_Proyecto',null).getText():'',
                    State = child2.getChildElement('Estado_Proyecto',null) != null ? child2.getChildElement('Estado_Proyecto',null).getText():'',
                    CurrencyIsoCode = child2.getChildElement('Moneda',null) != null ? 'MXN':'',
                    Title = child2.getChildElement('Titulo_1',null) != null ? child2.getChildElement('Titulo_1',null).getText():'',
                    FirstName = child2.getChildElement('Nombre_1',null) != null ? child2.getChildElement('Nombre_1',null).getText():'',
                    LastName = child2.getChildElement('Paterno_1',null) != null ? child2.getChildElement('Paterno_1',null).getText() +' '+child2.getChildElement('Materno_1',null).getText():'',
                    Email = child2.getChildElement('Email_1',null) != null ? child2.getChildElement('Email_1',null).getText():'',
                    numero_de_niveles__c = Decimal.valueOf(child2.getChildElement('Num_Niveles',null).getText().trim() != '' ? child2.getChildElement('Num_Niveles',null).getText():'0'),
                    numero_de_unidades__c = Integer.valueOf(child2.getChildElement('Numero_Unidades',null).getText().trim() != '' ? child2.getChildElement('Numero_Unidades',null).getText():'0'),
                    Sector__c = child2.getChildElement('Sector',null) != null ? child2.getChildElement('Sector',null).getText():'',
                    superficieonstruida__c = Decimal.valueOf(child2.getChildElement('Sup_Construida',null) != null ? child2.getChildElement('Sup_Construida',null).getText():''),
                    superficie_urbanizada__c = Decimal.valueOf(child2.getChildElement('Sup_Urbanizada',null) != null ? child2.getChildElement('Sup_Urbanizada',null).getText():''),
                    Phone = child2.getChildElement('Telefono1',null) != null ? child2.getChildElement('Telefono1',null).getText() + child2.getChildElement('Lada',null).getText():'',
                    tipo_de_desarrollo__c = child2.getChildElement('Tipo_Desarrollo',null) != null ? child2.getChildElement('Tipo_Desarrollo',null).getText():'',
                    unidad_superficieonstruida__c = child2.getChildElement('Unidad',null) != null ? child2.getChildElement('Unidad',null).getText():'',
                    unidad_superficie_urbanizada__c = child2.getChildElement('Unidad_',null) != null ? child2.getChildElement('Unidad_',null).getText():'',
                    Productos__c = productosDesc =='' ?  'No se encontraron productos':productosDesc,
                    LeadSource = 'BIMSA',
                    Clase__c = child2.getChildElement('Clase',null) != null ? child2.getChildElement('Clase',null).getText():'',
                    tipo_de_proyecto__c = tipoProyecto =='OC' ? 'Proyectos Contratados' : 'Proyectos de Inversión',
                    RecordTypeId =System.label.RecordTypeIdProspecto,
                    Descripcion_de_Proyecto__c = child2.getChildElement('Descripcion',null).getText()+' '+child2.getChildElement('Descripcion_Extra',null).getText()+' '+
                    child2.getChildElement('Observaciones',null).getText()+' '+child2.getChildElement('Acabados',null).getText(),
                    DireccionCompania__c = child2.getChildElement('Direccion_Compania',null).getText()+' '+child2.getChildElement('Del_Cd_Mun_Compania',null).getText()+' '+
                    child2.getChildElement('Estado_Compania',null).getText()+' '+child2.getChildElement('C.P.Compania',null).getText()+' '+child2.getChildElement('Colonia',null).getText()
                    
                );
                listLeads.add(lead);
            }
            
        }
        Database.SaveResult[] saveResultList = Database.insert(listLeads, false);        
        for (Database.SaveResult sr : saveResultList) {
            if (sr.isSuccess()) { 
                System.debug('Successfully inserted lead. Lead ID: ' + sr.getId());
            }
            else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred. '+err.getMessage());                    
                    
                }
            }
        }
        
    }
    
    /*******************************************************************
Purpose: Obtener xml de los productos publicados.
Parameters: 
Returns: String
Throws [Exceptions]:
Information about changes (versions) []:
********************************************************************/
    public static Map<String,List<String>> getProducts(String fechaConsulta){
        HttpRequest req = new HttpRequest();
        req.setTimeout(120000);
        req.setMethod('GET');
        req.setHeader('Content-Type','application/x-www-form-urlencoded');
        req.setEndpoint(System.label.IMP_LinkProductos);
        String user = System.label.IMP_UserBimsa;
        String password = System.label.IMP_PasswordBimsa;
        String fecha = fechaConsulta;
        String token = IMP_BRAnalyticsIntegration.retriveToken();
        req.setBody('Usr='+user + '&WSPss='+password +  '&Fecha='+fecha + '&TKN='+token );
        Http http = new Http();
        HTTPResponse response = http.send(req);
        Map<String,List<String>> mapProductos = new Map<String,List<String>>();
        
        
        Dom.Document doc = response.getBodyDocument();  
        Dom.XMLNode datos = doc.getRootElement();
        for(Dom.XMLNode child : datos.getChildElements()) {
            if(!mapProductos.containskey(child.getChildElement('Clave_proyecto',null).getText())){
                mapProductos.put(child.getChildElement('Clave_proyecto',null).getText(),new List<String>());
            }
            mapProductos.get(child.getChildElement('Clave_proyecto',null).getText()).add(child.getChildElement('Producto_Clave',null).getText());       
        }        
        
        return mapProductos;     
    }
}