force-app/main/default/objects/Descuento__c/Descuento__c.object-meta.xml
<CustomObject>
    <label>Descuento</label>
    <nameField>
        <label>Nombre de Descuento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Descuento__c/fields/IMP_IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IMP_IdExterno__c</fullName>
    <description>Campo usado para almacenar el id externo de los descuentos</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchUpsertDiscounts.cls
public class BatchUpsertDiscounts implements Database.Batchable<Descuento__c>,Database.AllowsCallouts{

    private List<Descuento__c>  listDicounts;
   
    
    public BatchUpsertDiscounts(List<Descuento__c>  listDicounts){
        this.listDicounts=listDicounts;
    }
    
    public Iterable<Descuento__c> start(Database.BatchableContext BC){
        System.debug('Descuentos entrantes BatchUpsertDiscounts :: '+this.listDicounts.size());
        
        return this.listDicounts;
    }
    
    public void execute(Database.BatchableContext BC, List<Descuento__c> scope){
        List<Database.UpsertResult> results = Database.upsert(scope,Descuento__c.IMP_IdExterno__c , FALSE);
        for(Database.UpsertResult itemResult : results){
            if(!itemResult.isSuccess()){
                system.debug(itemResult.getErrors());
            }
        }
        System.debug('Registros modificados : BatchUpsertDiscounts '+results.size());
        
    }
    
    public void finish(Database.BatchableContext BC){
      
    }      
    
}